### ISSUE TITLE
Markov Chain을 고등학생에게 설명하려면 어떤 방식이 제일 좋을까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#1]
[1회차] 2022년 8월 23일 화요일

**Comment by jarammm** [comment]
마르코프 체인은 마르코프 특성(Markov Property)을 지닌 이산시간(Discrete time) 확률과정(stochastic process)입니다.

- 왜 **체인**인가하면, 초기 상태를 나타내는 벡터가 주어지고, 현재 상태에 따라 다음 상태를 확률적으로 예측하는 행렬(상태변이행렬, 또는 상태전이행렬이라 합니다)이 있을 때,  그 행렬과 벡터의 곱이 다음 상태 예측의 입력 벡터로 쓰이는 것이 반복되면서 연쇄적으로 이어지기 때문에 체인이라고 합니다.
1. 먼저 마르코프 특성은 과거 상태들과 현재 상태가 주어졌을 때, 미래 상태는 과거 상태와는 독립적으로(=영향을 끼치지 않고), 현재 상태에 의해서만 결정된다는 것을 의미합니다. 다시 말해, 과거와 현재 상태 모두를 고려했을 때 미래 상태가 나타날 확률과 현재 상태만을 고려했을 때 미래 상태가 발생할 확률이 동일하다는 것입니다. 마르코프 특성을 식으로 나타내면 다음과 같습니다.

$$
P[s_{t+1}|s_t] = P[s_{t+1}|s_1,\cdots , s_t]
$$

마르코프 특성은 과거 상태를 기억하지 않기 때문에 메모리리스(memoryless) 프로세스라고도 불린다. 마르코프 프로세스도 같은 의미입니다.

1. 그리고 이산 시간은 시간이 연속적으로 변하지 않고, 이산적으로 변함을 의미합니다. 예를 들면 1시, 2시 혹은 시간 범주가 있을 때 이를 이산 시간이라 할 수 있습니다.
2. 마지막으로 확률 과정은 **시간에 따라** 어떤 사건이 발생할 확률이 변화하는 과정을 의미합니다.
- 주사위 던지기처럼 모든 시행이 독립적으로 발생하는 경우는 0차 마르코프 체인, 바로 직전 한 개의 상태에만 영향을 받는 경우는 1차 마르코프 체인이라고 합니다. 직전 n개 상태에 영향을 받는 경우 n차 마르코프 체인이라 합니다.

**Comment by import-max** [comment]
#### Markov Chain 
* markov chain이란, 어떤 사건이 n이라는 시점에서 발생했을 때, 바로 직전 시점의 상태의 영향을 받는 것에 대한 확률변수를 의미합니다. 예를 들어서 1초 마다 이벤트가 발생할 때, 10초의 상태가 한 단계 전인 9초의 상태에 의존한다면 1차 마코프 체인, 두 단계 전인 8초에만 의존한다면 2차 마코프 체인이라고 말할 수 있습니다.
* 반대로 마코프 체인의 성질이 없다는 것은 이벤트가 독립적으로 실행되는 것으로, 바로 전에 주사위가 어떤 것이 나왔든 주사위에서 특정 숫자가 나올 확률은 항상 1/6인 경우를 이야기 합니다.

**Comment by kimyuuuuuu** [comment]
- 마코프 체인이란 마코프 성질을 지닌 이산 확률 과정(Discrete-time Stochastic Pross)을 말한다.

- 고등학생이 배운 이산 확률을 사용하여 설명한다. 
예를 들어, 이번에 나온 <닥터 스트레인지 2> 를 예시로 들자면, 차베즈가 전에 어디에 있느냐에 따라서, 다음에 갈 장소가 정해진다. 

- 차베즈가 현재 있는 장소에서 닥스가 사망할 경우 → 다른 시공간의 닥스에게로
- 차베즈가 현재 있는 장소에서 닥스가 살아있는데, 본인이 위험한 경우 → 위험에서 벗어날 수 있는 곳으로

**Comment by miinkang** [comment]
동전 던지기는 독립 시행입니다. n번째의 상태가 n+1번쨰의 상태에 영향을 주지 않습니다. 마르코프 체인은 이와 달리 n번째 상태가 n+1번쨰 상태를 결정하는데 영향을 미칩니다. 이런 성질을 지닌 이산 확률 과정을 마르코프 체인이라고 합니다.

**Comment by jarammm** [comment]
질문) 왜 "체인"이라는 이름이 붙었나요?
