### ISSUE TITLE
엔트로피(entropy)에 대해 설명해주세요. 가능하면 Information Gain도요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#10]
[3차시] 2022년 8월 30일 화요일

**Comment by jarammm** [comment]
- 엔트로피(entropy)에 대해 설명해주세요. 가능하면 Information Gain도요.
    - 엔트로피 : 주어진 데이터의 혼잡도를 의미합니다.
        - 엔트로피는 각각의 데이터가 하나의 클래스에 속할 확률이 높다면 엔트로피가 낮고, 여러 클래스에 속할 확률이 비슷하다면 높습니다.
    - Information Gain : 데이터가 어떤 클래스에 속할 확률이 커짐에 따라 정보를 잘 얻게 되는 것을 말하며, 이는 감소되는 엔트로피 양을 의미합니다.
        - 수식으로는 기존 시스템의 엔트로피에서 현재 엔트로피를 뺀 값으로 표현됩니다. 의사결정트리는 가지를 칠 때 이 값을 사용하여 가지를 친다. 이 때 어떤 데이터를 두 집합으로 나누었을 때 두 집합의 정보이득이 크도록, 엔트로피는 작아지도록 분할을 한다.

**Comment by import-max** [comment]
- 엔트로피는 데이터의 혼잡도이다. 예를 들어 데이터가 서로 다른 클래스에 속하면 높고, 같은 클래스에 속하면 낮다.
- Information gain은 데이터가 특정 클래스에 속할 확률이 커짐에 따라 정보를 잘 얻게되고, 그로 인해 감소하는 엔트로피의 양을 의미한다. 기존 엔트로피에서 현재 엔트로피를 빼서 계산할 수 있다.

**Comment by kimyuuuuuu** [comment]
## 엔트로피(Entropy)
- 주어진 데이터의 혼잡도. 데이터가 어떤 클래스에 속할 확률에 대한 기댓값.
- 확률분포가 가지는 정보의 확신도 혹은 정보량을 수치로 표현한 것
- 주어진 데이터 집합에서 서로 다른 종류의 레코드들이 섞여 있으면 엔트로피가 높고, 같은 종류의 레코드들이 섞여 있으면 엔트로피가 낮다.

- 엔트로피는 **0에서 1까지의 값**을 갖는다.
⇒ 즉 엔트로피가 0일때는 같은 데이터 결과만 존재하는 것이고 엔트로피가 1일때는 전혀 분리가 안되어 있다는 것이다.

- 데이터가 서로 다른 클래스에 속하면 높고, 같은 클래스에 속하면 낮다
    
    ⇒ 특정 클래스에 속할 확률이 높고 나머지 클래스에 속할 확률이 낮다면 엔트로피가 
         낮고, 모든 각각의 클래스에 속할 확률이 비슷하다면 엔트로피는 높다.

## 정보이득

- 데이터가 어떤 클래스에 속할 확률이 커짐에 따라 정보를 잘 얻게되는 것.
  = **감소되는 엔트로피 양.**
    
- 수식으로는 기존 시스템의 엔트로피에서 현재 엔트로피를 뺀 값으로 표현된다.
- *의사결정트리*는 가지를 칠 때 이 값을 사용하여 가지를 친다. 
   이 때 어떤 데이터를 두 집합으로 나누었을 때 **두 집합의 정보이득이 크도록, 엔트로피는 작아지도록 분할**을 한다.

**Comment by miinkang** [comment]
- 엔트로피는 출력값을 나타나기 위해 필요한 평균 비트의 수를 뜻하며 확률분포에 대한 기대값입니다. 분류 모델을 예로 들면 데이터가 어떤 클래스에 속할 확률에 대한 기댓값이라고 설명할 수 있습니다. 데이터의 불순도가 높은 상태일 수록 엔트로피의 수치가 커치며 불순도가 낮은 상태일 수록 엔트로피는 0에 가깝습니다. 

    1. 데이터의 불순도 : 여러 클래스가 섞여 있는 정도
    2. 순도 100% = 클래스 1개 
- information gain은 의사결정 트리에서 분할 전 엔트로피 - 분할 후 엔트로피 식을 이용해 구합니다. information gain이 크면 불순도가 줄어든다는 것을 의미합니다. Information gain을 최대화하는 변수로 분할해나가는 것이 의사결정 트리의 목표입니다.
