### ISSUE TITLE
Bellman-Ford란?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#100]

**Comment by kimyuuuuuu** [comment]
- 다익스트라 알고리즘은 간선이 음수인 경우 음수 사이클에 빠질 수 있기 때문에 사용할 수 없다. 벨만 포드 알고리즘을 사용하면 음수 사이클을 찾을 수 있다.
- **모든 엣지**를 거치면서 최단거리를 찾는 것
1. 출발 노드를 설정한다.
2. 최단 거리 테이블을 출발 노드는 0 나머지는 INF 로 초기화한다.
3. 모든 E를 확인하며 테이블 값보다 (현재 노드 최단거리 + 현재노드에서 해당 노드로 가는 거리)가 작다면 테이블을 갱신하는 것을 $V-1$번 반복한다.

**Comment by miinkang** [comment]
- 그래프의 두 노드간의 최단 거리를 구할 떄 이용
- 음의 가중치도 계산할 수 있는 방법
- 음의 가중치를 계산할 수 없는 다익스트라보다는 시간복잡도가 높다.
- 전제 조건
    - 최대 v-1개의 간선만 이용할 수 있다.
    - 음의 가중치로 인해 무한하게 최단거리를 업데이트를 하는 경우는 탈출해야 함
- 공간복잡도 : O(|V|)

**Comment by import-max** [comment]
- 모든 엣지를 거치며 최단거리를 찾는 것으로, 모든 노드에 대해 진행한다.

### 프로세스

출발 노드 설정 → 최단 거리 테이블을 초기화 ( 출발노드 : 0, 나머지 : INF) → 엣지개수 확인하여 테이블 값보다 작다면 갱신하는 것을 노드 수만큼 반복한다.

- 모든 간선을 모든 노드 개수만큼 반복하는 점에서 다익스트라 알고리즘보다 비효율적이다. 하지만 음수 사이클을 처리할 수 있는 점이 특징이다.
