### ISSUE TITLE
XGBoost을 아시나요? 왜 이 모델이 캐글에서 유명할까요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#101]

**Comment by jarammm** [comment]
- Kaggle 경연대회에서 상위를 차지한 많은 캐글러들이 XGBoost를 이용하면서 널리 알려졌다.
- gbm에 기반하지만 이름에서도 알 수 있듯이 속도가 개선되었고, 과적합 규제 기능이 부재했던 gbm의 문제를 해결했다.
- 장점
    - **분류 및 회귀**에서 높은 성능을 자랑한다.
    - **병렬처리**를 사용하여, gbm 대비 **수행시간이 크게 단축**
    - **Regularization, Early Stopping** 기능을 통해 **오버피팅을 방지**
    - **Tree Pruning(가지치기)** 제공한다. (max_depth까지만 split하고 pruning을 하고, 거꾸로 올라가면서 positive gain이 없는 노드를 삭제)
    - 자체적으로 **결측치 처리**
    - 매 iteration마다 **교차검증**을 수행

**Comment by kimyuuuuuu** [comment]
- Extreme Gradient Boosting
- 트리 기반의 앙상블 학습에서 가장 각광받고 있는 알고리즘 중 하나
- GBM에 기반하고 있지만, GBM의 단점인 느린 수행시간 및 과적합 규제(Regularization) 부재 등의 문제를 해결해서 각광받고 있다.
- 
- Boosting 기법을 이용하여 구현한 알고리즘은 Gradient Boost 가 대표적인데
- 이 알고리즘을 병렬 학습이 지원되도록 구현한 라이브러리가 XGBoost 이다.
- Regression, Classification 문제를 모두 지원하며, 성능과 자원 효율이 좋아서, 인기 있게 사용되는 알고리즘이다.

- 장점
    - 분류와 회귀영역에서 **뛰어난 예측 성능**을 발휘한다.
    - XGBoost는 병렬처리를 사용하여, GBM 대비 **빠른 수행시간**을 보인다.
    - **Regularization, Early Stopping** 기능을 통해 오버피팅을 방지할 수 있다.
    - Tree Pruning(가지치기) 제공한다. 미리 정해둔 max_depth까지만 split하고 pruning을 하고, 거꾸로 올라가면서 positive gain이 없는 노드를 삭제한다.
    - 자체적으로 결측치를 처리해준다.
    - 매 iteration마다 교차검증을 수행한다.

**Comment by import-max** [comment]
- Gradient Boosting Algorithm (GBM)을 기반으로 한 예측 모형이며, 부스팅 계열에 속하는 알고리즘이다. GBM 의 단점을 다수 해결하였다.
- 뛰어난 예측 성능을 발휘하며, 병렬처리로 인해 GBM 대비 빠른 수행시간이 장점이다.
- 자체적으로 결측치를 처리하며 iteration마다 교차검증을 수행한다.
- Regularization, Early stopping 기능으로 오버피팅 방지를 할 수가 있고  Tree Pruning을 제공한다.
