### ISSUE TITLE
What is map function in Python?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#102]

**Comment by kimyuuuuuu** [comment]
- **map(function, iterable)**
- **첫 번째 매개변수로는 함수**가 오고 **두 번째 매개변수로는 반복 가능한 자료형(리스트, 튜플 등)**이 옵니다.
- 함수의 동작은 **두 번째 인자로 들어온 반복 가능한 자료형 (리스트나 튜플)을 첫 번째 인자로 들어온 함수에 하나씩 집어넣어서 함수를 수행하는** 함수입니다.

**Comment by import-max** [comment]
- iterable한 객체의 원소의 동일한 함수를 적용하는 메소드이다.
- 첫 인자 : 적용할 함수, 두번째 인자 : iterable한 객체를 넣으면 각 함수가 적용된 묶음이 나온다.

ex)

```jsx
int_arr = list(map(int, input().split()))
```
