### ISSUE TITLE
모수가 매우 적은 (수십개 이하) 케이스의 경우 어떤 방식으로 예측 모델을 수립할 수 있을까요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#103]

**Comment by kimyuuuuuu** [comment]
- 표본이 매우 작은 경우 표본평균의 분포가 정규분포를 따른다고 가정할 수 없으므로 **비모수적 방법**
을 채택하여 예측 모델을 수립할 수 있다. 하지만 중심극한정리에 의해 표본의 크기가 30보다 클 경우 표본평균이 정규분포를 따른다고 가정할 수 있으므로, 이 경우에는 모수적 방법을 사용한다.

- 비모수적 방법
    - 정규성 검정에서 정규분포를 따르지 않는다고 증명되거나 군 다 ㅇ10명 미만의 소규모 실험에서는 정규분포임을 가정할 수 없으므로 모수적 방법을 사용할 수 없다.
    - 자료를 크기 순으로 배열하여 순위를 매긴 다음 순위의 합을 통해 차이를 비교하는 순위합검정을 적용할 수 있다.

**Comment by jarammm** [comment]
- 대개 정규분포를 가정하고 통계나 예측이 이뤄지는데, 모집단의 크기 자체가 매우 작은 경우, 정규분포를 가정하기 어렵기 때문에 이런 경우에는 비모수적 방법론을 활용해 예측 모델을 수립
- **순위합검정** : 대표적인 비모수적 방법론. 자료를 크기 순으로 배열하여 순위를 매긴 다음 순위의 합을 통해 차이를 비교
    - **숫자로는 표현되지만 수량화 할 수 없는 순위척도**의 경우에도 연속형 자료가 아니더라도 순위합을 이용하는 비모수적 방법을 적용하는 것이 가능하다.
- 데이터 증강(시계열 데이터  X)
    - resampling
    - 이미지나 텍스트 데이터의 경우, 예측에 영향을 주지 않는 선에서 원본 변형
    - [[시계열 데이터 증강방법 참고](https://yonsodev.tistory.com/34)](https://yonsodev.tistory.com/34)

**Comment by import-max** [comment]
- 분포가 정규분포를 따른다고 가정할 수 없을 경우에는 비모수적 방법을 채택할 수 있다. 만약 표본의 크기가 30보다 클 경우는 정규분포를 따른다고 할 수 있으므로, 모수적 방법을 사용한다.
- 비모수적방법 중 하나는 자료를 크기 순으로 배열하여 순위를 매긴 다음, 순위의 합을 통해 차이를 비교하는 순위합검정의 방법이 있다.
