### ISSUE TITLE
ReLU로 어떻게 곡선 함수를 근사하나?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#106]

**Comment by jarammm** [comment]
ReLU를 여러 개 결합하면, 특정 지점에서 특정 각도만큼 선형 함수를 구부릴 수 있다. 이 성질을 이용하여 곡선 함수 뿐만 아니라 모든 함수에 근사를 할 수 있게 된다.

**Comment by import-max** [comment]
ReLU를 여러개 결합하면, 특정 지점에서 특정 각도만큼 선형 함수를 구부릴 수 있다. bias와 기울기의 결합을 통해 거의 모든 함수에 근사할 수 있다.
