### ISSUE TITLE
파이썬에서 self란 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#107]

**Comment by jarammm** [comment]
- self는 인스턴스 자기 자신을 의미한다.
- 객체의 속성들은 `self.속성` 의 형태로 쓸 수 있다. `self`를 사용함으로써 클래스내에 정의한 멤버에 접근할 수 있다.

**Comment by import-max** [comment]
인스턴스 메서드의 첫번째 인자로, 호출될 때 self 에 인스턴스를 넣고 이를 참조하여 인스턴스 메서드를 실행할 수 있다.
