### ISSUE TITLE
Floyd-Warshall

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#108]
플로이드-워샬 알고리즘

**Comment by jarammm** [comment]
- 정규화의 필요성 : 데이터의 각 피쳐간 분포에 차이가 크다면, 가 피쳐들의 절대적인 데이터 크기가 가중치에 영향을 주게 된다. 이를 방지하기 위해 정규화 시행이 필요하다.
- 정규화의 방법
    - **Min-Max Normalization** (최소-최대 정규화)
        - 방법 : 모든 feature에 대해 각각의 최소값 0, 최대값 1로, 그리고 다른 값들은 0과 1 사이의 값으로 변환하는 것이다.
        - 장점 : 모든 feature들의 스케일이 동일해 비교가 용이하다.
        - 단점 : 이상치에 너무 많은 영향을 받는다.
    - **Z-Score Normalization** (Z-점수 정규화)
        - 방법 : 각 피쳐 값들을 Z-점수로 바꿔준다.
        - 장점 : 이상치를 잘 처리한다.
        - 단점 : 모든 피쳐들이 정확히 동일한 척도로 정규화 된 데이터를 생성하지는 않는다.

**Comment by import-max** [comment]
- 모든 지점에서 모든 지점까지의 최단 경로를 구하는 알고리즘으로, 특정 노드를 거쳐 가는 값과 최단 경로 값 중 어떤 것이 짧은지 비교하는 것이 핵심이다. 시간 복잡도는 $O(V^3)$ ($V:$노드 개수) 이다.
- 계속해서 테이블을 갱신하는 방법이다.
