### ISSUE TITLE
TCP와 UDP의 차이를 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#109]

**Comment by kimyuuuuuu** [comment]
- UDP
    - 비연결 전송 프로토콜. 핸드쉐이킹 없음. 데이터 그램 사용
    - 비신뢰적. 메세지 손실, 중복 가능성 존재
    - 단순함 → 흐름제어, 혼잡제어 불가능
    - 멀티캐스트 지원
    - 메시지 지향적 프로토콜
    - 인터넷 전화, 스트리밍 등

- TCP
    - 연결지향적 → 3-way-handshaking
    - 신뢰적 → 순서보장, 재전송 기능
    - 스트림 지향 처리
    - 흐름제어 및 혼잡제어 기능 존재

**Comment by jarammm** [comment]
- 네트워크의 계층들 중 전송 계층
    - 송신자와 수신자를 연결하는 통신서비스를 제공하는 계층
    - 프로토콜을 사용해 데이터를 보내는데 이때 사용하는 프로토콜이 TCP, UDP
- TCP와 UDP의 차이
    - TCP : 신뢰성, 연결지향적
    - UDP : 비신뢰성, 비연결성, 실시간
- TCP(Transmission Control Protocol) : 연결 지향형 프로토콜(Connection Oriented Protocol)
    - 데이터의 확실한 전송을 보장
        - 패킷 송신 시 데이터를 흘려버리지 않게 데이터 흐름 제어(Flow Control)
        - 전송 중 에러가 발생할 경우 자동으로 재전송하는 에러 제어(Error Control)
    - 방식이 완전하지는 않아 해킹의 위험이 있음
        - 신뢰성 있는 연결을 위한 기능이 존재
            - 패킷의 순서가 올바른지 확인
            - 중간에 손실된 패킷은 없는지 확인
            - 손실된 패킷의 재전송 요구
- UDP(User Datagram Protocol) : TCP와는 달리 데이터의 신뢰성 있는 전송을 보장하지는 않음.
    - 신뢰성이 매우 높은 회선을 사용하거나, 데이터의 확실한 전송을 요구하지 않는 통신을 하거나, 한 번에 많은 상대에게 메시지를 전송하고자 하는 경우 → 전송 경로 확립을 위한 번잡함을 생략하고 시간을 절약할 수 있어 매우 효과적

**Comment by miinkang** [comment]
- 데이터를 보내기 위해 사용하는 프로토콜

TCP(Transmission Control Protocol)

- 데이터를 메세지의 형태로 보내기 위해 ip와 함께 사용하는 프로토콜
- 연결 지향 방식
- 높은 신뢰성
- UDP보다 속도가 느림
- 데이터의 흐름제어, 혼잡 제어와 같은 기능을 함

UDP(User Datagram Protocol)

- 데이터를 데이터그램 단위로 처리하는 프로토콜
    - 데이터그램 : 독립적인 관계를 지니는 패킷
- 비연결형 프로토콜
- 각각의 패킷이 다른 경로로 전송되며, 독립적인 관계를 지니고 처리함
- 신호절차가 없음
- 신뢰성이 낮음
- 속도가 빠름
- 신뢰성보다 연속성이 중요한 실시간 서비스 등에 자주 사용됨

**Comment by import-max** [comment]
- tcp는 **두 개의 호스트를 연결하고 데이터 스트림을 교환하게 해주는 중요한 네트워크 프로토콜**
이다. TCP는 데이터와 패킷이 보내진 순서대로 전달하는 것을 보장해준다.
- udp는 User Datagram Protocol의 축약어로 **컴퓨터가 다른 컴퓨터와 데이터 통신을 하기 위한 규약(프로토콜)의 일종**
이다. UDP는 세계 통신표준으로 개발된 OSI 모형에서 4번째 계층인 전송 계층(Transport Layer)에서 사용하는 규약이다.
- tcp 소켓에서는 통신이 이루어지기 전에 **connect, listen, accept**하는 과정이 있는데, udp에서는 없음
- tcp 소켓은 데이터 소실 x, 순서 보장
- udp 소켓은 데이터가 소실될 수 있고, 순서가 지켜지지 않을 수 있다.

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/52f82eaa-3258-4802-abe6-fb57cf964c29/Untitled.png)
