### ISSUE TITLE
회귀 / 분류시 알맞은 metric은 무엇일까?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#11]
[3차시] 2022년 8월 30일 화요일

**Comment by import-max** [comment]
- 회귀에서는 $R^2$ (r 스퀘어) 결정계수를 많이 사용하는데, 전체 변동 대비 회귀에 의한 변동을 계산한다. 독립변수의 개수가 많아질수록 결정계수가 1에 가까워짐으로 결정계수만으로는 신뢰도가 떨어진다.
- 분류 시에는 여러 지표가 사용되는데, 이진 분류에서는 Log Loss 나 Binary Crossentropy 를, 클래스가 3개 이상일 때는 Categorical Crossentropy를 사용한다.

**Comment by kimyuuuuuu** [comment]
## 질문
📌 MSE와 MAE의 차이

- MSE는 손실함수로써 쓰이고 / MAE는 회귀지표로써 사용된다.
- **평균 제곱 오차(MSE)**는 회귀에서 자주 사용되는 **손실 함수**입니다. 정확도 개념은 회귀에 적용되지 않습니다. 일반적인 **회귀 지표**는 **평균 절대 오차(MAE)**입니다.

**Comment by jarammm** [comment]
질문) MSE에 비해 MAE가 가지는 특징은? 특이치에 덜 민감하다

- 분류 : 정확도, 정밀도, 재현율, f1-score, ROC-AUC, Log Loss와 Binary Crossentropy(이진 분류), Categorical Crossentropy(다중 분류)
    - 정확도 : 전체 데이터 중 적중률
    - 정밀도 : positive로 예측한 데이터 중 실제 positive한 비율
    - 재현율 : 실제 positive 데이터 중 positive라고 잘 예측한 비율
    - f1-score : 정밀도와 재현율의 조화평균. 정밀도와 재현율을 모두 고려한 지표
    - ROC-AUC : ROC커브(수신자 판단 곡선)와 이에 기반한 AUC스코어는 이진 분류의 예측 성능 측정에서 중요하게 사용되는 지표.
        - ROC curve
            - FPR(False Positive Rate)이 변할 때 TPR(True Positive Rate, 재현율)이 어떻게 변하는지를 나타내는 곡선
            - FPR을 x축으로, TPR을 y축으로 잡음
            - 참고) 민감도(True Positive Rate) ↔ 특이성(True Negative Rate) : TNR = 1 - FPR
        - AUC 값 : 일반적으로 ROC 곡선 자체는 FPR과 TPR의 변화값을 관찰하는 데 이용하고, 분류의 성능 지표로 사용되는 것은 ROC곡선 면접에 기반한 AUC 값으로 결정
            - AUC(Area Under Curve) : 말그대로 ROC곡선 밑의 면적을 구한 것, 일반적으로 1에 가까울수록 좋은 수치
- 회귀 : MSE, MAE, RMSE, RMSLE, R-Squared
    - MSE(평균제곱오차) : 예측값과 정답값 사이의 차이의 제곱의 평균. 제곱을 하기 때문에 이상치에 민감하다.
    - MAE(평균절대오차) : 예측값과 정답값 사이의 차이의 절대값의 평균. MSE보다는 특이치에 덜 민감하다.
    - RMSE : MSE에 루트를 씌운 값. 오류 지표를 실제 값과 유사한 단위로 다시 변환하기에 해석이 다소 용이해짐.
    - RMSLE : RMSE와 비슷하지만 다른 점은 예측값과 정답값 간의 오차 제곱이 아니라, 예측값과 정답값 각가에 로그를 씌운 후 동일한 계산을 한다는 점이다.
        - 이상치에 민감하지 않아 Robust하다.
        - RMSE는 절대적인 오차를 측정하는 데 반해, RMSLE는 상대적인 크기를 측정한다.
    - R-Squared(결정계수) : 분산기반 예측 성능 평가
        - 다른 MAE, MSE 등과 같은 지표들는 데이터의 scale에 따라 값이 다르지만 R2은 **상대적인 성능**이 어느정도인지 직관적으로 판단할 수 있다.
        - 수정된 결정계수 : 독립변수의 개수가 많아질수록 결정계수가 1에 가까워진다. 회귀모형이 높은 결정계수를 갖는다면 실제로 모형이 설명력이 높은 것인지 단순히 독립변수의 개수가 많은 것인지 알기 어려워 결정계수를 신뢰할 수 없게 되는 문제가 발생한다. 수정된 결정계수는 결정계수의 문제를 해결하기 위해 표본의 크기(n)와 독립변수의 수(p)를 고려하여 수정된 결정계수를 계산한다.
- 1에 가까울수록 좋은 지표 : R-Squared / 0에 가까울수록 좋은 지표 : MSE, MAE, RMSE, RMSLE

**Comment by miinkang** [comment]
- 회귀 : 회귀 문제는 실제 값과 모델의 예측값의 차이에 기반을 둔 metric을 사용합니다. 대표적으로 평균 제곱 오차(MSE), 평균 절대값 오차(MAE, 오차의 절대값의 평균)가 있습니다. MSE는 오차에 제곱을 해서 이상치를 잡아내는 데 효과적입니다. (틀린 것을 더 많이 틀렸다고 알려줌) MAE는 변동치가 큰 지표와 낮은 지표를 같이 예측할 때 효과적입니다. 
    1. 하지만 둘 다 평균을 이용하기 때문에 데이터의 크기에 의존한다는 단점이 있음 1-(RSS(오차제곱합)/전체 분산) R2를 이용하면 그 단점을 극복할 수 있습니다. 

- 분류 : 정밀도(precision), 재현율(recall), 정확도(accuracy), f-1 score등이 있습니다.
    1. 정밀도 : 모델이 true라고 분류한 것중 실제 true의 비율
    2. 재현율 : 실제 true 중 모델이 true라고 예측한 비율
    3. 정확도 : 모델이 예측한 것 중 정답의 비율
    4. f-1 score : 정밀도와 재현율을 조화평균한 값
