### ISSUE TITLE
스케줄러가 무엇이고, 단기/중기/장기로 나누는 기준에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#110]

**Comment by kimyuuuuuu** [comment]
- 시스템 내의 여러 프로세스 중에, 자원을 할당하는 프로세스를 스케줄러라고 한다.
- 스케줄러의 목적 : 시스템 성능 향상. (자원이 한정되어 있기 때문에.)
    - 응답시간: 작업 요청으로부터 응답을 받을 때까지의 시간
    - 작업 처리량: 단위 시간 동안 완료된 작업의 수
    - 자원 활용도 : 주어진 시간동안 자원이 활용된 시간
- 발생 빈도와 할당 자원에 따라 장기/중기/단기 스케줄러
    - 장기 스케줄러
        - Job Scheduling(Job → created)
        - 시스템 내에 프로세스 수를 조절
        - CPU든 I/O든 모두 써서 효율성을 높이기 위해서 I/O bounded와 compute-bounded 프로세스들을 잘 섞어서 선택해야 한다.
    - 중기 스케줄러
        - 메모리 할당을 결정하는 Memory Allocation(suspended ready → ready)
    - 단기 스케줄러
        - 프로세서를 할당 받을 프로세스를 결정하는 Process Scheduling(ready → running)

**Comment by jarammm** [comment]
- OS에서 자원을 할당하는 것이 스케줄러의 일
- 스케줄러의 목적 : 시스템 성능 향상.
    - 응답시간: 작업 요청으로부터 응답을 받을 때까지의 시간
    - 작업 처리량: 단위 시간 동안 완료된 작업의 수
    - 자원 활용도 : 주어진 시간동안 자원이 활용된 시간
- 스케줄러는 발생하는 `빈도`와 할당하는 `자원`에 따라 **장기/중기/단기 스케줄러** 로 나뉨
    - 장기 스케줄러
        - 시스템에 제출할 작업을 결정하는 잡스케줄링에 사용
        - 시스템 내에 프로세스 수를 조절
    - 중기 스케줄러
        - 메모리 할당
    - 단기 스케줄러
        - 프로세서를 할당 받을 프로세스를 결정함 → 가장 빈번하게 발생하므로 매우 빨라야 함

**Comment by miinkang** [comment]
**스케줄러**

- 어떤 프로세스에게 자원을 할당할지를 결정하는 운영체제 커널의 모듈을 지칭하는 것
- queue를 사용한다.
    - job queue : 현재 시스템 내에 있는 모든 프로세스의 집합
    - ready queue : 현재 메모리 내에 있으면서 CPU를 잡아서 실행되기를 기다리는 프로세스의 집합
    - device queue :  device I/O작업을 대기하고 있는 프로세스의 집합

**장기 스케줄러**

- Job scheduler 라고도 불림
- 디스크와 메모리 사이의 스케줄링 담당
- 어떤 프로세스에 메모리를 할당해 ready queue로 보낼지 결정

**중기 스케줄러**

- Swapper라고도 불림
- 여유 공간을 마련하기 위해 프로세스를 통째로 메모리에서 디스크로 쫓아내는 역할
- swap in, swap out을 한다.

**단기 스케줄러**

- 메모리와 CPU사이의 스케줄링 담당
- 어떤 프로세스를 running상태로 전환할지 결정

**선택하는 기준**

- 스케줄링 정잭에는 FIFO, SJF, STCF, RR 등이 있다.
- 위의 정책들을 몇가지 평가지표를 이용해 비교할 수 있다.
    1. 응답 시간 (Response Time = FirstRun Time - Arrival Time)
    2. 형평성 : 여러 개의 프로세스들의 완료시간이 얼마나 비슷한지에 대한 형평성
    3. Throughput : 단위 시간당 완료된 프로세스 수
    4. 마감 시간 : Turnaround Time < Deadline Time 해야 함

**Comment by import-max** [comment]
- 시스템 내에 존재하는 여러 개의 프로세스 중 자원을 할당하는 역할을 하는 것이 스케줄러이다. 일반적으로 시스템 성능 향상을 위해 사용하며, 응답시간/작업처리량/자원활용도 등을 지표로 고려하여 선택한다.
- 장기 스케줄러 : 시스템에 제출할 작업을 결정하는 Job Scheduling에서 사용하며, 시스템 내에 프로세스 수를 조절한다. 효율성을 높이기 위해서 I/O 와 compute-bounded 프로세스 모두를 잘 섞어서 선택해야 한다.
- 중기 스케줄러 : 메모리 할당을 결정하는 Memory Allocation에서 사용한다.
- 단기 스케줄러 : 프로세서를 할당 받을 프로세스를 결정하는 Process Scheduling에서 사용하며, 가장 빈번하게 발생하므로 매우 빨라야 한다.
