### ISSUE TITLE
Circular linked list란?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#111]

**Comment by kimyuuuuuu** [comment]
- linked list는 서로 떨어져 있는 데이터를 메모리 주소를 참조함으로써 이어진 것처럼 사용할 수 있다. linked list는 구조체가 이어진 형태로 존재하며, 이 구조체를 `노드`라고 부른다. 노드는 값을 담고 있는 `데이터 필드`와 다음 구조체를 가리키는 `링크 필드(포인터)`로 구성된다. 정확히는, 포인터가 다음 구조체의 주소를 담고 있다.
- tail이 다시 head를 가리키는 구조를 가지고 있다. 따라서, tail 노드의 next에는 NULL이 들어가는 것 대신, head의 주소가 들어간다.

**Comment by miinkang** [comment]
- 기존 단순 연결 리스트의 구조에서 마지막 노드가 첫 번째 노드를 가치켜서 연결 형태가 원이 되는 구조의 리스트를 말한다.
- 다음 노드의 주소를 저장하는 next 변수가 있음
- 맨 처음을 가리키는 head 변수가 있음
- tail 변수를 가질 수도 있음

삽임

- 머리와 꼬리의 구분이 없어서 꼬리 혹은 머리에 간단히 추가할 수 있음
- head에 새로운 변수를 저장하고, 새로운 head를 가리키도록 tail을 재 설정함

**Comment by import-max** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/92b40661-2c91-4b25-8c1a-a69fda476eca/Untitled.png)

- tail이 다시 head를 가리키는 구조를 가지고 있다. tail 의 다음 노드에는 NULL이 아닌 head의 주소가 들어간다.
