### ISSUE TITLE
가우시안 정규 분포에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#112]

**Comment by jarammm** [comment]
- 용어 : 가우시안 분포 = 정규 분포
- 확률밀도함수(구간으로 확률 계산 요함)
- 가우시안 분포가 중요한 이유 : 정규분포의 성질을 이용해서 통계 현상을 연구하기 위해 만들어진 분포들이 많기 때문에, 정규분포를 가정하지 않으면 여타 분포나 통계적 공식들을 활용하기 어렵다
- $N(\mu, \sigma^2)$
    - $\mu$ 값인 $x$축의 포인트를 중심으로 종모양 그래프
- 표준화(평균 0, 표준편차 1)하여 표준정규분포를 만들어 활용 가능
- 어느 정도 충분히 표본을 키웠는데도 불구하고 각 결과값이 나온 횟수의 합의 분포가 정규를 따르지 않는다면 서로 독립이 아닐 수 있다. 이때에는 다른 분포를 찾아보거나, 비모수 통계를 이용하는 것이 바람직하다.

**Comment by miinkang** [comment]
추가 질문
- 정규분포와 표준 정규분포의 차이점

**Comment by kimyuuuuuu** [comment]
- **정규 분포(normal distribution)**
- 자연 현상에서 나타나는 숫자를 확률 모형으로 나타낼 때 사용한다. 즉, 수집된 자료의 분포를 근사하는 데에 자주 사용된다.
- 확률 밀도 함수로 나타냈을 때, 엎어진 종모양 (bell shape)을 가진다.

- 정규분포는 평균과 표준편차가 주어져 있을 때 엔트로피를 최대화 하는 분포이다.
- 정규분포곡선은 좌우 대칭이며 하나의 꼭지를 가진다.
- 정규분포는 중앙치에 사례 수가 모여있고, 양극단으로 갈수록 X축에 무한히 접근하지만 X 축에 닿지는 않는다.

**Comment by import-max** [comment]
- 가우시안 정규분포는 일반 정규분포(Normal Distribution)의 다른 이름이다.
- 정규분포는 2개의 매개변수 (평균,표준편차)에 따라 모양이 결정되고, 이때의 분포를
로 표기한다. 특히, 평균이 0이고 표준편차가 1인 정규분포를 표준 정규분포라고 한다.
