### ISSUE TITLE
LSA, LDA, SVD 등의 약자들이 어떤 뜻이고 서로 어떤 관계를 가지는지 설명할 수 있나요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#113]

**Comment by miinkang** [comment]
**LSA**

- 잠재 의미 분석 (Latent Semantic Analaysis)
- 토픽 모델링 분야에 아이디어를 제공한 알고리즘
- 단어의 빈도 수만을 이용하는 것이 아닌, 단어의 의미, 토픽을 고려하는 알고리즘
- SVD를 사용해 차원을 축소하고, 단어의 잠재적 의미를 끌어냄
    - **SVD**(Singular Value Decomposition), 특이값 분해
        - 3개의 행렬의 곱으로 분해하는 것 (차원축소 기법)
        - 불필요한 토픽은 제거되고 중요 토픽, 단어만 남게 됨
        - 행과 열이 달라도 적용할 수 있음
- 포함된 단어가 가우시안 분포를 따라야 LSA를 적용할 수 있음
- 데이터가 큰 경우, 차원축소의 효과가 커짐
- 단점 : 새로운 데이터를 추가하기 위해서는 처음부터 다시 계산해햐해서 업데이트가 어려움

**LDA**

- 잠재 디리클레 할당 (Latent Dirichlet Allocation)
- LSA의 단점을 보완한 토픽 모델링에 보다 적합한 알고리즘
    - 어떻게 보완?
    - 업데이트?
- 단어 집합에서 토픽 k개를 뽑는다.
- k개의 토픽에 해당하는 단어들을 뽑는다.
- k개의 토픽이 존재할 확률, 해당 단어가 어떤 토픽에 존재할 확률을 결합확률로 추청하는 기법

**Comment by jarammm** [comment]
- SA : 잠재의미분석(Latent Semantic Analysis)
    - DTM(Document-Term Matrix)이나 TF-IDF(Term Frequency-Inverse Document Frequency) 행렬에 Truncated SVD를 적용하여 차원을 축소시키고, 단어들의 잠재적인 의미를 이끌어낸다. Truncated SVD는 SVD와 똑같으나 상위 n개의 특이값만 사용하는 축소 방법이다. 이 방법을 쓸 경우 원 행렬로 복원할 수 없다.
- LDA : 잠재디리클레할당(Latent Dirichlet Allocation)
    - 토픽 모델링 기법 중 하나이며 디리클레 분포에 기반한다.
    - SVD (행렬분해)를 자연어처리 토픽 모델링에 적용한 것이다.
    - LDA(Linear Discriminant Analysis)는 PCA에서 확장된 차원 축소 기법
- SVD : 특이값분해(Singular Value Decomposition)
    - PCA와 유사한 행렬 분해 기법을 사용하나 정방 행렬(square matrix)를 분해하는 PCA와 달리 행과 열의 크기가 다른 행렬에도 적용할 수 있다.

**Comment by import-max** [comment]
- SVD는 Singular Value Decomposition의 약자로, 행렬 분해 기법을 사용하여 차원을 춗소하는 방법이다. PCA는 행과 열의 길이가 같을 때만 사용할 수 있지만 SVD는 행과 열의 크기가 달라도 적용할 수 있다는 장점이 있다.
- LSA는 Latent Semantic Analysis의 약자로, 직역하면 잠재 의미 분석이고 주로 topic modeling에 사용된다. DTM이나 tf-idf 행렬에 Truncated SVD(특이값 분해)를 적용하여 차원을 축소하고 단어들의 잠재 의미를 추출할 수 있다. 이 방법을 사용하면 원래 행렬로 복원할 수 없기 때문에 주의해야 한다.
- LDA는 Latent Dirichlet Allocation 혹은 Linear Discriminant Analysis의 약자이다. 전자는 토픽 모델링에 사용되는 기법으로, tf와 idf를 결합확률로 추정하여 토픽을 추정하는 기법이다. 후자는 차원 축소 기법으로, 분류가 쉽도록 클래스 간 분산을 최대화하고 클래스 내부의 분산은 최소화하는 방식을 말한다.
