### ISSUE TITLE
샘플링(Sampling)과 리샘플링(Resampling)이 무엇이고 리샘플링의 장점을 말씀해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#115]

**Comment by miinkang** [comment]
**샘플링(Sampling)**

- 모집단 전체를 조사할 수 없기에 표본을 추출하는 것
- 표본을 추출해(샘플링) 모집단의 분포를 추정할 수 있다.
- 추출한 표본 자체의 노이즈로 인해 모집단의 분포를 추정하기 어려울 수 있다.

**리샘플링(Resampling)**

- 샘플만으로는 모집단의 분포를 확인하기 어려울 경우 사용한다.
    - 하지만 매번 샘플을 다르게 진행하기에는 비용적 손실이 있다.
- 보유한 샘플에서 다시 부분집합을 추출해 통계량의 변동성을 확인한다.
- k-fold 교차검증, 부트스트래핑 등의 방법으로 같은 샘플을 여러 번 사용해 성능을 측정할 수 있다.
- 정규성 가정이 필요하지 않다.
    - 왜..? 이유를 못찾음

**Comment by jarammm** [comment]
- 샘플링
    - 샘플링이란 표본추출을 의미하는 것으로, 모집단 전체에 대한 추정치(estimate)을 얻기 위해 모집단에서 임의의 sample을 뽑아내는 것이다.
    - 모집단 전체에 대한 조사는 사실상 불가능하기 때문에 sample을 이용하여 모집단에 대한 추론(inference)을 하게 되는 것이다.
- 리샘플링
    - 샘플은 모집단 그 자체가 아니므로 모집단의 모든 특성을 반영할 수 없다. 이런 샘플을 가지고 통계를 낸다면 그 통계는 샘플에 오버피팅되었을 가능성이 크다. 이를 보완하기 위해 리샘플링을 실시한다.
    - '**내가 가지고 있는 샘플에서 다시 샘플 부분집합을 뽑아서 통계량의 변동성(variability of statistics)을 확인하는 것**'이다.
    - 장점
        - 리샘플링은 표본을 활용하는 방법이기 때문에 **모집단의 분포에 어떤 가정도 필요 없이 표본만으로 추론이 가능**하다는 장점이 있다.

**Comment by import-max** [comment]
- 샘플링이란 모집단에서 임의의 샘플을 뽑아 표본을 추출하는 것이다. 전체를 조사할 수 없기 때문에 랜덤하게 뽑아서 inference하는 것이다. 하지만 표본은 표본일 뿐, 모집단 전체를 대표한다고 할 수 없고 noise가 존재할 수 밖에 없다.
- 리샘플링이란 모집단의 분포 형태를 알 수 없을 때 사용하는 방법으로, 현재 데이터로 모집단의 분포를 유추하는 것이다. 이미 가지고 있는 샘플에서 다시 부분적으로 샘플을 추출하여 변동성을 확인함으로써 여러 차례 성능을 측정하는 방법이다. 주로 k-fold cross validation, bootstraping 등이 있다. 리샘플링은 표본을 추출하면서 원래 데이터 셋을 복원하기 때문에 이를 통해서 모집단의 분포에 어떤 가정도 필요 없이 표본만으로 추론이 가능하다는 장점이 있다.
