### ISSUE TITLE
How do you write comments in python?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#116]

**Comment by miinkang** [comment]
주석

- 맨 앞에 ‘#’을 붙이면 주석처리가 된다.

```python
#한 줄을 주석처리하는 방법 
```

- 한 줄 이상일 경우 맨 앞과 맨 뒤에 큰따옴표 혹은 작은따옴표를 3개씩 써주면 주석 처리가 가능하다.

```python
"""
한 줄 이상일 경우 이렇게 따옴표로 처리한다.
"""

'''
작은 따옴표도 가능하다.
''' 
```

**Comment by jarammm** [comment]
- 한 줄 - `#주석내용`
- 여러 줄 - `'''주석내용'''`  또는 `"""주석내용"""`
- **따옴표** 사용 시 주의사항 - indentation error가 나지 않도록 일반적인 코드를 작성할 때처럼 indentation을 신경써주어야 함
- 예시
```python
def temp():
"""comment
comment2
comment"""
    a = 10
```

**Comment by import-max** [comment]
- `#`을 사용하여 주석을 달 수 있다.

```python
# 설치
$ git clone www.github.com/github.git
```

- 만약 여러 줄을 주석달고 싶으면, `‘’’`를 통해 할 수 있다.

```python
'''
	for i, j in enumerate(iii,jjj):
		i_list.append(i)
		j_list.append(j)
'''
```
