### ISSUE TITLE
dimension reduction 기법으로 보통 어떤 것들이 있나요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#117]

**Comment by import-max** [comment]
- 크게 Feature Selection, Feature Extraction으로 나눌 수 있다.
- Feature Selection의 경우 불필요한 피쳐를 제거하고 간결한 feature만 남기는 것인데, Decision Tree, Lasso 등이 위의 방법에 해당한다.
- Feature Extraction의 경우 고차원의 피처를 저차원의 feature 공간으로 투영시키며 매핑하는 것이다.  PCA, SVD, LDA 등이 있으며 PCA도 위와 같은 방법으로 해서 분산이 가장 큰 축을 첫번째 주성분, 그 다음 큰 축을 두번째 주성분 이런식으로 데이터를 선형 변환하여 축소하는 방법이다.

**Comment by kimyuuuuuu** [comment]
- dimension reduction : 차원축소
    - 일반적으로 차원이 증가할수록 데이터 간의 거리가 기하급수적으로 증가하기 때문에 희소한 구조를 가지게 되고 모델의 예측 신뢰도가 떨어지게 된다.
- 차원 축소 기법
    - 피처 선택(feature selection)
        - 특정 피처에 종속성이 강한 불필요한 피처는 제거하고 데이터의 특징을 잘 표현하는 주요 피처만 선택하는 것
        - **장점:** 선택한 피처의 해석이 용이하다
        - **단점:** 피처간 상관관계를 고려하기 어렵다
    
    - 피처 추출(feature extraction)
        - 기존 피처를 저차원의 피처로 압축하여, 피처를 함축적으로 잘 설명할 수 있도록 저차원으로 매핑하는 것
        - 단순히 데이터를 압축하는 것이 아닌 차원 축소를 통해 좀 더 데이터를 잘 설명할 수 있는 잠재적인 요소를 추출하는 데에 있습니다
        - **장점:** 피처 간 상관관계를 고려하기 용이하고 피처의 개수를 많이 줄일 수 있다는 점
        - **단점:** 추출된 변수의 해석이 어렵다는 점입니다.
        
        - 피처 추출 알고리즘
            - PCA, SVD, NMF, LDA
            - PCA
                - 가장 대표적인 차원 축소 기법
                - 여러 변수 간에 존재하는 상관관계를 이용해 이를 대표하는 주성분을 추출해 차원을 축소하는 기법

**Comment by jarammm** [comment]
- PCA
    - **변수간 상관관계**를 활용해 주성분을 추출하는 차원 축소 기법
    - 데이터를 **축에 사영했을 때 가장 높은 분산**을 가지는 데이터의 축을 찾아 그 축으로 차원을 축소
        - 이때 그 축을 주성분이라 함.
        - 높은 분산을 가지는 축(주성분)을 찾는 이유는 정보의 손실을 최소화하기 위함
        - 사영했을 때 **분산이 크다는 것은 원래 데이터의 분포를 잘 설명할 수 있다**는 의미. 이는 곧 정보의 손실을 최소화할 수 있다는 것을 뜻함.
    - **고유벡터**가 **PCA의 주성분 벡터**로서 입력 데이터의 **분산이 큰 방향**을 나타냅니다.
    - **입력 데이터의 공분산 행렬을 분해해 얻을 수 있는 고유벡터로 입력 데이터를 선형 변환하는 방식**
    - 가장 큰 분산을 기반으로 첫 번째 축을 생성하고 두 번째 축부터는 직전에 생성된 축에 직각이 되는 벡터를 축으로 삼는다. 이렇게 벡터 축의 개수만큼의 차원으로 원본 데이터를 차원 축소 시킨다.
        - 직각이 되는 벡터를 다음 축으로 설정하는 이유 : 한 축에 데이터들을 사영할 때 같은 점으로 겹쳐서 사영된 데이터들이 있다면 각 데이터들을 모두 설명할 수 없다. 이때 직교하는 축으로 사영시키면 겹쳤던 데이터가 모두 다른 점으로 사영되면서 설명 가능성을 획득하게 된다.
    - **PCA의 주요 한계점**으로 최대의 분산의 각 축이 반드시 클래스 간의 구별을 잘하는 좋은 피처를 뽑아준다는 보장이 없다는 점이 있습니다. 그래서, 차원을 축소하는 데 있어 **클래스 간의 차별성을 최대화**할 수 있는 방향으로 수행하는 것이 **LDA**
- LDA
    - 선형 판별 분석법으로 PCA와 매우 유사
    - PCA는 입력 데이터의 변동성(분산)이 가장 큰 축을 찾았지만, LDA는 **입력 데이터의 결정 값 클래스를 최대한으로 분리**할 수 있는 축을 찾는다. 즉, 래스 간 분산을 최대화하고, 클래스 내부 분산은 최대한 작게 가져가는 방식이다.(클래스의 값들은 모여있고 클래스끼리는 서로 많이 떨어져 있음을 의미)
    - LDA는 공분산 행렬이 아닌 **클래스 내부와 클래스 간 분산 행렬**에 기반해 고유벡터를 구하고 입력 데이터를 투영 (→ 사용되는 행렬만 다르고 계산 과정은 PCA와 동일)

**Comment by miinkang** [comment]
차원 축소

- 다차원 데이터의 차원을 축소해 새로운 차원의 데이터 셋을 생성하는 것

피처 선택

- 종속성이 강한 불필요한 피처 제거
- 특징을 잘 표현하는 주요한 피처를 선택
- 해석이 용이함
- 피처간 상관관계를 고려하기 어려움

피처 추출

- 기존 피처를 저차원의 피처로 압축
- 저차원 매핑을 뜻함
- 상관 관계를 고려하기 용이함
- 해석이 어려움
- PCA, SVD, NMF, LDA 등이 있음

**Comment by miinkang** [comment]
차원 축소

- 다차원 데이터의 차원을 축소해 새로운 차원의 데이터 셋을 생성하는 것

피처 선택

- 종속성이 강한 불필요한 피처 제거
- 특징을 잘 표현하는 주요한 피처를 선택
- 해석이 용이함
- 피처간 상관관계를 고려하기 어려움

피처 추출

- 기존 피처를 저차원의 피처로 압축
- 저차원 매핑을 뜻함
- 상관 관계를 고려하기 용이함
- 해석이 어려움
- PCA, SVD, NMF, LDA 등이 있음
