### ISSUE TITLE
베이지안과 프리퀀티스트 간의 입장차이를 설명해주실 수 있나요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#118]

**Comment by import-max** [comment]
- 베이지안은 사전 확률을 미리 염두해두고 사건의 발생에 따라 베이즈 정리로 사후 확률을 구해 다시 사전 확률을 업데이트시킨다. 과거의 사건이 현재 사건에 영향을 끼친다는 견해를 가지고 있다.
- 프리퀀티스트는 확률을 발생하는 현상의 빈도수로 바라본다. 현재의 객관적인 확률에 의해서만 사건이 발생한다는 견해를 가지고 있다.

**Comment by kimyuuuuuu** [comment]
- 베이지안
    - 사건의 확률을 바라볼 때, 사전 확률을 미리 염두해두고 사건의 발생에 따라 베이즈 정리로 사후 확률을 구해 다시 사전 확률을 업데이트시킨다. 즉, 베이지안은 **과거의 사건이 현재 사건에 영향을 끼친다는 입장**을 가지고 있다.
    - 이전의 경험과 현재의 증거를 토대로 어떤 사건의 확률을 추론하는 알고리즘
- 프리퀀티스트
    - 확률을 무한번 실험한 결과, 객관적으로 발생하는 현상의 빈도수로 바라본다. 즉, 프리퀀티스트는 **현재의 객관적인 확률에 의해서만 사건이 발생한다는 입장**을 가지고 있다.

**Comment by jarammm** [comment]
- 베이지안은 모수(parameter)를 변수라고 여기지만, 프리퀀티스트는 상수로 여기는 입장
    - 프리퀀티스트는 새롭게 얻은 관측값이 이미 내린 결론에 부합하는지만을 확인할 뿐이지만 베이지안은 기존에 갖고 있던 결론에 즉시 업데이트함으로써 새로운 사후분포를 구한다.

**Comment by miinkang** [comment]
베이지안 

- 과거의 사건이 현재 사건에 영향을 끼친다는 입장
- 모수는 변할 수 있다는 입장
- 사전 확률을 미리 염두해두고 발생에 따라 사후 확률을 구한 후 사전 확률을 업데이트 함
- 머신러닝에서 베이지안의 입장이 인간의 사고방식과 비슷하다는 점을 주목함

프리퀀티스트 

- 현재의 객관적인 확률에 의해서만 사건이 발생한다는 입장
- 모수는 고정된 값이라는 입장
- 확률을 무한번 실험한 결과, 객관적으로 발생하는 현상의 빈도수로 바라봄

**Comment by miinkang** [comment]
https://www.notion.so/006-7b93d4275e1c45388227c8fbcec16550

잘 설명된 글이 있어 공유합니다.
