### ISSUE TITLE
GD가 Local Minima 문제를 피하는 방법은?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#119]

**Comment by import-max** [comment]
- **SGD,**  **Momentum, Adagrad, Adam** 등이 있다.

**SGD**는 Stochastic Gradient Descent으로, 데이터를 확인한 후에 weight를 update 하는 방식이다.  매번 데이터를 볼 때마다 랜덤으로 shuffle하는 방식인데, 너무 비효율적이기 때문에 이 비효율을 해결하기 위해 mini-batch gradient descent가 등장했다. 데이터 1개가 아니라 하나의 mini-batch 만큼 데이터를 확인한 뒤에 weight 를 update하는 방법으로, 요새는 SGD가 mini-batch gradient descent를 가리키는 의미로 혼용하여 사용되기도 한다.

**Momentum**이란 관성을 의미하며, 기존에 변수가 가던  방향의 관성을 어느 정도 유지시켜 local minima에 빠지지 않게 만든다. 이전 속도를 이용해서 지수 평균을 통해 새로운 속도를 계산할 수 있다. 관성을 이용하여, 학습 속도를 보정하고 변곡점을 잘 넘어갈 수 있도록 해주는 역할을 수행한다.

**Adagrad**란 뉴럴넷의 파라미터를 확인하고 크게 변한건 더 작게 변화시키는 방법이다. gradient 그래디언트가 얼만큼 변했는지를 제곱해서 더하는데, 계속 커진다는 문제가 발생하고 만약 이 값이 너무  커지면 분모가 점점 무한대에 가까워지게 되어, 뒤로 갈수록 학습이 점점 안되는 문제점이 발생한다. 이를 해결하기 위해 RMSProp를 통해 개선했다.

**Adam**은 Gradient의 history와 Momentum을 모두 고려해서 Adagrad+Momentum이 합쳐져 붙여진 네이밍이다. 요즘 거의 디폴트로 많이 사용되고 있다.  momentum 역할을 수행하고, 각각 파라미터에 서로 다른 학습률을 적용한다.  과거의 기울기의 가중 평균과 지수적으로 감소하는 가중 평균을 적용한다.

**Comment by jarammm** [comment]
- 최적화 기법 - sgd, momentum, adagrad, rmsprop, adam 등
- sgd : 확률적 경사하강법. mini batch 단위로 gd 실행
- momentum : 이전 gradient의 방향성을 담고있는 `momentum`
 인자를 통해 흐르던 방향을 어느 정도 유지시켜 local minima에 빠지지 않게 만듦
- adagrad : 적게 변한건 더 크게 변하게 하고, 크게 변한건 더 작게 변화시키는 방법이다.(sum of gradient squares 사용)
- rmsprop : Adagrad의 단점을 해결하기 위한 방법. 그레디언트값의 제곱값을 합하지 않고 대신 그 지수평균을 구해 활용
- adam : Momentum 방식과 유사하게 지금까지 계산해온 기울기의 지수평균을 저장하며, RMSProp과 유사하게 기울기의 제곱값의 지수평균을 저장

**Comment by kimyuuuuuu** [comment]
Local minima 문제를 피하는 방법: Momentum, Nesterov Accelerated Gradient(NAG), Adagrad, Adadelta, RMSprop, Adam

Adagrad란 뉴럴넷의 파라미터가 많이 바뀌었는지 적게 바뀌었는지 확인하고, 적게 변한건 더 크게 변하게 하고, 크게 변한건 더 작게 변화시키는 방법이다. Adagrad는 sum of gradient squares($G_t$)를 사용하는데, 이는 그래디언트가 얼만큼 변했는지를 제곱해서 더하는 것이므로 계속 커진다는 문제가 발생한다. $G_t$가 계속 커지면 분모가 점점 무한대에 가까워지게 되어, $W$ 업데이트가 되지 않게 되어, 뒤로 갈수록 학습이 점점 안되는 문제점이 발생한다.

Momentum이란 관성을 의미하며, 이전 gradient의 방향성을 담고있는 momentum 인자를 통해 흐르던 방향을 어느 정도 유지시켜 local minima에 빠지지 않게 만든다. 즉, 관성을 이용하여, 학습 속도를 더 빠르게 하고, 변곡점을 잘 넘어갈 수 있도록 해주는 역할을 수행한다.

**Comment by miinkang** [comment]
- 최적화 기법을 사용함 (optimizer)

SGD (Stochastic Gradient Descent)

- 데이터를 확인 후에 어느 방향으로 갈지 정하는 기초적인 방식
Momentum

- 이전 gradient의 방향성을 담고 있는 관성(momentum)인자를 통해 방향을 유지시켜 Local minima에 빠지지 않게 만든다.

Nesterov Accelerated Gradient(NAG)

- 미리 한 스텝을 옮긴 후에 방향을 결정

Adagrad

- 타임스텝으로부터 변화를 반영함
- 이전 변화량에 특정 비율을 곱해 더한 인자를 따로 둔 후에 사용
