### ISSUE TITLE
프로세스와 스레드의 차이(Process vs Thread)를 알려주세요.

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#120]

**Comment by kimyuuuuuu** [comment]
- **프로세스(Process)**란 운영체제로부터 시스템 자원을 할당받는 작업의 단위로 메모리에 올라와 실행되고 있는 프로그램의 인스턴스(독립적인 개체)를 의미한다.
- **할당받는 시스템 자원의 예**
    - CPU 시간, 운영되기 위해 필요한 주소 공간, Code, Data, Stack, Heap의 구조로 되어 있는 독립된 메모리 영역

- 프로세스
    - 프로세스는 각각 독립된 메모리 영역(Code, Data, Stack, Heap의 구조)을 할당받는다.
    - 프로세스당 최소 1개의 스레드(메인 스레드)를 가지고 있다.
    - 각 프로세스는 별도의 주소 공간에서 실행되며, 한 프로세스는 다른 프로세스의 변수나 자료구조에 접근할 수 없다.
    - 한 프로세스가 다른 프로세스의 자원에 접근하려면 프로세스 간의 통신(IPC, Inter-Process Communication)을 사용해야 한다.
- 스레드
    - 프로세스가 할당받은 자원을 이용하는 실행의 단위로 프로세스와는 다른 더 작은 실행 단위 개념이다. 스레드는 프로세스의 코드에 정의된 절차에 따라 실행되는 특정한 수행 경로이다.
    - 스레드는 프로세스 내에서 각각 Stack 영역만 따로 할당받고 Code, Data, Heap 영역은 공유한다.
    - 스레드는 한 프로세스 내에서 동작되는 여러 실행의 흐름으로, 프로세스 내의 주소 공간이나 자원들(힙 공간 등)을 같은 프로세스 내에 스레드끼리 공유하면서 실행된다.
    - 같은 프로세스 안에 있는 여러 스레드들은 같은 힙 공간을 공유한다. 반면에 프로세스는 다른 프로세스의 메모리에 직접 접근할 수 없다.
    - 각각의 스레드는 별도의 레지스터와 스택을 갖고 있지만, 힙 메모리는 서로 읽고 쓸 수 있다.
    - 한 스레드가 프로세스 자원을 변경하면, 다른 이웃 스레드(sibling thread)도 그 변경 결과를 즉시 볼 수 있다.

**Comment by jarammm** [comment]
- 프로세스는 서로 메모리를 공유하지 않는 데에 반해 스레드는 하나의 프로세스 안에서 서로 메모리 영역을 공유한다.
- 한 프로세스에서 오류가 발생한다면?
    
    공유하고 있는 파일을 손상시키는 경우가 아니라면, **다른 프로세스에는 아무런 영향을 주지 않는다**
    
- 한 스레드에서 오류가 발생한다면?
    
    스레드는 **Code/Data/Heap 메모리 영역의 내용을 스레드 간 공유**하기 때문에 어떤 스레드 하나에서 오류가 발생한다면 **같은 프로세스 내의 다른 스레드 모두가 강제로 종료**된다.

**Comment by import-max** [comment]
- 프로세스는 실행파일로 .exe 형태로 실행되기도 하고, 메모리에 올라와서 연속적으로 실행되고 있는 프로그램의 인스턴스라고 할 수 있다. 각각 독립된 메모리 영역(Stack, Code, Data, Heap)을 할당받는다.
- 스레드는 프로세스 내에서 실행되는 여러 흐름의 단위로, 프로세스의 특정한 수행 경로를 의미하기도 한다. 프로세스 내에서 각각 stack만 따로 할당받고 Code, Data, Heap은 공유한다.

**Comment by miinkang** [comment]
프로세스

- 운영체제로부터 자원을 할당받는 작업의 단위
- 실행될 때 운영체제로부터 프로세서, 필요한 주소 공간, 메모리 등을 할당받음
- 한 프로그램 당 할당된 메모리 내의 정보에만 접근할 수 있는 제약이 있음 → 스레드가 필요했던 이유

스레드

- 프로세스가 할당받은 자원을 이용하는 실행 흐름의 단위
- 프로세스 내의 주소 공간이나 자원들을 같은 프로세스 내의 스레드끼리 공유하면서 실행됨
    - Stack 영역만 따로 할당받고 Code, Data, Heap 영역은 공유
- 시스템 자원을 효율적으로 관리하기 위해 사용 → 멀티 스레드를 사용하면 시스템 콜이 줄어들기 때문
- 프로세스 간의 통신보다 스레드 간의 통신 비용이 적음
- 스레드간의 자원 공유는 전역 변수를 이용하기에 동기화 문제에 신경을 써야함
