### ISSUE TITLE
알고 있는 metric에 대해 설명해주세요. (ex. RMSE, MAE, recall, precision ...)

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#121]

**Comment by miinkang** [comment]
mae, mse, rmse

- 예측값과 실제값 사이의 오차를 이용한 평가지표

오차행렬 (confusion matrix)

- 실제 true를 true로 예측한 것을 true positive (정답)
- 실제 false를 false로 예측한 것을 true negative (정답)
- 실제 true를 false로 잘못 예측한 것을 false negative (오답) : 2종 오류
- 실제 false를 true로 잘못 예측한 것을 false positive (오답) : 1종 오류

오차행렬로 구할 수 있는 metric들 

- 정확도 (accuracy)
    - 전체 예측에서 정답을 얼마나 맞췄는가
    - TP+TN / TP+TN+FP+FN(전체)
- 재현율 (recall)
    - 실제 true를 true라고 예측한 비율
    - TP / TP+FN
- 정밀도 (precision)
    - 예측 결과 중 실제 true를 맞춘 비율
    - TP / TP+FP
- f1-score
    - recall, precision의 조화평균
    - 데이터가 불균형할 때 성능을 정확하게 평가할 수 있음

ROC 커브

- 민감도 (sensitivity)
    - = 재현율
- 특이도 (specificity)
    - 실제 false를 false라고 예측한 비율
    - TN / TN+FP
- X : 1-특이도, Y : 민감도
- (0,0) 시작, (1,1) 에서 수렴
- 커브 밑의 면적을 AUC라고 하며, AUC의 값이 0.5보다는 크고 0.7이상이 되어야 수용할만한 수준이라고 평가함

**Comment by jarammm** [comment]
- accuracy : 정확도. 전체 데이터 중에서 (true, false 무관하게) 맞게 예측한 데이터의 비율.
- recall : 재현율. 실제 True인 것 중에서 모델이 True라고 예측한 것의 비율.
- precision : 정밀도. 모델이 True라고 분류한 것 중에서 실제 True인 것의 비율.
- f1-score : recall과 precision의 조화평균값으로 두 지표를 모두 적절히 반영

**Comment by import-max** [comment]
- 주요 task를 classification으로 할지, regression으로 할지에 따라 metric이 달라진다.

Classification
- accuracy, precision, recall

Regression
- MAE, MSE, RESE
