### ISSUE TITLE
ReLU의 문제점은?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#122]

**Comment by miinkang** [comment]
- 0 이상이면 그대로 내보내고, 이하면 0으로 수렴한다.
- 음수 값이 모두 0이 된다. → 가중치 업데이트가 안된다.

**Comment by import-max** [comment]
- 결과값이 음수일 경우 해당 값들이 모두 0이 된다는 것이다. 이를 해결하기 위해 음수를 일부 반영해주는 LeakyReLU가 등장하였다.
- ELU는 ReLU와 유사하게 생겼으면서도 exp를 이용해 그래프를 부드럽게 만들고, 그로 인해 미분 시 0에서 끊기는 ReLU와 달리 미분해도 부드럽게 이어진다. 음의 출력을 생성할 수 있다. ReLU에 비해 성능이 크게 증가한다는 이슈가 없으며 속도도 더 느려 잘 사용하지 않는다.

**Comment by jarammm** [comment]
- 뉴런이 죽는 경우가 발생한다는 사실이 문제점
- 역전파 시 기울기에 0을 곱하면 해당 뉴런과 이후 뉴런들까지 모두 죽게 된다. 0 이하인 값 모두에 대해 일괄적으로 0 취급하므로 죽는 뉴런이 많게 된다.(이를 해결하기 위해 leaky relu가 등장)

**Comment by kimyuuuuuu** [comment]
- 음수 영역에서 saturated 되는 문제가 다시 발생합니다.
- 어떤 업데이트도 되지 않는 `Dead ReLU`문제가 발생
  - ReLU는 결과값이 음수인 경우 모두 0으로 취급하는데, back propagation시 기울기에 0이 곱해져 해당 부분의 뉴런은 죽고 그 이후의 뉴런 모두 죽게 된다.
