### ISSUE TITLE
미니배치를 작게 할때의 장단점은?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#123]

**Comment by jarammm** [comment]
- 장점 : 한 iteration 당 계산량이 적어 속도 빠름, 메모리 사용량 적음
- 단점 : 데이터의 전체적이 경향, 흐름 반영 어려움

**Comment by miinkang** [comment]
장점 

- 계산량이 작아 학습 속도가 빠름
- 배치가 작기 때문에 적은 자원으로도 학습이 가능함
- 기울기가 낮은 구간에서 쉽게 벗어날 수 있음

단점

- 전체 데이터의 경향을 반영하기 힘들다.
- 업데이트가 항상 좋은 방향으로 되지는 않는다.
- 병렬처리를 할 때 동기화 작업이 많이 필요해 오히려 비용이 많이 필요할 수 있음

**Comment by import-max** [comment]
장점 : 한 iteration의 계산량이 적어지기 때문에 step당 속도가 빨라진다. 적은 메모리로도 학습이 가능하다.

단점 : 데이터 전체의 경향을 반영하기 힘들다. 업데이트를 항상 좋은 방향으로 하지만은 않는다.
