### ISSUE TITLE
알고있는 Activation Function에 대해 알려주세요. (Sigmoid, ReLU, LeakyReLU, Tanh 등)

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#124]
- sigmoid 함수
    - 입력을 0~1 사이의 값으로 바꿔준다.
    - 가장 많이 사용되었던 활성화 함수라고 합니다.
    - 단점
        - `saturation`
            - 입력 값이 크거나 작을 때 기울기가 0에 가까워짐. 이는 `gradient vanishing` 문제를 야기하므로 요즘에는 활성화 함수로서 잘 사용되지 않는다.
        - 시그모이드 함수가  `zero-centered` 하지 않다.
            - 입력값의 부호에 그대로 영향을 받으므로 경사하강법 과정에서 정확한 방향으로 가지 못하고 지그재그로 움직이는 문제가 있다.
- tanh 함수
    - 특징
        - 시그모이드에 비해서 0에 수렴하는 속도가 느리다.
        - 출력 값은 -1에서 1로 압축시켜줍니다.
        - zero-centerd 합니다(Nice!, sigmoid가 가졌던 두 번째 문제점을 해결해줍니다)
    - 단점
        - 여전히 gradient가 죽는 구간이 있습니다. (양수/음수 구간 모두 존재합니다)
- ReLU 함수
    - 입력이 양수면 그대로, 음수면 0을 출력한다.
    - 특징
        - 양의 값에서는 Saturated 되지 않습니다.
        - 계산 효율이 뛰어납니다. sigmid/tanh보다 훨씬 빠릅니다.(6배 정도)
        - 생물학적 타당성도 가장 높은 activation function이라고 합니다.
    - 단점
        - zero-centerd가 아니라는 문제가 다시 발생했습니다.(non-zero centered)
        - 또한 음수 영역에서 saturated 되는 문제가 다시 발생합니다.
        - 어떤 업데이트도 되지 않는 `Dead ReLU`문제가 발생

**Comment by jarammm** [comment]
- Sigmoid : 출력이 0-1 사이인 함수이고 미분 가능. 출력의 특징 때문에 이진 분류 문제에 잘 사용되지만 입력값이 커질수록 그 미분값이 0에 수렴하게 되어 있어 기울기 소실 문제가 발생.
- ReLU : 거의 모든 CNN 네트워크나 딥러닝에 사용됨. 0이하의 값들에 대해 일괄적으로 0으로 만들어 역전파 시 계산할 필요가 없어져 계산량이 줄어들고, 양수 값들에 대해선  Vanishing Gradient 문제 해결. ****다만 0 이하 값들의 처리 방법 때문에 ****뉴런이 죽는 경우가 발생.
- Tanh : 시그모이드 함수를 변형한 쌍곡선 함수. 시그모이드의 x축 위에 있는 함수라면, tanh는 함수의 중심이 (0,0)이다. 미분 함수를 보면, 0에 수렴하는 것이 보다 느려졌다. 하지만 여전히 기울기 소실 문제는 존재한다.
- Softmax : input값을 [0,1] 사이의 값으로 모두 정규화, 출력값들의 총합은 항상 1이 되는 특성을 가진 함수. 따라서 multi-class classification에서 시그모이드 함수는 사용할 수 없고, 대신 소프트맥스 함수를 사용.

**Comment by miinkang** [comment]
sigmoid

- 입력값을 0에서 1 사이의 범위로 만든다.
- s 자형 그래프
- 입력값이 크거나 작으면 기울기가 0에 가까워 잘 사용되지 않음

Leaky ReLU

- relu의 단점을 보완하기 위해 만들어짐
- 0보다 작으면 0.01 과 같은 아주 작은 수를 곱해준다.

Tanh

- 입력값을 -1에서 1사이의 범위로 만든다.
- 입력값이 없어지는 saturation이 있음

**Comment by import-max** [comment]
- sigmoid 함수 : $s(z)=\frac{1}{1+e^{-z}}$로, 입력을 0~1 사이의 값으로 바꿔준다. 입력 값이 크거나 작을 때 기울기가 0에 가까워지는 `saturation` 문제가 있다. 이는 `gradient vanishing` 문제를 야기하므로 요즘에는 활성화 함수로서 잘 사용되지 않는다.
    - RELU : $f(x) = max(0, x)$로, 입력이 양수면 그대로, 음수면 0을 출력한다. 계산 효율과 성능에서 뛰어난 성능을 보여 가장 많이 사용되는 활성화 함수이다. 양의 입력에 대해서는 `saturation` 문제가 발생하지 않는다.
