### ISSUE TITLE
메모리 관리 전략에는 무엇이 있는지 간략히 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#125]

**Comment by kimyuuuuuu** [comment]
- 스왑
    - 프로세스가 실행되기 위해서는 메모리에 올라가야한다. 실행되어야 하는 여러 프로세스 중
        - swap-out : **기존에 메모리에 올라간 프로세스를 보조 기억장치 (HDD, SSD) 로 보내는 것**
        - swap-in : **보조 기억장치에 있던 프로세스를 메모리에 올리는 것**
    - 일반적으로 **중기 스케줄러에 의해 swap out 시킬 프로세스를 선정하며, 우선순위에 따라 어떤 프로세스를 swap in/out 할지 결정한다.** 우선순위가 낮은 프로세스를 swap out 시키고, 높은 프로세스를 메모리에 올려놓는 방식이다
    - 어떤 프로세스를 swap-out 시킬지에 대한 대표적인 방법으로는 **round-robin**이 있다.
    
- 압축
    - 메모리에 프로세스들을 올리다보면 빈 공간(free) 이 생긴다. 이 공간을 fragmentation(단편화) 이라고 한다
    - 현재 메모리에서 프로세스와 단편화를 파악하고 **프로세스가 연속적으로 메모리 주소에 할당되게 단편화를 없애는 방법**을 압축이라 한다.
    - 프로세스가 사용하는 공간들을 한쪽으로 몰아 자유공간을 확보하는 방법
    - 압축은 효율적이지 못하기 때문에 좋은 메모리 관리 방법이 아니다.
    
- 페이징
    - 메모리에 연속적으로 프로세스를 할당하지 않고, ****메모리를 페이지라는 단위로 **물리적**으로 나눠서 페이지에 프로세스를 올리는 방법이다.
    - 프로세스가 페이지 크기보다 크다면 여러 페이지를 사용한다.
    - 페이지 크기보다 작은 프로세스가 할당되면 내부적으로 공간이 남는 **내부 단편화**가 발생할 수 있다.
    
- 세그멘테이션
    - 세그멘테이션은 **논리적** 단위로 메모리를 나눈다.
    - 이를 위해 세그멘테이션 테이블을 사용하고, 테이블에는 시작주소인 base 와 최대 크기인 limit 가 포함되어 있다.
    - 세그멘테이션은 세그멘트 간에 할당되지 않은 공간이 남는 **외부 단편화**가 발생할 수 있다.

**Comment by jarammm** [comment]
1. 스왑
    1. 메모리 ↔ 보조 기억장치(SSD, HDD) 간의 프로세스 이동
    2. 프로그램 실행이란 프로세스가 메모리 위에 올라가는 것이다. 이때 기존에 메모리에 올라간 프로세스를 쓰지 않아서 보조 기억장치 (HDD, SSD)로 보내는 것을 swap-out, 보조 기억장치에 있던 프로세스를 다시 실행하기 위해 메모리에 올리는 것을 swap-in 이라고 한다.
2. 압축 : 특정한 조치 없이는 여러 프로세스를 실행시킬 때 불규칙적으로 랜덤하게 메모리 위에 올라가게 된다 그럼 메모리에 빈 공간이 생기기도 하는데 이를 fragmentation(단편화)라 한다. 프로세스가 연속적으로 메모리 주소에 할당되게 해 단편화 발생을 방지하는 방법이 압축이다. 다만 방법론적으로 비효율적이기 때문에 잘 사용하지 않는다.
3. 페이징 : 압축의 방법(메모리 연속 할당)을 사용하지 않고, 대신 **메모리를 페이지라는 물리적 단위로 나눠서 각 페이지에 프로세스를 올리는 방법**이다. 프로세스가 페이지 크기보다 크다면 여러 페이지를 사용하면 된다. 그런데 페이지 크기보다 작은 프로세스가 할당되면 페이지 내에 공간이 남는 **내부 단편화**가 발생할 수 있다.
4. 세그멘테이션
    1. 세그멘테이션은 페이징과 달리 **논리적 단위**인 **세그멘테이션 테이블**을 사용하여 메모리를 나눈다. 테이블에는 시작주소(base)와 최대 크기에 대한 정보(limit)가 포함되어 있다. 필요한 만큼 가변적으로 메모리를 가져가므로 동적 메모리 할당 방식이다. 따라서 프로세스가 필요한 메모리 만큼 할당해주기 때문에 내부단편화는 일어나지 않는다.
    2. 단 초반에는 연속적으로 할당할 수 있지만 계속 메모리의 할당과 해제가 반복되면서 **세그멘트 간에 할당되지 않은 공간이 남는 외부 단편화**가 발생할 수 있다.

**Comment by miinkang** [comment]
## 스와핑 (Swapping)

- 메모리와 HDD, SSD 등의 보조 기억장치간에 프로세스를 이동시키는 것
- 프로세스의 주소 공간을 일시적으로 디스크(보조 기억장치)로 내려놓는다.
- 너무 많은 프로그램이 메모리에 동시에 올라와 메모리를 적게 사용해 성능이 떨어지는 것을 방지
- swap out 후 메모리에 있는 프로세스들이 충분히 실행된 후에 다시 swap in 한다.
- 메모리 → 보조 : swap out
- 보조 → 메모리 : swap in

### 중기 스케줄러 (스와퍼, Swapper)

- 메모리에 적재된 프로세스의 수를 동적으로 조절한다.
- 프로세스에 할당된 메모리 주소 공간을 통째로 빼앗아 (프로세스 단위) 디스크의 스왑 영역으로 swap out 시킨다.
- 메모리 공간에 여유가 생기면, 필요한 프로세스의 메모리 주소 공간을 swap in 시킨다.

## 압축

- 단편화 : 메모리에 빈 공간이 생기는 경우
- 단편화 문제 해결 방법
- 더 많은 프로세스가 즉시 실행할 수 있으며, 이용가능한 물리 메모리에 더 많이 할당되도록 하는 방법
- 메모리에 존재하는 단편화 영역을 한 곳으로 모은다.
- 효율적이지 않기에 좋은 방법은 아님

## 페이징

- 연속적으로 할당하지 않고, 페이지 단위로 나누어 프로세스를 올리는 방법
- 단점 : 내부 단편화가 발생할 수 있음

## 세그멘테이션

- 논리적 단위로 메모리를 나누며 세그멘테이션 테이블을 사용함
- 단점 : 외부 단편화가 발생할 수 있음

**Comment by import-max** [comment]
- 스왑
    - 메모리에 올라간 프로세스 → 보조기억장치 : swap out
    - 보조기억장치에 있는 프로세스 → 프로세스 : swap in

- 압축
    - 메모리에 올라간 프로세스 사이사이의 빈 공간(단편화)을 없애고 프로세스를 연속적으로 메모리 주소에 할당되게 하는 것

- 페이징
    - 페이지라는 단위로 나눠 프로세스를 할당하는 것. 페이지보다 작은 프로세스가 할당되면 내부적으로 공간이 남을 수 있다. (내부 단편화)

**Comment by import-max** [comment]
- 스왑
    - 메모리에 올라간 프로세스 → 보조기억장치 : swap out
    - 보조기억장치에 있는 프로세스 → 프로세스 : swap in

- 압축
    - 메모리에 올라간 프로세스 사이사이의 빈 공간(단편화)을 없애고 프로세스를 연속적으로 메모리 주소에 할당되게 하는 것

- 페이징
    - 페이지라는 단위로 나눠 프로세스를 할당하는 것. 페이지보다 작은 프로세스가 할당되면 내부적으로 공간이 남을 수 있다. (내부 단편화)
