### ISSUE TITLE
pickling과 unpickling은 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#126]

**Comment by kimyuuuuuu** [comment]
`직렬화`란 객체를 바이트 스트림(byte stream)으로 변환하여 디스크에 저장하거나 네트워크로 보낼 수 있도록 만들어주는 것을 말한다. 반대로 바이트 스트림을 파이썬 객체로 변환하는 것을 `역 직렬화`라고 한다.

- pickling
    - 파이썬 객체의 직렬화와 역 직렬화를 수행하는 모듈. 파이썬 객체 구조의 직렬화와 역 직렬화를 위한 바이너리 프로토콜을 구현
    - 파이썬 객체 계층 구조가 바이트 스트림으로 변환
    - 파이썬 객체를 직렬화할 때를 `pickling`
- unpickling
    - 바이트 스트림을 역 직렬화할 때를 `unpickling`
    - 바이트 스트림을 객체 계층 구조로 복원

- `[pickle](https://docs.python.org/ko/3/library/pickle.html#module-pickle)` 이 사용하는 데이터 형식은 파이썬에 고유합니다. 이것은 JSON 또는 XDR (포인터 공유를 나타낼 수 없음)과 같은 외부 표준에 의해 부과된 제약이 없다는 장점이 있습니다. 그러나 비 파이썬 프로그램은 피클 된 파이썬 객체를 재구성할 수 없다는 것을 의미합니다.
- 기본적으로, `[pickle](https://docs.python.org/ko/3/library/pickle.html#module-pickle)` 데이터 포맷은 상대적으로 간결한 바이너리 표현을 사용합니다. 최적의 크기 특성이 필요하다면, 피클 된 데이터를 효율적으로 [[압축](https://docs.python.org/ko/3/library/archiving.html)](https://docs.python.org/ko/3/library/archiving.html) 할 수 있습니다.

**Comment by jarammm** [comment]
- 파이썬에서는 pickle 모듈을 통해 어떤 형태의 파일이든 pickle이라는 형태의 데이터로 변환하여 저장할 수 있어서 파싱이 필요할 때 이 pickling을 해서 필요한 곳에 전달 후 다시 unpickling을 통해 원래의 형태로 돌려놓아 쓸 수 있다.
- 바이트형식으로 저장되어 속도가 빠르다는 장점이 있다.
- 저장해놓고 재사용할 때 파일로서 저장하기 어려운 커스텀 클래스와 함수, 학습이 완료된 머신러닝 모델 등을 저장할 때 많이 사용한다.

**Comment by miinkang** [comment]
- pickling
    - 파이썬 객체를 직렬화할 때
    - 데이터를 바이너리(2진법)형태로 변환하는 것
- unpickling : 바이트 스트림을 역 직렬화할 때
- 직렬화 : 객체 → 바이트 스트림으로 변환 → 디스크에 저장 / 네트워크로 전송
- 역직렬화 : 바이트 스트림 → 객체
- pickle이라는 표준 라이브러리를 이용해 처리
    - dump(), load() 함수를 사용함

**Comment by import-max** [comment]
- Python의 모듈 중 pickle 이라는 모듈이 있는데, 파이썬 객체의 직렬화와 역직렬화를 수행하는 모듈이다. 직렬화란 객체를 바이트 스트림으로 변환하여 디스크에 저장하거나 네트워크로 보낼 수 있도록 만들어주는 것이다. 역 직렬화는 반대로 변환하는 것을 의미한다.
- pickle 모듈에서 파이썬 객체를 직렬화하는 것을 pickling, 반대(역직렬화)는 unpickling 이라고 한다.
