### ISSUE TITLE
F분포에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#127]

**Comment by jarammm** [comment]
- **연속확률분포**이고, 정규분포를 이루는 모집단에서 독립추출한 표본들의 **분산**을 나타낸다.
- 2개 이상의 표본집단의 분산을 비교하거나 모집단의 분산을 추정할 때 쓴다. **분산비 검정, 분산 분석, 회귀 분석 등에** 사용된다.
- 이 분포는 기본적으로 카이제곱분포를 따른다. 서로 독립인 두 확률 변수 U와 V가 각각 자유도 $v_1, v_2$인 카이제곱분포를 따를 때 새로운 확률변수 $F=\frac{\frac{U}{v_1}}{\frac{V}{v_2}}$는 자유도가 $(v_1, v_2)$인 F분포를 따른다.
    - 카이제곱분포를 따르는 두 확률변수에 대해 각각을 자유도로 나누고 그 결과를 각각 분자와 분모로 취해준 결과인 새로운 확률변수 F가  F분포를 따른다. 이 F분포의 자유도가 $(v_1, v_2)$라면 $v_1$로 나눠준 결과가 분자로 간 것이다.
- (F분포의 확률밀도함수식이 매우 복잡한데 F-분포표를 만들어 사용하기 때문에 직접 계산할 일은 없다.)

**Comment by miinkang** [comment]
- 두 집단의 분산을다루는 분포
- 두 분산을 나눗셈을 한 후 그 값을 확률분포로 나타냄
- 비대칭모양을 하고 있으며, 양의 값만 존재함
- 1에 가까울 수록 분포가 많다 (값이 비슷한 경우)
- 신뢰구간, 가설검정, 분산분석에서 사용하는 분포
- x축 좌표를 f값이라고 하며, f값은 f분포표를 사용해서 구할 수 있음

**Comment by kimyuuuuuu** [comment]
- 정규분포를 이루는 모집단에서 독립적으로 추출한 표본들의 분산 비율이 나타내는 연속 확률 분포.
- 두 가지 이상의 표본집단의 분산을 비교하거나 모집단의 분산을 추정할때 사용
- 2개 이상의 표본 평균들이 동일한 모평균을 가진 집단에서 추출되었는지 아니면 서로 다른 모집단에서 추출된 것인지를 판단하기 위해 사용
- F 분포의 기본은 카이제곱분포.
