### ISSUE TITLE
OLS (ordinary least squre) regression의 공식은 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#128]

**Comment by miinkang** [comment]
최소차승법

- 데이터 분포 그래프를 그릴 때, 경향을 알기 위한 최적의 추세선을 그리기 위한 방법 중 하나
- 구하려는 해와 실제 해의 오차의 제곱의 합이 최소가 되는 해를 구하는 방법

OLS Regression

- 회귀를 통해 방정식의 상수 값들을 추정하는 데에 사용
- 공식 : 잔차의 제곱의 합
- 단점 : outlier가 있으면 적용하기 힘들다.

**Comment by kimyuuuuuu** [comment]
- 최소자승법(OLS, Ordinary Least Squares) 이란, 산점도를 통해 데이터의 분포 그래프를 그릴때, 이 데이터들의 경향을 알기 위한 최적의 추세선을 그리기 위한 방법 중 하나이다. OLS는 근사적으로 구하려는 해와 실제 해의 오차의 제곱의 합이 최소가 되는 해를 구하는 방법
- 회귀를 통해서 방정식의 상수 값들을 추정하는 데에 사용
