### ISSUE TITLE
Union-find에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#129]
- 공통 원소가 없는, 즉 “상호 배타적” 인 부분 집합들로 나눠진 원소들에 대한 자료구조이다. 합집합(Union)과 찾기(Find) 연산을 제공해서 Union-find이다.
- **합집합(Union)**: 두 개의 집합을 하나의 집합으로 합친다. 서로 연결할 두 노드 A, B가 있다고 할 때, A와 B의 루트 노드인 A'과 B'을 찾는다. A'을 B'의 부모 노드로 혹은 B'을 A'을 부모 노드로 설정한다.
- **찾기(Find)**: 노드가 속한 집합을 반환한다.
- 임의의 노드들에 대해 루트 노드를 확인하여 같은 집합인지 확인하는 문제에서 활용될 수 있다.

**Comment by jarammm** [comment]
- 공통 원소가 없는, 즉 “상호 배타적” 인 부분 집합들로 나눠진 원소들에 대한 자료구조이다. 합집합(Union)과 찾기(Find) 연산을 제공해서 Union-find이다.
- **합집합(Union)**: 두 개의 집합을 하나의 집합으로 합친다. 서로 연결할 두 노드 A, B가 있다고 할 때, A와 B의 루트 노드인 A'과 B'을 찾는다. A'을 B'의 부모 노드로 혹은 B'을 A'을 부모 노드로 설정한다.
- **찾기(Find)**: 노드가 속한 집합을 반환한다.
- 임의의 노드들에 대해 루트 노드를 확인하여 같은 집합인지 확인하는 문제에서 활용될 수 있다.

**Comment by import-max** [comment]
서로소 부분 집합들로 나눠진 원소들에 대한 정보를 다루는 자료구조이다. 유니온-파인드 자료구조는 합집합(Union)과 찾기(Find) 연산을 제공한다.

**Comment by miinkang** [comment]
Disjoint Set

- 중복되지 않는 부분 집합들로 나눠진 원소들에 대한 정보를 저장하고 조작하는 자료구조
- 서로소 집합 자료구조

Union-find

- 두 개의 노드를 선택해서, 현재 이 두 노드가 서로 같은 그래프에 속하는지 판별하는 알고리즘
- Disjoint Set을 표현할 때 사용하는 알고리즘
- 가장 효율적으로 구현할 수 있는 트리구조를 사용
    - 배열을 이용하지 않는 이유
        - 모든 원소를 순회해야 함
        - 시간복잡도 O(N)
- 연산
    - make-set(x)
        - 초기화
        - x를 유일한 원소로 하는 새로운 집합 만들기
    - union(x, y)
        - 합하기
        - x, y가 속한 두 집합을 합치는 연산
    - find(x)
        - 찾기
        - x가 속한 집합의 대표값을 반환
        - 어떤 집합에 속해 있는지 찾는 연산
- 사용 예시
    - 구성 원소가 겹치지 않게 분할 하는데에 자주 사용함
