### ISSUE TITLE
*args, **kwargs 는 무엇이며, 왜 사용하는가?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#13]
[4회차] 2022년 9월 2일 금요일

**Comment by import-max** [comment]
- `*args` 는 함수에 전달되는 argument의 수를 알 수 없거나, list나 tuple의 argument들을 함수에 전달하고자 할 때 사용합니다. 어디서부터 어디까지 담아야 할 지 알 수 없을 때, 일반 변수를 앞에 두고 그 뒤에 *args 를 지정할 수 있습니다. 결과값은 튜플 형태로 출력됩니다.
- `**kwargs` 는 함수에 전달되는 keyword argument의 수를 모르거나, dictionary의 keyword argument들을 함수에 전달하고자 할 때 사용합니다.
- 둘을 함께 사용할 경우 `*args` 를 `**kwargs` 보다 앞에 둬야 합니다.

**Comment by jarammm** [comment]
- *args, **kargs : 동시에 여러 변수를 함수에 전달하고 싶을 때 사용하며 특히 몇 개나 전달할 지 알 수 없을 때 사용하면 편리
- **kargs는 key-value형태로 전달할 때 사용한다.
- *args : 쉼표로 구분해 여러 변수를 전달하면 그 변수들을 담은 튜플이 전달됨
- **kargs : 쉽표로 구분 + key=value의 형태로 변수를 전달하면 그 key-value쌍을 담은 딕셔너리가 전달됨

**Comment by miinkang** [comment]
- *args : 함수에서 인자를 받을 때 인자의 개수를 정하지 않고 복수로 받기 위해 사용합니다. (tuple로 받음)
- **kwargs : keyword arguments의 약자로 “키워드=변수” 딕셔너리 형태로 복수의 인자를 받을 때 사용합니다.
- 둘 다 입력받을 인자의 개수가 유동적일 때 사용합니다.

**Comment by kimyuuuuuu** [comment]
- *args : 함수에 전달되는 argument의 수를 알 수 없거나, 여러개의 매개변수를 함수로 받고싶을때 사용.
- **kwargs :   keyword argument의 수를 모르거나, dictionary의 keyword argument들을 함수에 전달하고자 할 때 사용
