### ISSUE TITLE
여러분이 서버를 100대 가지고 있습니다. 이때 인공신경망보다 Random Forest를 써야하는 이유는 뭘까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#130]
- 인공신경망은 각 레이어가 직렬로 연결되어 있지만, 랜덤 포레스트는 **각 트리들이 병렬적으로 수행**해 앙상블 하는 알고리즘이다.
- 서버가 여러 개 있을 때 랜덤 포레스트를 사용한다면 **각 서버에 하나의 트리 모델을 모델링한 후 그 결과를 앙상블**할 수 있다. 따라서 랜덤포레스트를 사용하는 것이 **속도면에서 효율적**이다.

**Comment by import-max** [comment]
- **랜덤 포레스트**는 여러 결정 트리를 앙상블하여 하나의 모델로 구성하는 방법이다. 랜덤 포레스트는 앙상블 모델(여러 결정 트리를 앙상블하여 하나의 모델로 구성하는 방법)로, 각 서버를 모델의 특성을 이해하는 단일 결정 트리 (Decision tree) 로 **병렬**적이게 구성할 수 있다.
    
    반면, **인공신경망**은 하나의 서버 자체가 모델의 특성을 모두 이해하는 end-to-end 구조로 **직렬**적이게 구성된다. 따라서 서버가 100대 있을 때는, 이를 병렬적으로 활용할 수 있는 **랜덤 포레스트**를 사용한다.

**Comment by miinkang** [comment]
- random forest는 tree기반의 앙상블 모델이기 때문에, 문제를 나누어 그 결과를 합친다. 서버가 여러개일 때 사용하기 용이함
- 인공신경망은 하나의 서버가 모델을 이해하고 동작하기 때문에 병렬적으로 활용할 방법이 없지만 random forest는 100대의 서버를 병렬적으로 활용할 수 있다.
