### ISSUE TITLE
학습시 필요한 GPU 메모리는 어떻게 계산하는가?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#133]

**Comment by import-max** [comment]
- 보통 GPU로 올리는 것은 모델과 데이터셋이므로, **(모델의 크기 + 데이터의 크기 × 배치 크기)**로 학습시 필요한 메모리 크기를 계산할 수 있다.
- 만약 메모리 초과 문제가 발생한다면, 다른 프로세스의 gpu 점유를 제거하거나 batch size를 낮추는 방법을 사용할 수 있다.

**Comment by jarammm** [comment]
to.(cuda)를 붙여 gpu 메모리상에 올리는 모든 것을 합산 → 통상적으로 (모델의 크기 + 데이터의 크기 × 배치 크기)

**Comment by kimyuuuuuu** [comment]
(모델의 크기 + 데이터의 크기 × 배치 크기)로 학습시 필요한 메모리 크기를 계산할 수 있다.
