### ISSUE TITLE
K-means의 대표적 의미론적 단점은 무엇인가요? (계산량 많다는것 말고)

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#134]

**Comment by jarammm** [comment]
*K-means : 특성이 비슷한 데이터를 같은 그룹으로 묶어주어 총 k개의 그룹으로 나누는 클러스터링 알고리즘

- K 를 몇 개로 설정하냐에 따라 성능이 달라진다.
- 그루핑을 하기 좋게 데이터가 잘 모여있는 경우에는 좋아도, 그렇지 않은 경우에는 성능이 좋지 않음

**Comment by import-max** [comment]
K-means 는 특성이 비슷한 데이터를 같은 그룹으로 묶어주는 클러스터링 알고리즘으로, k 개의 군집 개수를 정하고 군집의 중심점을 예측하여 각 데이터와 거리를 비교한 후 군집을 결정한다. 이때, K 를 몇 개로 설정하냐에 따라 성능이 달라지며, 어디를 중심점으로 두냐에 따라 성능이 달라진다. 데이터가 잘 모여있는 경우에 효과적이지만, 노이즈가 많은 경우 효과적이지 않다.

**Comment by kimyuuuuuu** [comment]
- K 를 몇 개로 설정하냐에 따라 성능이 달라진다.
- K 개 군집의 중심점을 예측하여야 하는데, 어디를 중심점으로 두냐에 따라 성능이 달라진다.
- 데이터가 잘 모여있는 경우에 효과적이지, 노이즈가 많은 경우 효과적이지 않다.

**Comment by miinkang** [comment]
K-means 

- 비지도학습, clustering 모델
- 중심값을 설정해서 중심값과 데이터간의 거리를 이용해서 분류
- 위 과정을 더이상 분류가 되지 않을 때까지 반복함
- Cost : 중심값과 얼마나 가까운지

단점

- 관찰치 사이의 거리, 중심값과의 거리(유사성) 을 어떻게 설정하느냐에 따라 결과가 크게 좌우함
- 초기화가 잘못되면 local minima에 빠질 수 있음
- 모든 데이터를 거리만으로 판단하여, 분석 목적이 없기 때문에 결과를 해석하기 어려움
