### ISSUE TITLE
REST와 RESTful의 개념을 설명하고 차이를 말해주세요.

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#136]

**Comment by jarammm** [comment]
- `REST`란 **Re**presentational **S**tate **T**ransfer의 약자로, URI로 자원(Resource)을 명시하고 HTTP 메서드를 통해 해당 자원에 대한 CRUD(Create, Read, Update, Delete) 연산을 적용하는 것을 의미한다.
- `RESTful`이란 REST아키텍쳐를 따른다는 의미이다.

**Comment by import-max** [comment]
- REST(Representational State Transfer) : URI로 데이터베이스의 정보(이하 자원)을 명시하고 HTTP 메서드로 해당 자원에 대한 CRUD 연산을 적용하는 것인데, 클라이언트가 db에 직접 접속하는 것이 위험하기 때문에 REST API를 사용한다. 클라리언트가 HTTP 메서드로 요청하면 서버가 해당 요청을 처리한다.
- RESTful은 REST 아키텍처로 구현된 웹 서비스를 나타내기 위한 용어로, "REST API를 제공하는 웹 서비스는 RESTful하다" 같은 의미임

**Comment by kimyuuuuuu** [comment]
REST란 URI로 자원(Resource)을 명시하고 HTTP 메서드를 통해 해당 자원에 대한 CRUD(Create, Read, Update, Delete) 연산을 적용하는 것을 의미.

RESTful은 REST 아키텍처로 구현된 웹 서비스를 나타내기 위한 용어로, "REST API를 제공하는 웹 서비스는 RESTful하다"처럼 사용

**Comment by miinkang** [comment]
- Representational State Transfer 
: 자원의 이름으로 구분, 해당 자원의 상태를 주고 받는 모든 것
- REST API 
: REST의 특징을 기반으로 API를 구현한 것
- RESTful API
: REST의 설계 규칙을 잘 지켜서 설계된 API
