### ISSUE TITLE
t 분포

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#137]

**Comment by kimyuuuuuu** [comment]
- 표본평균을 이용해 정규 분포의 평균을 해석할때 사용
- 가설검정과 회귀분석에서 사용
- 새로운 확률변수를 정의. t 분포는 종모양으로서 t=0에서 좌우대칭을 이룬다. t 분포의 모양을 결정하는 것은 자유도이며, 자유도가 커질수록 표준정규분포에 가깝게 된다

**Comment by jarammm** [comment]
1. 정규 분포의 평균을 측정할 때 주로 사용되는 분포이다.
2. 확률변수 Z 는 표준정규분포를 따르고, V는 자유도가 v인 카이제곱분포를 따를 때, 서로 독립인 Z와 V에 대해 새로운 확률변수 T가 정의된다.
3. 확률변수 T는 자유도가 v인 T 분포를 따른다.
4. 표본 크기가 30보다 작으면 T 분포를 사용해야 한다. 표본의 크기가 작으면 신뢰도가 낮아지기 때문에 표준정규분포보다 예측범위가 좀 더 높은 T 분포를 사용한다.
5. T분포는 모집단의 분산(혹은 표준편차)이 알려져 있지 않은 경우에 정규분포 대신 이용하는 확률분포라고 볼 수 있다.

**Comment by miinkang** [comment]
- 모집단의 표준편차를 알 수 없을 때
- 표본 평균과 모집단 평균 사이 표준화된 거리를 설명하는 분포
- t분포의 관측값은 정규 분포를 따르는 모집단에서 추출된다.

특징

- 정규분포와 마찬가지로 모양이 매끄러우며 대칭, 평균이 0이다.
- 정규분포와 다르게 모집단의 표준편차를 알고있다는 가정을 내리지 않는다.
- 자유도에 의해 정의된다.
    - 자유도는 표본 크기와 관련이 있음
- 자유도가 클수록 퍼짐의 정도가 작아지며, 자유도가 무한대가 되면 정규분포와 같아진다.

자유도 

- 표본값 중 자유롭게 변할 수 있는 표본의 수
    - 표본수가 n이라면 자유도는 n-1이 된다.

사용

- 모집단이 정규분포를 따르더라도 분산이 알려져 있지 않고 표본의 수가 적은 경우, 평균에 대한 신뢰구간을 추정, 가설검정에 유용하게 쓰임

**Comment by import-max** [comment]
- 정규분포의 경우 표본수가 적으면 신뢰도가 낮아지는데, 이에 대한 대응책으로 정규 분포보다 예측범위가 넓은 분포를 사용하는데 이게 T분포이다.
- 표본의 수에 따라 그래프 모양이 변하며, 많을수록 정규분포와 같아지고 적을수록 옆으로 퍼지는 특징이 있다.
