### ISSUE TITLE
카이제곱 분포

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#138]

**Comment by miinkang** [comment]
- 평균 0, 분산 1인 표준정규분포를 각각 제곱 후 더한 분포
- 표준정규분포를 제곱한 x^2 을 자유도 v개를 합함

사용 

- 분산 분석에 이용 (집단 간 비교 분석이 용이함)

특징 

- 자유도에 따라 모양이 달라짐 (t분포와 유사함)
- 비대칭적인 모양
- 자유도에 따라 모양이 달라짐
- 자유도가 클수록 정규분포에 근사하게 되며 대칭적인 모양을 하게 됨

**Comment by miinkang** [comment]
t 분포
    - 모집단의 표준편차를 알 수 없을 때
    - 표본 평균과 모집단 평균 사이 표준화된 거리를 설명하는 분포
    - t분포의 관측값은 정규 분포를 따르는 모집단에서 추출된다.
    
    특징
    
    - 정규분포와 마찬가지로 모양이 매끄러우며 대칭, 평균이 0이다.
    - 정규분포와 다르게 모집단의 표준편차를 알고있다는 가정을 내리지 않는다.
    - 자유도에 의해 정의된다.
        - 자유도는 표본 크기와 관련이 있음
    - 자유도가 클수록 퍼짐의 정도가 작아지며, 자유도가 무한대가 되면 정규분포와 같아진다.
    
    자유도 
    
    - 표본값 중 자유롭게 변할 수 있는 표본의 수
        - 표본수가 n이라면 자유도는 n-1이 된다.
    
    사용
    
    - 모집단이 정규분포를 따르더라도 분산이 알려져 있지 않고 표본의 수가 적은 경우, 평균에 대한 신뢰구간을 추정, 가설검정에 유용하게 쓰임

**Comment by kimyuuuuuu** [comment]
- 감마분포의 특수한 형태. 
- K개의 서로 독립적인 표준정규 확률변수를 각각 제곱한 다음 합해서 얻어지는 분포. 
- 자유도 K의 카이제곱 분포는 확률변수의 분포이다.

**Comment by import-max** [comment]
k개의 서로 독립적인 표준정규 확률변수를 각각 제곱한 다음 합해서 얻어지는 분포이다. 신뢰구간이나 가설검정 등의 모델에서 자주 등장한다.
