### ISSUE TITLE
GD 중에 때때로 Loss가 증가하는 이유는?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#139]

**Comment by miinkang** [comment]
- minima에 들어갔다가 나오는 경우일 것
- momentum 등의 개념을 도입한 optimization 전략을 사용하게 되면, gradient가 양수인 방향으로 업데이트를 하게 되기 때문에 일시적으로 Loss가 증가할 수 있음

**Comment by kimyuuuuuu** [comment]
- minima에 들어갔다가 나오는 경우일 것이다. 실제로 사용되는 GD에서는 local minima 문제를 피하기 위해 Momentum 등의 개념을 도입한 RMSprop, Adam 등의 optimization 전략을 사용한다.
각 optimization 전략에 따라 gradient가 양수인 방향으로도 parameter update step을 가져가는 경우가 생길 수 있으며, 이 경우에는 Loss가 일시적으로 증가할 수 있다
- 각 최적화 기법에 따라 그림과 같이 gradient가 양수인 방향으로, 다시 말해 loss function의 값이 증가하는 방향으로도 가중치가 갱신될 수 있으며, 이 경우 loss가 증가할 수 있다.

**Comment by jarammm** [comment]
1. local minima에 들어갔다가 나오는 경우일 것이다.
2. optimization 전략에 따라 gradient가 양수인 방향으로 업데이트될 수도 있으며, 이 경우에는 Loss가 일시적으로 증가할 수 있다.

**Comment by import-max** [comment]
- local minima에 들어갔다 나오는 경우에 loss가 증가할 수 있다. 이를 해결하기 위해 RMSprop, Adam 등의 optimization 전략을 사용한다.
- optimization 전략에 따라 gradient가 양수인 방향으로 parameter가 update 될 경우에는 Loss가 일시적으로 증가할 수 있다.
