### ISSUE TITLE
Dropout의 효과는?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#14]
[4회차] 2022년 9월 2일 금요일

**Comment by import-max** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/c08d836f-4721-4230-b393-823ea51d50b0/Untitled.png)

- 드롭아웃은 설정된 확률 ($p)$ 만큼 은닉층(hidden layer)에 있는 뉴런을 무작위로 제거하는 방법입니다. 오버피팅을 방지하기 위한 방법 중 하나로, 확률에 따라 출력을 0으로 설정할 수 있습니다.

**Comment by jarammm** [comment]
드롭아웃(Dropout)은 설정된 확률만큼 은닉층(hidden layer)에 있는 뉴런을 무작위로 제거하는 방법으로, 매번 다른 모델을 학습시키는 것으로 해석할 수 있으므로 앙상블 효과를 낼 수 있다.

**Comment by miinkang** [comment]
- bias란 데이터의 특징 중 일부만 반영해 학습하게 되어 새로운 데이터도 잘 예측을 하지 못하는 것으로 너무 편향이 심하면 underfitting한 모델이 될 수 있습니다.
- 이를 통제하기 위해서는 분산을 높이는 방법으로 편향을 줄일 수 있습니다. feature를 더 많이 반영할 수 있도록 레이어를 추가하거나 분산이 높은 머신러닝 모델을 사용할 수 있습니다. (decision tree, KNN 등)

**Comment by kimyuuuuuu** [comment]
- Drop-out은 0~1 사이의 확률로 은닉층의 뉴런을 무작위로 제거하는 기법이다.
- Drop-out은 학습때마다 무작위로 뉴런을 제거하므로 여러개의 모델을 만들지 않고 이미 있는 모델들을 매번 다른 모델을 학습하는 것으로 해석할 수 있다.
- Drop-out은 오버피팅을 방지하기 위해 사용한다.
- 그리고 추론시 출력에 제거확률을 곱함으로써 앙상블 학습에서 여러 모델의 평균을 내는 효과를 낼 수 있다.
