### ISSUE TITLE
PYTHONPATH란 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#140]

**Comment by miinkang** [comment]
- Import할 때 사용되는 환경변수
- sys.path와 PYTHONPATH에 있는 경로를 탐색해서 파일을 불러옴
- PYTHONPATH에 경로를 추가하면, 파이썬은 이 경로를 sys.path에 추가함

**Comment by jarammm** [comment]
1. 모듈을 import할 때마다 PYTONPATH라는 환경변수를 조회하여 가져온 모듈이 디렉토리에 있는지 확인한다.
2. 터미널에서 `set PYTHONPATH=./way/to/import/module` 과 같은 식으로 명령어를 입력해 실행하면 환경 변수에 경로가 추가되어 해당 경로의 파일들을 불러와 쓸 수 있다. + `sys.path.append` 를 사용해  `sys.path.append(./way/to/import/module)` 와 같은 식으로 사용해도 된다.

**Comment by import-max** [comment]
- python에서 모듈을 import할 때 사용되는 환경변수이다. 모듈을 import할 때마다 PYTONPATH를 조회하여 가져온 모듈이 디렉토리에 있는지 확인한다. 인터프리터는 이를 사용하여 로드할 모듈을 결정한다.
- PYTHONPATH 환경 변수에 경로를 추가하면, 파이썬은 이 경로들을 `sys.path`에 추가한다. 이를 통해 파이썬 코드 내부에서 뿐만 아니라 파이썬 코드 밖에서도 `sys.path`를 조작할 수 있다. PYTHONPATH에는 `sys.path`에 추가할 여러 경로들이 들어간다.
- import는 `sys.path` 리스트에 들어있는 경로들을 탐색하며 불러올 파이썬 파일을 찾는다. 리스트에 들어있는 맨 처음 경로부터 탐색을 시작하여, 특정 경로에서 불러올 파일을 찾았다면 남은 경로를 더 찾아보지 않고 탐색을 중지한다.
```jsx
import sys
print(sys.path)
```
