### ISSUE TITLE
CORS가 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#141]

**Comment by import-max** [comment]
- Cross-Origin Resource Sharing(CORS)는 추가 HTTP헤더를 사용하여, 한 출처에서 실행중인 웹 애플리케이션이 다른 출처의 자원에 접근 권한을 부여하도록 브라우저에 알려주는 체제이다.
- 브라우저와 서버 간의 안전한 교차 출처 요청 및 데이터 전송을 지원한다.

**동작 원리**

- 웹브라우저는 요청할 때 HTTP 프로토콜을 사용하여 요청헤더에 `Origin` 필드에 요청을 보내는 출처를 담아 전송한다.
- 서버가 요청에 응답할 때, 응답 헤더에 ‘허용된 출처’를 내려준다.
- 브라우저는 자신이 보낸 요청의 `Origin`과 서버 응답을 비교해본 후 유효 응답 여부를 결정한다.

**Comment by jarammm** [comment]
- 브라우저에서는 보안적인 이유로 `cross-origin`HTTP 요청들을 제한한다. 따라서 서버가 동의한다면 브라우저에서는 `cross-origin`요청을 허락하고, 동의하지 않는다면 브라우저에서 거절한다. 이처럼 cross-origin요청에 대한 브라우저의 동작(요청 허락 혹은 거절) 매커니즘을 CORS(Cross-Origin Resource Sharing)라 한다.
- `cross-origin` : 프로토콜, 도메인, 포트 번호 중 하나라도 다른 경우를 말한다.
- 서버의 요청에 대한 응답이 왔을 때 브라우저가 요청한 `Origin`과 응답한 헤더 `Access-Control-Request-Headers`의 값을 비교하여 유효한 요청이라면 리소스를 응답한다. 만약 유효하지 않은 요청이라면 브라우저에서 이를 막고 에러가 발생한다.
    - 요청을 보내는 것이 안전한지 확인하기 위해 먼저 OPTIONS 메서드를 사용하여 `cross-origin` HTTP 요청을 보낸다.

**Comment by kimyuuuuuu** [comment]
- 교차 출처 리소스 공유(Cross-Origin Resource Sharing, CORS)는 추가 HTTP 헤더를 사용하여, 한 출처에서 실행 중인 웹 애플리케이션이 다른 출처의 선택한 자원에 접근할 수 있는 권한을 부여하도록 브라우저에 알려주는 체제
- 브라우저와 서버 간의 안전한 교차 출처 요청 및 데이터 전송을 지원

**Comment by miinkang** [comment]
CORS (Cross-Origin Resource Sharing, 교차 출처 리소스 공유)

- 추가 HTTP헤더를 사용, 한 출처에서 실행 중인 웹 애플리케이션이 다른 출처의 선택한 자원에 접근할 수 있는 권한을 부여하도록 브라우저에 알려주는 체제
1. 브라우저에서 보안적인 이유로 cross-origin HTTP요청들을 제한함 
2. 요청을 하기 위해 서버의 동의가 필요함
3. 요청을 허락 또는 거절하는 메커니즘은 HTTP-header를 이용해 가능 

⇒ CORS

cross-origin

- 다음 중 한 가지라도 다른 경우
    - 프로토콜 (e.g. http, https)
    - 도메인
    - 포트 번호

CORS 동작방식 

- simple requests
    - 메서드 :  GET, POST, HEAD 중 하나
    - 헤더 : Accept, Accept-Language, Content-Language, Content-Type 만 허용
    - Content-Type 헤더
        - application/x-www-form-urlencoded
        - multipart/form-data
        - text/plain
- preflight
    - 일반적으로 웹 어플리케이션을 개발할 때 자주 마주치는 시나리오
    - 요청을 한번에 보내지 않고 예비 요청과 본 요청으로 나누어 서버로 전송
    - 본 요청 전의 예비 요청을 preflight라고 부름
        - 예비 요청에는 HTTP 메소드 중 OPTIONS 메소드가 사용됨
