### ISSUE TITLE
지금 나오고 있는 deep learning 계열의 혁신의 근간은 무엇이라고 생각하시나요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#143]

**Comment by import-max** [comment]
- Attention, Transformer, GAN 등의 혁신의 기반이 되는 건 신경망이라고 생각한다. 또한, GAN을 활용하면서 다양한 데이터셋을 만듦으로써 더이상 대용량 데이터셋에 대한 부담을 덜게 되었다.
- 더불어, 하드웨어의 발전 덕분에 훨씬 효율적으로 학습을 할 수 있었다.
- 머신러닝적 방법론, 앙상블, end-to-end모델, parameter 및 metric 발견, 하이퍼파라미터 최적화 등의 방법론적인 개선도 한 몫하였다.

**Comment by jarammm** [comment]
- 거대 데이터셋과 기술의 발달에 따른 GPU 성능 향상으로, 실질적인 딥러닝 학습이 가능하게 된 것이 근간이라 생각

**Comment by kimyuuuuuu** [comment]
- 거대하고 높은 품질의 데이터셋이 공개되면서 혁신적인 발전이 시작되었다고 본다. 
- 현재 좋은 성능을 내는 딥러닝 모델들은 모두 큰 규모의 모델들인데 하드웨어의 발전이 이를 가능하게 하였다.

**Comment by miinkang** [comment]
- 방대한 양의 높은 품질을 가진 데이터셋이 공개되면서 혁신적인 발전이 시작될 수 있었음
- 큰 규모의 모델을 학습할 수 있는 하드웨어의 발전
