### ISSUE TITLE
graph에 대해 모두 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#144]

**Comment by import-max** [comment]
- 연결되어있는 원소간의 관계를 표현한 자료구조이다. 정점(V)과 그것들을 연결하는 간선인 엣지(E)로 구성되어 있다.
- 방향이나 연결 종류에 따라 무방향 그래프, 완전 그래프, 방향 그래프, 부분 그래프 등이 있다.
- 그래프 탐색 방법에 따라 BFS(너비우선탐색), DFS(깊이우선탐색) 등으로 나눌 수 있다.
- BFS(너비우선탐색)는 인접한 노드들을 먼저 탐색하고, 멀리 있는 곳을 나중에 탐색한다. queue에 자료를 담아두고 차례대로 pop한다. 주로 노드 사이의 최단 경로를 찾을 때 사용한다. DFS보다 빠르지만 저장공간이 많이 필요하다.
- DFS(깊이우선탐색)는 그래프 전체를 탐색하되, 하나의 노드의 끝까지 탐색 후 다음 노드를 탐색하는 방식이다. stack을 사용하며 BFS가 느리다는 단점이 있다. 해를 구하기만 하면 종료되기 때문에 구한 값이 최적경로가 아닐 수 있다.

**Comment by kimyuuuuuu** [comment]
- 그래프는 정점과 간선으로 이루어진 자료구조이다. 정점 간의 연결관계는 간선으로 나타낸다.
- Graph Traversal: BFS, DFS 등으로 나눌 수 있다. 
  - BFS(Breadth-First Search, 너비우선탐색)
     - 그래프 전체를 탐색하는 방법 중 하나로써, 현재 확인하는 노드의 인접한 노드들을 먼저 탐색하는 것이다. 시작 정점으로부터 가까운 정점을 먼저 방문하고 멀리 떨어져 있는 정점을 나중에 방문하는 순회하는 방식으로 노드를 탐색한다. 
     - Queue라는 자료구조에 이웃하는 정점을 다 담아놓고 차례대로 pop을 하는 방식으로 구현

  - DFS(Depth-First Search, 깊이우선탐색)
     - 그래프 전체를 탐색하는 방법중 하나로써, 시작점 부터 다음 분기(branch)로 넘어가기 전에 해당 분기를 완벽하게 탐색하고 넘어가는 방법.
     -  Stack이나 재귀함수를 통해서 구현할 수 있는데, 재귀함수가 구현이 간편하다.

**Comment by jarammm** [comment]
- 그래프는 정점과 간선으로 이루어진 자료구조이다. 정점 간의 연결관계는 간선으로 나타낸다. 방향 그래프, 무방향 그래프, 가중치 그래프 등이 있다.
- 구현방법
    - 인접 행렬 : 해당하는 위치의 value 값을 통해서 vertex 간의 연결 관계를 O(1) 으로 파악할 수 있다. Edge 개수와는 무관하게 V^2 의 Space Complexity 를 갖는다. Dense graph 를 표현할 때 적절할 방법이다.
    - 인접 리스트 : vertex 의 adjacent list 를 확인해봐야 하므로 vertex 간 연결되어있는지 확인하는데 오래 걸린다. Space Complexity 는 O(E + V)이다. Sparse graph 를 표현하는데 적당한 방법이다.
- 그래프를 탐색하는 알고리즘
    - DFS : 스택 자료구조 사용, 시간 복잡도 : O(V+E) vertex 개수 + edge 개수
    - BFS : 큐 자료구조 사용, 시간 복잡도  O(V+E) vertex 개수 + edge 개수
    - 이외에도 최소신장트리, 크루스칼 알고리즘, 프림 알고리즘 등을 사용하여 그래프를 탐색할 수 있다.

**Comment by miinkang** [comment]
- 정점과 간선으로 이루어진 자료구조
- 정점간의 관계를 표현하는 조직도

구현방식

- 인접 행렬
- 인접 리스트
