### ISSUE TITLE
최적화 기법중 Newton’s Method와 Gradient Descent 방법에 대해 알고 있나요? 

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#146]

**Comment by jarammm** [comment]
- newton’s method : 함수의 해을 근사하는 방법으로 현재 지점에서 접선을 그리고 접선이 x축과 만나는 지점으로 x를 이동시켜 가면서 점진적으로 해를 찾아간다. 초기값을 잘 주면 잘못 주면 시간이 오래 걸리거나 아예 해를 찾지 못할 수 있다.
- gd : 임의의 지점에서 시작해 미분한 만큼 이동해가며 극소점을 찾아가는 최적화 기법이다. 초기값 설정은 큰 문제가 되지 않지만 수렴 속도가 느리다.

**Comment by kimyuuuuuu** [comment]
- Newton's Method
    - 이 $f_{approx}$ 즉, quadratic approximation을 최소로 만드는 입력 $y$를 찾으려 한다. 이때 $f_{approx}$는 convex이므로 위 식의 gradient를 0으로 만드는 입력 $y$가 $f_{approx}$를 최소로 만들 것이다. 이 결과가 Newton’s method에서의 step update 식이 된다. 아래 식의 미분은 $y$에 대한 미분 임을 기억하자.
    
- Gradient Descent
    - $f$의 2차 테일러 근사항을 사용하고, 2차 항의 경우 실제 2차 미분 결과가 아닌, 정방행렬(identity matrix)과 이를 $t$로 나눈 값으로 가정한다.
- Gradient descent는 2차 미분항을 정방행렬에 상수가 곱해진 값으로 가정하고 gradient를 계산하기 때문에, 등고선(contour)의 접선 방향에 수직하게(perpendicular) 수렴함을 확인할 수 있고, Newton’s method에 비해 느린 수렴 속도를 보인다.

**Comment by import-max** [comment]
*
