### ISSUE TITLE
좋은 모델의 정의는 무엇일까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#15]
[4회차] 2022년 9월 2일 금요일

**Comment by jarammm** [comment]
unseen data, outlier에 robust한 모델, 즉 일반화 성능이 좋은 모델

**Comment by miinkang** [comment]
데이터에 강건한 모델이라고 생각합니다. 이런 모델을 만들기 위해서는 특정 데이터에 오버피팅되지 않도록 학습시켜야하고, 새로운 데이터가 들어왔을 때도 적절한 수준의 성능을 보이도록 일반화해야합니다.

**Comment by import-max** [comment]
- 데이터마다 특성이 다를텐데, 주어진 데이터의 특성을 잘 인지하고 그 패턴을 잘 이해한 모델이 좋은 모델이라고 생각합니다. 예를 들어 데이터의 성질에 따라 복잡한 모델이 나을 때도 있고 간단한 모델이 나을 때도 있습니다. 이렇게 데이터를 다루는 목적과 데이터의 특성에 따라 잘 fit하게 만든 모델이 좋은 모델이 아닐까 생각합니다.
- 혹자는 이렇게 말합니다. 데이터의 패턴을 잘 학습한 모델로, 한 번도 본 적 없는 데이터에 대해 옳은 판단을 내리는 모델이 좋은 모델이라고 합니다.
- 대중적인 모델도 좋은 모델이라고 생각합니다. 우선 조건은 과적합되지 않은 모델이어야 한다고 생각합니다. 목적에 따라 달라질 수 있는데, 예측모델은 loss를 최소화하는 것, 확률추정모델은 likelihood를 최대화하는 것이 좋은 모델이라 할 수 있습니다.

**Comment by kimyuuuuuu** [comment]
실전에서 사용 가능한 모델, 처음 보는 데이터에 대해 옳은 판단을 내리는 모델이 좋은 모델이라고 생각합니다.
