### ISSUE TITLE
출장을 위해 비행기를 타려고 합니다. 당신은 우산을 가져가야 하는지 알고 싶어 출장지에 사는 친구 3명에게 무작위로 전화를 하고 비가 오는 경우를 독립적으로 질문해주세요. 각 친구는 2/3로 진실을 말하고 1/3으로 거짓을 말합니다. 3명의 친구가 모두 “그렇습니다. 비가 내리고 있습니다”라고 말했습니다. 실제로 비가 내릴 확률은 얼마입니까?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#153]

**Comment by miinkang** [comment]
- 실제 비가 내린다면(p), 3명의 친구가 진실을 말하는 경우이다.
    - (2/3)^2 *p
- 실제 비가 내리지 않는다면 (1-p), 3명의 친구는 모두 거짓을 말하는 경우이다.
    - (1/3)^2 *(1-p)
- 베이지안 룰을 적용하면,
    - 사전확률 : 진실을 말할 경우
    - 사후확률 : 비가 내리는 경우
    - P(비가 올 확률|진실을 말한 경우)
        - 비가 올 확률 = P(p)
        - 진실을 말한 경우 = P(t) (편의상, 실제 확률 2/3)
    - = P(p)*(P(t|p)/P(t)
    - = 8p/(7p+1)

**Comment by jarammm** [comment]
- 비가 내릴 확률 : p
- 모두가 진실을 말할 확률 → 2/3확률로 진실을 말한 것 ⇒ 8p/27 = a
- 모두가 거짓말을 할 확률 → 1/3확률로 거짓말을 한 것 ⇒ 1(1-p)/27 = b
- 모두가 비가 내린다고 진실을 말할 확률 → a/(a+b)

**Comment by kimyuuuuuu** [comment]
비가 내릴때(p), 내리지 않을 때(1-p)라고 한다.
비가 내릴때 모든 친구가 비가 내린다고 하면 -> 모두 진실 -> 8p/27
비가 내리지 않는데 모든 친구가 비가 내린다고 하면 -> 모두 거짓 -> 1(1-p)/27

이 계산 확률을 베이즈 법칙을 적용해 계산하면 실제로 출장지에 비가 내릴 확률은 약 72.7%
