### ISSUE TITLE
SVM은 왜 반대로 차원을 확장시키는 방식으로 동작할까요? SVM은 왜 좋을까요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#154]
SVM(Support Vector Machine)

- 분류를 위한 결정경계를 정의하는 모델
- 결정 경계는 데이터 군으로부터 멀리 떨어지는 것이 좋음

support vector

- 결정 경계와 가까이 있는 데이터 포인트들
- 경계를 정의하는 결정적인 역할을 함

margin

- 결정 경계와 서포트 벡터 사이의 거리
- 최적의 결정 경계는 마진을 최대화함

장점

- 분류, 회귀 모두 사용 가능함
    - but, 전처리, 파라미터에 따라 정확도가 달라질 수 있음
- 신경망 기법에 비해 과적합 정도가 낮음
    - 해석이 어려움
- 예측 정확도가 높다
    - 데이터가 커질 수록 모델 속도가 느리고 메모리 할당량이 큼

차원을 확장시키는 방식

- 선형으로 분류할 수 없는 경우
- 데이터 차원을 증가시켜 문제를 단순화시킴
- 결정 경계 평면을 찾는다.

**Comment by jarammm** [comment]
- 장점
    - 분류, 회귀 태스크 모두에 적용 가능
    - 저차원, 고차원 데이터에 모두 적용할 수 있음
- 동작
    - svm은 선이 아닌 면으로 경계를 나누기 위해 차원을 확장시키기도 한다.
    - svm은 비선형 분류에도 사용되는데 이때 커널 트릭을 사용해 입력 데이터를 다차원 공간상으로 매핑할 수 있다.
    - 비선형성을 띤 경계선보다 직관적이고 마진도 커서 분류를 보다 확실히 할 수 있다.

**Comment by kimyuuuuuu** [comment]
- 서포트 벡터 머신(Support Vector machines, 이하 SVM) 모형은 고차원 또는 무한 차원의 공간에서 초평면을 찾아 이를 이용해 분류화 회귀를 수행한다.
- SVM은 지도학습 기법으로 비-중첨(non-overlapping) 분할을 제공하며 모든 속성(attributes)을 활용하는 전역적(global) 분류 모형이다.
- SVM은 을 가지는 선형판별에 기초하며, 속성들간의 의존성은 고려하지 않는다.

-장점
  - 분류와 회귀에 모두 사용 가능
  - 신경망 기법에 비해 과적합 정도가 낮음
  - 예측의 정확도가 높음
 - 단점
  - 데이터 전처리와 매개변수 설정에 따라 정확도가 달라질 수 있다.
  - 예측이 어떻게 이루어지는지에 대한 이해와 모델에 대한 해석이 어렵다
