### ISSUE TITLE
What is the purpose of is, not and in operators?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#155]

**Comment by jarammm** [comment]
is, not은 ==, ≠ 와 비슷하지만 다른 점은 값이 아니라 객체를 비교한단 점이다. A와 B라는 객체에 모두 3이 할당되었다고 할 때 ==으로 비교하면 true이지만, is로 비교하면 false가 나온다.

**Comment by import-max** [comment]
- `is`는 객체 비교 연산자로, 두 변수가 참조하는 객체의 id가 같을 경우 True를 반환한다. 두 변수거 참조하는 객체가 동일한 객체인지 확인할 때 사용한다.
- `not`은 단항 논리 연산자로, 뒤에 오는 boolean 값을 뒤집어서 뒤에 True가 오면 False, False가 오면 True를 반환한다.
- `in`은 멤버 연산자로, b안에 a가 있는지 확인할 때 a in b라고 표현하여 있다면 a가 b안에 있다면 True, 없다면 False를 반환한다.

**Comment by miinkang** [comment]
is 

- 객체 비교 연산자
- 객체 비교
- 객체의 id가 같으면 True를 반환
- ‘==’ , ‘! = ‘ 과는 다른 연산이다.
    - 값을 비교

not 

- 단항 논리 연산자 (logical operator)
- 뒤에 오는 boolean값을 뒤집는다

in

- 멤버 연산자
- 시퀀스 안에 특정 요소가 있는지 확인할 때 사용
