### ISSUE TITLE
Explain Inheritance in Python with an example.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#156]

**Comment by import-max** [comment]
https://supermemi.tistory.com/178

**Comment by import-max** [comment]
- 부모 클래스의 멤버 함수, 멤버 변수를 자식 클래스가 가질 수 있으며 상속을 함으로써 코드 재사용성이 더 좋아지고 관리가 용이해진다. 상속 후에 부모 메소드를 호출할 수 있다. 다중상속이 가능하다.
- 부모 → 자식 : single inheritance
- 부모 → 자식 → 자식 : multi-level inheritance
- 부모 → 여러자식 : hierarchical inheritance
- 여러부모 → 자식 : multiple inheritance
- 메소드 오버라이딩 : 부모 클래스 메소드를 자식 클래스에서 재정의하는 것

**Comment by jarammm** [comment]
파이썬에서의 상속은 클래스 이름 옆 괄호안에 상속할 클래스를 넣는 형식으로 이뤄진다. 상속한 클래스를 호출할 땐 클래스 내부에서 super()를 통해 불러올 수 있다.
