### ISSUE TITLE
이진 검색 트리

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#157]

**Comment by import-max** [comment]
- 이진탐색과 linked list를 결합한 자료구조로, 이진탐색의 효율적인 탐색 능력을 유지하면서도 빈번한 자료입력과 삭제가 가능하게 고안됐다.
- 아래와 같은 조건을 지니고 있다.
    - 노드의 좌측 서브트리에는 노드 값보다 작은 값들을 지닌 노드로 이루어져 있다.
    - 노드의 우측 서브트리에는 노드 값보다 큰 값들을 지닌 노드로 이루어져 있다.
    - 중복된 노드가 없어야 한다.
    - 좌우 서브트리는 이진탐색트리이다.
- 검색, 삽입, 삭제의 세 단계로 이루어진다.
- 검색의 계산 복잡도는 트리의 높이가 $h$일 때 $O(h)$가 된다.
- 삽입의 계산 복잡도는 트리의 높이가 $h$일 때 $O(h)$가 된다.
- 삭제의 계산 복잡도는 트리의 높이가 $h$이고 노드의 레벨이 $d$일 때 $O(d+h-d), O(h)$가 된다.
- 종합적으로 계산복잡성은 $O(n)$이며 이진탐색에 비해 속도가 느리기 때문에 비효율적이라는 단점이 있다. 이를 개선하기 위해 AVL Tree가 제안되었다.

**Comment by miinkang** [comment]
- 이진 탐색과 연결리스트를 결합한 자료구조
- 이진탐색 : 효율적인 탐색 능력 + 연결리스트 : 빈번한 자료입력, 삭제
- 순회 방식
    - 중위 순회
    - 왼쪽, 노드, 오른쪽
- 노드보다 작으면 왼쪽, 크면 오른쪽으로 배치
- 핵심 연산 세가지
    - 검색
    - 삽입
    - 삭제
- 그 밖의 연산
    - 이진탐색트리 생성 (create)
    - 이진탐색트리 삭제 (destroy)
        - 삭제할 때 자식노드가 여러개 있는 경우, 왼쪽 자식노드를 복사해놓고 저장한 후 삭제함
    - 이진탐색트리 비어있는지 확인 (isEmpty)
    - 트리순회 (traverse)
- 시간복잡도
    - O(h)
    - h = 트리의 높이, 최대 가지 수
- 한계점
    - 시간복잡도가 O(h)이기 때문에 기존 이진탐색 (O(log n))의 속도보다 느릴 수 있다.
    - 길게 늘어뜨린 트리의 경우 O(n)이 될 수 있기 때문

**Comment by jarammm** [comment]
- 정의 : 이진탐색(binary search)과 연결리스트(linked list)를 결합한 자료구조
- 목적 : 이진탐색의 효율적인 탐색 능력을 유지하면서도, 빈번한 자료 입력과 삭제를 가능하게끔 고안
- 작동 방식 : 이진탐색트리를 순회할 때는 중위순회(inorder) 방식 사용(왼쪽 서브트리-노드-오른쪽 서브트리 순으로 순회) → 이진탐색트리 내에 있는 모든 값들을 **정렬된 순서대로 읽을 수** 있다.
- 연산 : 검색(retreive), 삽입(insert), 삭제(delete) (+ 이진탐색트리 생성(create), 이진탐색트리 삭제(destroy), 이진탐색트리가 비어 있는지 확인(isEmpty), 트리순회(tree traverse))
