### ISSUE TITLE
분할정복

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#158]

**Comment by miinkang** [comment]
- 여러 알고리즘의 기본이 되는 해결방법
- 큰 문제를 작은 문제로 나눈(분할) 다음 해결하고(정복),  다시 합쳐서 해결하는 개념
- 언제까지 나누나?
    - 나눌 수 없을 때까지
- 각 문제는 재귀함수를 이용해서 정복함
- 분할정복이 응용된 알고리즘
    1. 병합 정렬 , O(n*logn)
    2. 피보나치 수열

**Comment by import-max** [comment]
- 문제를 나눌 수 없을 때까지 나눠서 풀면서 다시 합병하여 답을 얻는 알고리즘이다. 시간복잡도는 $O(nlogn)$이다. 대표적으로 퀵소트나 병합정렬이 있다.
- divide : 분할이 가능한 경우 2개 이상의 문제로 나눈다.
- conquer : 나눠진 문제가 분할이 가능하면 divide, 불가능하면 문제를 푼다.
- combine : conquer한 문제를 통합하여 원래 문제의 답을 얻는다.

**Comment by jarammm** [comment]
- 하나의 큰 문제를 동일한 작은 문제로 더 이상 나눠지지 않을 때까지 쪼개는 것이 분할이고, 분할 완료 후 각 태스크를 하나씩 해내는 것을 정복한다고 표현하고 이 정복한 것들을 계속 더 큰 문제로 병합해나가서 완전한 하나의 문제를 풀도록하는 것이 분할정복 알고리즘이다.
- 쪼개진 하나의 문제는 더 이상 나눌 수 없는 단위여야하며 동일한 하위 문제들의 합이 곧 상위 문제가 되는 형식이어야 한다. 따라서 재귀의 일종으로 볼 수 있다.
- 시간 복잡도 O(nlogn) / 공간 복잡도 O(n)
