### ISSUE TITLE
Bias를 통제하는 방법은 무엇입니까?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#16]
[4회차] 2022년 9월 2일 금요일

**Comment by kimyuuuuuu** [comment]
* bias(편향)은 실제값에서 멀어진 척도로 이 값이 크면 언더피팅을 야기한다. 
- 모델 구조를 수정
    - 가장 적합. 이 방법을 통해 bias와 variance에 영향
- 학습 데이터 추가
    - variance문제를 해결할 수 있지만 bias 관점에서 그렇게 명확한 영향을 주지는 않는다.
- 뉴런이나 계층의 개수가 같은 모델의 크기 증가
    - bias를 줄여준다.
    - 이 방식은 variance도 증가시킬 수 있는데, 이 때 정규화 방식을 사용하면 variance의 증가를 막을 수 있다.

**Comment by jarammm** [comment]
1. 편향이 높다는 것은 모델이 유연하지 않고 오차가 큼을 의미 → **언더피팅**
2. 하지만 편향을 낮추는 데에만 치중하면 분산이 커진다. → 편향-분산의 tradeoff 관계 때문
3. 모든 데이터를 못맞추거나(언더피팅), 특정 데이터만 맞추기보다는(오버피팅) 모든 데이터에 있어서 정답인 값과 그리 큰 차이가 나지 않는 범위의 값을 예측하는 방향으로 학습하도록 해야 ⇒ 편향과 분산을 함께 고려할 필요 있음
4. bias 통제 방법 : 모델의 크기를 키우거나, 개인적인 인사이트와 분석을 바탕으로 직접 모델 구조 및 파라미터를 수정

**Comment by import-max** [comment]
- 뉴런이나 계층의 개수가 같은 모델의 크기 증가, 오류평가시 얻은 지식을 기반으로 입력 특성 수정, 정규화, 모델 구조를 수정, 학습 데이터 추가 등의 방법이 있습니다.

**Comment by miinkang** [comment]
- bias란 데이터의 특징 중 일부만 반영해 학습하게 되어 새로운 데이터도 잘 예측을 하지 못하는 것으로 너무 편향이 심하면 underfitting한 모델이 될 수 있습니다.
- 이를 통제하기 위해서는 분산을 높이는 방법으로 편향을 줄일 수 있습니다. feature를 더 많이 반영할 수 있도록 레이어를 추가하거나 분산이 높은 머신러닝 모델을 사용할 수 있습니다. (decision tree, KNN 등)
