### ISSUE TITLE
앙상블 방법엔 어떤 것들이 있나요?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#17]

**Comment by import-max** [comment]
1. 
    - **앙상블(Ensemble)** 은 여러개의 모델을 조합해서 그 결과를 뽑아 내는 방법이다. 크게 배깅과 부스팅 , 스태킹 등이 있다.
    - 배깅 : 샘플을 여러번 뽑아(Bootstrap = 복원 랜덤 샘플링) 각 모델을 학습시켜 결과물을 집계(Aggregation)하는 방법, 대표적으로 random forest가 있다.
    - 부스팅 : 이전 모델의 오답에 가중치를 높게 부여하여 다음 모델을 학습하는 방법이다. 대표적으로 gradient boosting 이 대표적이다.
    - 스태킹(Stacking) : 여러 개별 모델이 예측한 결과값을 다시 학습 데이터셋으로 사용해서 모델을 만드는 방법이다.

**Comment by kimyuuuuuu** [comment]
- 앙상블이란 여러개의 모델을 조합해서 그 결과를 뽑아내는 방법이다.
- 앙상블의 예시로는 스태킹, 배깅, 부스팅이 있다.
- 스태킹은 개별 모델이 예측한 데이터를 다시 meta data set으로 사용해서 학습하는 것이다.
- 배깅은 **샘플을 여러 번 뽑아(Bootstrap) 각 모델을 학습시켜 결과물을 집계(Aggregration)**하는 방법이다.
- 부스팅은 가중치를 활용하여 약분류기를 강분류기로 만드는 방법이다. 부스팅은 배깅과 다르게 모델간 팀워크가 이루어져있다.

- 배깅은 독립적, 부스팅은 순차적(연결)

**Comment by miinkang** [comment]
1. 배깅 : 샘플을 여러번 뽑아 각 모델을 학습시킨 후 결과물을 집계 (e.g. random forest)
2. 부스팅 : 이전 모델의 오답에 가중치를 높게 부여해 다음 모델을 학습
3. 스태킹 : 개별 모델의 결과값을 다시 학습 데이터셋으로 사용해서 모델을 만드는 방법

- 부스팅, 스태킹은 동일한 데이터로 재학습하기 때문에 오버피팅의 문제점이 있다.
