### ISSUE TITLE
하이퍼 파라미터는 무엇인가요?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#18]

**Comment by import-max** [comment]
하이퍼 파라미터는 사용자가 직접 지정하는 값이다. 이는 정해진 최적의 값이 없으며, 사용자의 지식을 기반으로 설정한다. 예를들어 딥러닝의 하이퍼 파라미터에는 학습률, 배치 사이즈 등이 있고, 가중치는 학습 과정에서 바뀌는 값이며 이는 파라미터에 속한다.

**Comment by jarammm** [comment]
1. 하이퍼 파라미터는 머신러닝 모델이 학습 과정에서 학습하거나 통제할 수 없는 부분으로, 인간이 그동안의 경험적 인사이트를 활용해 직접 제어해주어야 하는 매개변수를 말함
2. 예시 : epoch, batch size, SVM의 C값 등

**Comment by kimyuuuuuu** [comment]
- 하이퍼 파라미터는 사용자가 직접 세팅해주는 값으로, 정해진 값은 없으며 사용자의 지식을 기반으로 설정한다. 딥러닝에서 사용하는 하이퍼 파라미터는 학습률, 배치크기, 은닉층의 개수 등이 있다.

- 사용자가 직접 설정(하이퍼 파라미터)하는냐 아니냐(파라미터)의 차이.
- 파라미터는 가중치, 편향 등이 있다.

- 질문1. 하이퍼 파라미터 튜닝기법들 아는거 있으신가요?
    - Manual Search, Grid Search, Random Search

- 질문2. 하이퍼 파라미터를 사람이 직접 설정하는 이유는?
    - 모델이 학습해서 알 수 있는 부분이 아니다.
