### ISSUE TITLE
시간, 공간 복잡도에 대해 설명해주세요

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#19]

**Comment by import-max** [comment]
- 시간 복잡도(Time Complexity): 알고리즘에 사용되는 연산 횟수의 총량, 공간 복잡도(Space Complexity): 알고리즘에 사용되는 메모리 공간의 총량
- 시간 복잡도는 속도에 대한 분석 결과이고, 공간 복잡도는 메모리 사용량에 대한 분석 결과이다.

**Comment by kimyuuuuuu** [comment]
- 시간 복잡도(Time Complexity)
    - 알고리즘에 사용되는 **연산 횟수의 총량**
    - **속도**에 대한 분석결과
    
- 공간 복잡도(Space Complexity)
    - 알고리즘에 사용되는 **메모리 공간의 총량**
    - **메모리 공간**에 대한 분석결과

- 복잡도를 나타내는 표현
    -  점근적 표기법 : O(빅오), Ω(오메가), Θ(세타)

**Comment by jarammm** [comment]
1. 시간 복잡도 : 알고리즘의 절대적인 실행 시간을 나타내는 것이 아닌 알고리즘을 수행하는 데 **연산들이 몇 번 이루어지는지** 대한 척도.
2. 공간 복잡도 : 프로그램을 실행시킨 후 완료하는 데 필요로 하는 자원 공간의 양 → **할당된 메모리의 크기**

**Comment by miinkang** [comment]
- 알고리즘의 성능을 분석하기 위한 조건들
- 시간복잡도 : 알고리즘을 수행하는 데 연산들이 몇 번 이루어지는 지를 표기하는 법
    - 최악의 경우 : 빅오 표기법을 사용함 (최고 차항의 계수를 제외한 최고 차항만 표시한다.)
    - 최선의 경우 : 빅 오메가 표기법
    - 평균의 경우 : 빅 세타 표기법 
    - 평균은 구하기 어렵기에 최악의 경우를 보통 구함
- 공간 복잡도 : 프로그램 실행 후 완료까지 필요로하는 자원 공간의 양

- 시간복잡도와 공간복잡도는 반비례적인 경향이 있어 알고리즘의 성능 척도는 주로 시간 복잡도를 위주로 판단
