### ISSUE TITLE
 iterator와 iterable의 차이점은 무엇입니까?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#20]

**Comment by kimyuuuuuu** [comment]
- iterable은 iter함수에 인자로 전달 가능한, 반복 가능한 객체이다. 리스트, 딕셔너리, 집합, 문자열 등이 있다. (반복 가능한 객체)
- iterator은 next 함수의 인자로 주면 iterable 객체의 요소의 값을 차례대로 반환한다. (값을 차례대로 꺼낼 수 있는 객체)
   - 내장함수 또는 iterable객체의 메소드로 객체를 생성할 수 있습니다.

**Comment by import-max** [comment]
- 우선 두 개념의 차이점을 말하기 전에, 파이썬에는 `iter` 메서드가 존재하는데,  이를 통해 반복해서 호출할 수가 있다.
- iterator 는 lterable 객체를 순회하며 차례대로 꺼낼 수 있는 객체이다.
- iterable 은 반복이 가능한 객체로, list, dict, set, str, bytes, tuple, range 등이 `iter` 메서드에 전달이 가능한 객체이다. 데이터를 순회할 수 있는 객체이다.
- Iterator 객체는 항상 Iterable 객체가 된다. 하지만 Iterable 객체는 Iterator 객체가 될 수 있지만 아닐 수도 있다.

**Comment by jarammm** [comment]
- iterable 객체는 iterator로 변환 가능한 객체, `iter` 함수에 인자로 전달 가능한, 반복 가능한 객체를 말한다. 예를 들면, 리스트(list), 딕셔너리(dictionary), 집합(set), 문자열(string) 등이 있다.
- iterable 객체를 `iter` 함수의 인자로 넣으면 iterable 객체를 순회할 수 있는 객체를 반환하는데, 이것이 iterator 객체이다.
- iterator 객체를 `next` 함수의 인자로 주면 iterable 객체의 요소의 값을 차례대로 반환한다. 만약 iterable 객체를 모두 순회했다면, *StopIteration* 예외를 발생시킨다.

**Comment by miinkang** [comment]
- iterator 
    - iterable 객체를 순회하는 객체
    - iter() iterable 객체로부터 iterator를 생성하는 메소드
    - next() 메소드로 다음 요소를 탐색한다. (__**next()__**) 를 호출 
- iterable
    - iterable한 객체 : 한번에 하나씩 돌려줄 수 있는 객체라는 뜻 == 순회할 수 있는 객체
    - e.g. list, set, tuple, dictionary, string

**Comment by miinkang** [comment]
Iterator가 갖는 장점 **lazy evaluation**에 관해 잘 설명되어 있는 글 공유합니다.
https://shoark7.github.io/programming/python/iterable-iterator-generator-in-python
