### ISSUE TITLE
generator에 대해 설명해주세요.

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#21]

**Comment by miinkang** [comment]
- iterator를 생성하는 함수
- iterable한 순서가 지정되며, lazy evaluation이 가능(메모리 절감)
- 명확한 끝이 없는 객체를 모델링할 수 있음
- yield 키워드를 사용해 구현
- 모든 generator는 iterator이다.

**Comment by jarammm** [comment]
- 값을 차례대로 꺼낼 수 있는 객체인 iterator를 생성해주는 함수로, 함수안에 yield 키워드를 사용
- 함수이기 때문에 그대로 사용하는 것이 아니라 객체를 생성하여 사용하며, 그 객체가 곧 iterator 객체임
- 느슨하게 평가된다.(순서의 다음 값은 필요에 따라 계산됨)
- 무한한 순서가 있는 객체를 모델링할 수 있다.(명확한 끝이 없는 데이터 스트림. 느슨하게 평가되며 내부의 변수가 유지되고 있기 때문.)
    
    ```python
    def infinite_generator():
    		count = 0
    		while True:
    				count += 1
    				yield count
    
    g = infinite_generator()
    
    ############ 실행 결과 ##############
    
    >>> next(g)
    1
    >>> next(g)
    2
    >>> next(g)
    3
    >>> next(g)
    ...(무한 반복)
    ```
    
- generator타입이며 isinstance로 확인해보면 collections.Iterable의 객체이기도 함
- generator 객체를 동시에 여러 개 생성해도 각기 다른 객체가 됨( → yield가 없는 일반적인 함수일 경우에는 `==` 와  `is` 로 체크해보면 모두 True가 나오지만 generator의 경우 모두 False로 나옴)
- yield 사이에 추가로 코드를 입력하면 이전 yield 직후부터 다음 yield문까지 모두 실행 → 즉, yield문 전에 다른 코드가 존재한다면 그 코드와 함께 실행됨
    
    ```python
    def test_generator():
        print('yield 1 전')
        yield 1
        print('yield 1 후')
        print('yield 1과 2사이')
        yield 2
        print('yield 2 후')
        print('yield 2와 3사이')
        yield 3
        print('yield 3 후')
    
    g = test_generator()
    
    ############ print 결과 ##############
    
    >> next(g)
    yield 1 전
    1
    >> next(g)
    yield 1 후
    yield 1과 2사이
    2
    >> next(g)
    yield 2 후
    yield 2과 3사이
    3
    >> next(g)
    yield 3 후
    ---------------------------------------------------------------------------
    StopIteration                             Traceback (most recent call last)
    <ipython-input-42-e734f8aca5ac> in <module>
    ----> 1 next(g)
    
    StopIteration:
    ```
    
- List, Set, Dictionary의 표현식의 내부도 generator
- yield from : 파이썬 3.3 이상 부터 사용가능
    - 기존 : yield를 사용해 여러 값을 리턴하려면 아래와 같이 for문 사용했음
        
        ```python
        def yield_generator():
        		a = [1,2,3]
        		for i in a:
        				yield i
        
        g = yield_generator()
        list(g)  # [1,2,3] / 그냥 next(g)하면 1,2,3 차례로 리턴
        ```
        
    - yield from
        
        ```python
        def yield_generator():
        		a = [1,2,3]
        		yield from a
        
        g = yield_generator()
        list(g)  # [1,2,3]
        ```

**Comment by kimyuuuuuu** [comment]
- generator란 iterator객체를 간단히 만들 수 있는 함수이다.
    - iterator를 생성해주는 함수, 함수안에 yield 키워드를 사용함
- generator를 만드는 방법은 1) yield문, 2) 표현식
- iterable한 순서가 지정됨(모든 generator는 iterator)
- 느슨하게 평가된다.(순서의 다음 값은 필요에 따라 계산됨)
- 함수의 내부 로컬 변수를 통해 내부상태가 유지된다.

**Comment by import-max** [comment]
1. generator에 대해 설명해주세요.
- iterator 객체를 간단히 만들 수 있는 함수이다. 기존의 iterable, iterator 두 요소를 분리하지 않고 한 요소에 담아 단순화한 개념으로, 나만의 iterator를 customizing하는 것이라 생각하면 된다.
