### ISSUE TITLE
인공신경망(deep learning이전의 전통적인)이 가지는 일반적인 문제점은 무엇일까요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#22]

**Comment by miinkang** [comment]
딥러닝 이전의 인공신경망은 입력된 다수의 신호와 웨이트를 곱한 뒤 활성화함수를 거친 값이 0보다 크면 1, 작으면 -1을 출력하는 선형분류기입니다. 두 개의 논리값이 모두 거짓이거나 참이면 거짓을 출력하고, 두 논리값이 하나는 거짓 하나는 참일 때 참을 출력하는 XOR 논리 연산이 불가능하다는 문제점을 갖고 있습니다.  (⇒ 다층 퍼셉트론)

**Comment by jarammm** [comment]
- 선형적으로 신경망을 구축할 수밖에 없어서 예를 들어 XOR과 같은 문제는 풀지 못함
- 실제세계의 데이터는 훨씬 복잡하고 다양해 선형적으로 구분되기 어려움( → 단층 퍼센트론으로는 불가능하기에 여러 층의 신경망으로 구성된 딥러닝이 출현하게 됨)

**Comment by kimyuuuuuu** [comment]
- 레이어를 깊게 쌓지 못한다. (선형적으로만 가능)
    → 복잡한 문제를 풀지 못함.

**Comment by import-max** [comment]
- 딥러닝 이전의 인공신경망은 문제를 접근할 때 선형적으로만 접근하였다. linear regression, linear classification 을 했기 때문에 레이어를 깊게 쌓지 못했다.
- sigmoid, relu 등의 activation function 을 추가하고, back-propagation 등의 방법으로 모델을 업데이트하며 레이어를 깊게 쌓을 수 있게 되었다.
