### ISSUE TITLE
딥러닝할 때 GPU를 쓰면 좋은 이유는?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#24]

**Comment by miinkang** [comment]
- 딥러닝은 행렬 곱셈과 같은 사칙연산을 기본으로 함 
- 부동소수점 연산을 수행하는 많은 코어가 있어 병렬처리가 가능
- cpu와 비교하면 더 큰 메모리 대역폭을 갖고 있어 큰 데이터를 더 효율적으로 처리 가능

**Comment by jarammm** [comment]
- GPU(Graphics Processing Unit)은 부동 소수점 연산을 수행하는 많은 코어가 있어 수 많은 연산을 **병렬처리**할 수 있다.
- CPU보다 더 큰 메모리 대역폭을 가지고 있기 때문에 **큰 데이터를 더 효율적으로 빠르게 처리**할 수 있다.

> 메모리 대역폭(Memory Bandwidth)란 메모리가 처리할 수 있는 초당 데이터양을 뜻한다.

**Comment by kimyuuuuuu** [comment]
- GPU(Graphics Processing Unit)은 부동 소수점 연산을 수행하는 많은 코어가 있어 수 많은 연산을 병렬처리할 수 있다. 또한 CPU보다 더 큰 메모리 대역폭을 가지고 있기 때문에 큰 데이터를 더 효율적으로 빠르게 처리할 수 있다.

**Comment by import-max** [comment]
GPU는 병렬 연산처리를 할 수 있으며, CPU보다 더 큰 메모리 대역폭을 가지고 있어서 큰 데이터를 더 효율적으로 빠르게 처리할 수 있다.
