### ISSUE TITLE
@classmethod, @staticmethod, @property 가 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#25]
2022년 9월 20일 화요일 - 7회차

**Comment by import-max** [comment]
**@classmethod**

클래스 내부의 함수 중에 @classmethod 로 선언된 함수에 대해서는 클래스의 객체를 만들지 않고도 바로 접근이 가능하다. 하지만 함수의 첫 인자로 클래스를 받아서, 상속되었을 때 자식 클래스의 데이터를 따르는 특징이 있다.

**@staticmethod**

@staticmethod 는 @classmethod 와 마찬가지로 클래스의 객체를 만들지 않고도 바로 접근할 수 있다. 하지만 클래스를 인자로 받지 않기 때문에, 상속되었을 때에도 자식 클래스의 데이터를 따르지 않고 처음에 클래스에서 선언한 데이터대로 함수가 사용된다.

**@property**

객체지향 언어에서는 캡슐화를 위해 변수를 직접 지정하지 않고 객체의 함수를 통해 지정하고 받아오는 setter, getter 함수를 사용한다. 파이썬에서는 이를 편하게 사용할 수 있도록 @property 를 제공한다.

getter 가 될 함수에 @property 를, setter 가 될 함수에 @변수.setter 를 붙이면 된다.

**Comment by kimyuuuuuu** [comment]
- 정적 메서드(클래스에서 직접 접근 가능) 지원
    - @classmethod
        - 클래스 내부 함수 중에서 @classmethod로 선언된 함수에 대해서는 클래스의 객체를 만들지 않고도 바로 접근이 가능함.
        - 함수의 첫 인자로 클래스를 받아서, 상속되었을 때 자식 클래스의 데이터를 따르는 특징이 있다.
        - 클래스의 어떤 옵션을 바꾸는 용도로 사용할 수 있다.
        
    - @staticmethod
        - 클래스의 객체를 만들지 않고도 바로 접근 가능.
        - 클래스를 인자로 받지 않음 → 상속되어도 자식 클래스의 데이터를 따르지 않고 처음에 클래스에서 선언한 데이터대로 함수가 사용됨.
- 캡슐화 지원
    - @property
        - 캡슐화를 위해 변수를 직접 지정하지 않고 객체의 함수를 통해 지정하고 받아오는 setter, getter 함수를 사용한다. 파이썬에서는 이를 편하게 사용할 수 있도록 @property 를 제공한다.

**Comment by jarammm** [comment]
****@classmethod****

- @classmethod 로 선언된 함수에 대해서는 클래스의 객체를 만들지 않고도 바로 접근이 가능
- 함수의 첫 인자로 클래스를 받아서, 상속되었을 때 자식 클래스의 데이터를 따름

****@staticmethod****

- @classmethod 와 마찬가지로 클래스의 객체를 만들지 않고도 바로 접근 가능
- 하지만 클래스를 인자로 받지 않기 때문에, 상속되었을 때에도 자식 클래스의 데이터를 따르지 않고 처음에 클래스에서 선언한 데이터대로 함수 사용

****@property****

getter 가 될 함수에 @property를 붙임
