### ISSUE TITLE
파이썬 array와 list 간의 차이가 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#28]
2022년 9월 20일 화요일 - 7회차

**Comment by kimyuuuuuu** [comment]
- array = 배열 / list = 리스트
- 배열은 **단일 데이터 타입** 요소만 포함할 수 있는 반면, 리스트에는 **다양한 타입의 요소**들이 들어갈 수 있다.
- array의 선언 방법은 `arrayName = array(type, [Values])`처럼 자료형을 정하고, 지정한/동일한 자료형만을 넣을 수 있도록 되어있다.
- list은 변수에 `[]`로 여러 타입의 변수를 묶어서 선언할 수 있다.

**Comment by miinkang** [comment]
- array
    - 요소의 데이터 타입이 동일해야 함(array 모듈을 사용할 시)
        - (numpy) 숫자형과 문자열이 섞이면 모두 문자열로 전환
    - Numpy 패키지 혹은 array 모듈을 통해 사용할 수 있음
    - 수학적 연산을 쉽게 할 수 있음(numpy)
    - 정적 할당 (고정된 크기로 size 변화를 원할 시 새로운 array를 생성해야 함)
        - 모든 요소가 같은 타입이면 고정 타입 버퍼에 저장하는 것이 더 효율적
    - 할당된 공간은 연속적
    
    array module vs Numpy package
    
    - 효율적인 저장 : array module
    - 효율적인 저장 + 연산 : Numpy package
- list
    - 요소의 데이터 타입이 동일하지 않아도 됨
        - 동일하지 않을 때, 리스트의 각 항목에 대한 타입 정보, 참조 횟수, 기타 정보 등이 저장됨
    - 동적 할당
    - 할당된 요소의 메모리가 연속적이 아닐 수 있음

**Comment by import-max** [comment]
- 둘은 저장 방식은 동일하나, 미세한 차이가 있다. array 는 단일 데이터 타입의 요소만 포함할 수 있지만 리스트에는 다양한 타입의 요소가 들어갈 수 있다.

**Comment by import-max** [comment]
Q. array에 다양한 데이터 타입이 들어오면 어떻게 하나요?
- array module 이랑 numpy array 로 나뉘는데 전자는 valueError 발생. 후자는 섞여도 사용 가능

**Comment by jarammm** [comment]
리스트

1. 상이한 타입의 데이터들을 하나의 리스트에 담을 수 있음
2. 리스트 간 연산은 덧셈만 됨. 덧셈 시 원소끼리 더하는 것이 아니라, 원소가 추가되는 것이니 각 리스트가 가지는 원소의 개수는 무관함

어레이

1. 동일한 타입의 데이터들만 하나의 어레이에 담을 수 있음
-> ex. int형, float형 데이터를 하나의 어레이에 담으면 모두 float형으로 변환,
숫자형과 문자열을 함께 담으면 모두 문자열로 변환
2. 어레이 선언 시, 배열 내 원소 개수가 동일해야함
3. 어레이 간 사칙 연산 가능. 다만 어레이 shape이같아야 함
4. 리스트보다 어레이간의 연산 속도가 더 빠름. 대량의 연산일수록 더 빠름.
