### ISSUE TITLE
가상 메모리에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#29]

**Comment by jarammm** [comment]
1. 등장배경 : 물리 메모리보다 큰 프로세스를 수행하기 위해 사용
2. 필요한 부분만 메모리에 적재(**부분적재**)하는 것이 핵심 → 프로세스를 실행할 때, 실행에 필요한 부분만 메모리에 올린다 (적재 여부를 *페이지테이블*에 표시)
3. 메모리를 페이지 단위로 나누어 **페이지 테이블**을 통해 물리 메모리에 맵핑을 하는데, 필요한 페이지만을 스와핑을 통해 메모리에 올리고 나머지는 하드디스크에 두는 방식이다.

**Comment by import-max** [comment]
- 하드웨어의 메모리의 크기보다 큰 용량의 프로세스를 실행하고 싶을 때, 필요한 부분만 메모리에 올려 실행하는 것을 가상 메모리라고 한다.
- 현재 필요한 페이지만 메모리에 올리는 방식이고, 만약 메모리가 꽉찰 경우에는 어떠한 페이지를 내릴지 판단해서 내린다.

**Comment by miinkang** [comment]
- 실제 물리 메모리보다 더 큰 메모리가 있는 것처럼 보이게 하는 방법(메모리 관리 기법)
- 어떤 프로세스가 실행될 때 메모리에 해당 프로세스 전체가 올라가지 않더라도 실행이 가능 → 실행할 애플리케이션보다 메모리가 작아도 애플리케이션을 실행할 수 있음 
- 실행에 필요한 일부분만 메모리에 올리고, 나머지 애플리케이션은 디스크에 남게 됨     
  
- 페이징
    - 외부 단편화 해소
    - 프로세스를 일정한 크기의 페이지로 분할 후 메모리에 적재하는 방식
    - 하나의 프로세스가 사용하는 메모리 공간은 연속적이어야 한다는 제약을 없애는 방법
- 세그멘테이션
    - 내부 단편화 해소
    - 페이지 : 물리적 단위, 세그먼트 : 논리적 단위
    - 프로세스를 세그먼트로 분할해서 메모리에 적재하는 방식 (분할된 크기가 일정하지 않음)
