### ISSUE TITLE
Bubble Sort (버블 정렬) 에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#30]

**Comment by jarammm** [comment]
서로 인접한 두 원소를 검사하여 정렬하는 알고리즘. 인접한 2개의 레코드를 비교하여 크기가 순서대로 되어 있지 않으면 서로 교환한다.

**Comment by import-max** [comment]
0번부터 N-1번까지 하나씩 탐색하여 swap하는 정렬이고, 시간복잡도는 $O(N^2)$ 이다.

**Comment by miinkang** [comment]
- 배열의 0번부터 n-1번까지 탐색을 하면서 인접한 칸과 비교해 swap하는 방식의 정렬 알고리즘
- 0번과 1번, 1번과 2번, 2번과 3번 … n-2번과 n-1번까지 비교함
- 시간복잡도 = O(N^2)

**Comment by kimyuuuuuu** [comment]
- 버블 정렬은 배열의 0번부터 N-1번까지 탐색을 하면서, 인접한 칸과 비교하여 swap(교환)을 하는 방식의 정렬 알고리즘.
- 시간복잡도는 $O(N^2)$
- 정렬시 부가 메모리가 필요 없는 *inplace sort* 기법
아울러 두 값이 같으면 위치를 바꾸지 않기 때문에 *stable sort*기법
