### ISSUE TITLE
조건부 확률은 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#31]

**Comment by kimyuuuuuu** [comment]
- $A$가 일어났다는 전제 하에 사건 $B$가 일어날 확률
- $P(B|A) = P(B \cap A) / P(A)$
- **베이즈 정리**와도 이어지며, 조건부 확률을 이용한 가장 유명한 문제는 [[몬티홀 문제](https://terms.naver.com/entry.naver?docId=3569086&cid=58944&categoryId=58970)](https://terms.naver.com/entry.naver?docId=3569086&cid=58944&categoryId=58970)가 있다.
    - 베이즈 정리를 통해 **가능도(Likelihood)와 증거(Evidence)를 바탕으로 사전확률을 사후확률로 업데이트**한다.

**Comment by miinkang** [comment]
조건부 확률

- P(A|X) : 사건 X가 일어난다는 가정 아래에 사건 A가 일어나는 확률
- P(X) > 0 일 때에만 정의
- P(A|X) = P(A, X)/P(X) 로 표현 가능하다
- 사건 X가 일어난 상황에서 사건 A와 X 교집합이 일어날 확률

베이즈 정리

- P(A) : 사전확률 (사건 X가 발생하기 전에 갖고 있던 사건 A의 확률)
- P(A) → P(A|X) : 사후확률로 바뀌게 됨
- P(A|X) = P(X|A)P(A)/P(X)

**Comment by jarammm** [comment]
어떤 사건이 일어나는 경우에 다른 사건이 일어날 확률
- 언제 사용?
- 베이즈 정리?

**Comment by import-max** [comment]
- 사건 A 가 일어났다는 전제 하에 사건 B가 일어날 확률이다.

$$ P(B|A) = P(B \cap A) / P(A) $$
