### ISSUE TITLE
 외부 단편화와 내부 단편화에 대해 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#35]

**Comment by import-max** [comment]
- 메모리 단편화는 메모리를 쪼개서 나눠 할당하여 사용할 때, 메모리가 존재하지만 연속되지 않고 파편으로 존재하기 때문에 할당이 불가능한 경우가 발생하는 경우를 이야기 한다.
- 내부 단편화란 프로세스가 필요한 양보다 더 큰 메모리를 할당하여 메모리가 낭비되는 경우를 이야기하고, 외부 단편화란 메모리가 할당되고 해제되는 작업 사이에 작은 메모리들이 존재하여 메모리가 낭비되어 공간이 충분해도 메모리가 할당되지 못하는 경우를 이야기 한다.

**Comment by kimyuuuuuu** [comment]
- **메모리 단편화(Memory Fragmentation)**
    - RAM에서 메모리의 공간이 작은 조각으로 나뉘어져 사용가능한 메모리가 존재하지만, **할당이 불가능한 상태**를 말한다.

- **내부 단편화(Internal Fragmentation)**
    - 메모리를 할당할 때 **프로세스가 필요한 양보다 더 큰 메모리가 할당**되어서 프로세스에서 사용하는 **메모리 공간이 낭비** 되는 상황을 말한다.

- **외부 단편화(External Fragmentation)**
    - 작은 메모리가 중간중간에 존재해서 **메모리 공간은 충분하지만 실제로 할당할 수 없는 상황**을 말한다.

**Comment by jarammm** [comment]
- 내부 단편화 : 빈 메모리 공간에 프로세스가 적재될 때, 빈 공간이 애매하게 남아서 어떤 작업을 하기에 너무 작아 쓸 수 없는, 낭비되는 공간이 발생하는 것을 내부 단편화라고 한다.
- 외부 단편화 : 전체 메모리 공간의 합은 실행하려는 프로세스보다 크지만, 각각의 메모리 공간이 모두 실행하려는 프로세스보다 작을 때 발생하는 문제이다. 즉 논리적으로는 프로세스를 실행할 수 있는 공간이 충분함에도 불구하고 물리적인 한계로 인해 프로세스를 메모리에 올릴 수 없어서 낭비되는 공간이 발생할 때 외부 단편화라고 한다.
- 해결 방법
    - 압축기법 : 비용 많이 드는 단점
    - 페이징기법 : 가상메모리사용, **외부 단편화 해결**, 내부 단편화 존재
    - 세그멘테이션기법 : 가상메모리사용, **내부 단편화 해결**, 외부 단편화 존재

**Comment by miinkang** [comment]
- **단편화(fragmentation)**
    - 메모리의 공간이 작은 조각으로 나뉘어져 사용가능한 메모리가 충분히 존재하지만 사용(할당)이 불가능한 상태
- 내부 단편화
    - 사용자 영역이 실행 프로그램보다 커서 사용 공간 할당 후 사용되지 않고 남게 되는 현상
    - e.g. 페이징을 할 때 프로그램보다 페이지가 커서 공간이 남는 경우
- 외부 단편화
    - 남아있는 총 메모리 공간이 요청한 메모리 공간보다 크지만, 남아있는 공간이 연속적이지 않아 발생하는 현상(이로 인해 실제로는 할당할 수 없음)
