### ISSUE TITLE
 Greedy Algorithm에 대해 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#36]

**Comment by jarammm** [comment]
- global minimum : 에러가 최소화되는 절대적인 지점
- local minima : 에러가 최소가 될 수 있는 후보가 되는 지점(아래로 볼록한 지점) 중 Global Minimum을 제외한 지점들
- Local Minima는 자칫 에러가 **최소화되는 지점을 찾았다고 착각**할 수 있기에 함정에 비유할 수 있다. 이를 해결하기 위해 **Momentum과 같은 최적화 알고리즘을 사용하거나 학습률(learning rate)를 잘 조절**하여 Local Minima에서 벗어날 수 있다.

**Comment by kimyuuuuuu** [comment]
- 그리디 알고리즘은 **현재 단계에서 최선의 방법을 선택하는 알고리즘**이다.
- 가장 큰 값만 선택, 가장 작은 값만 선택 등 한 가지 방법을 정해놓고 다음 단계로 나아가서도 같은 방식으로 문제를 해결한다. 단, 그리디 알고리즘이 적용하기 위해서는 항상 적용될 수 있는지 **정당성을 확인**해야 한다.
- 그리디 알고리즘은 다익스트라 알고리즘 등에도 활용 가능하며, 정렬 등과 함께 사용되는 경우가 많다.
- 결정 트리 알고리즘 
   - https://wewinserv.tistory.com/16
   - DT에서의 학습은 적절한 분할 기준에 따라 부분 집합들로 나누는 과정이고, 나뉘어진 자료 부분 집합에 다시 분할 과정이 진행되어 새로운 예측 값이 추가되지 않거나 부분 집합 노드가 목표 변수와 같은 값을 지닐 때 까지 계속된다. 이러한 방식을 Top-down induction of decision trees로 Greedy algorithm의 한 예이다.

**Comment by jarammm** [comment]
- 그리디 알고리즘은 **현재 단계에서 최선의 방법을 선택하는 알고리즘**이다.
- 장점은 무엇보다도 빠르다는 것이며, 단점은 항상 최적화 되지 않는다는 점
- 가장 큰 값만 선택, 가장 작은 값만 선택 등 한 가지 방법을 정해놓고 다음 단계로 나아가서도 같은 방식으로 문제를 해결한다. 단, 그리디 알고리즘이 적용하기 위해서는 항상 적용될 수 있는지 정당성을 확인해야 한다.
- 그리디 알고리즘 종류 :  [[https://velog.io/@jsh5408/그리디-알고리즘-Greedy-Algorithm](https://velog.io/@jsh5408/%EA%B7%B8%EB%A6%AC%EB%94%94-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Greedy-Algorithm)](https://velog.io/@jsh5408/%EA%B7%B8%EB%A6%AC%EB%94%94-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-Greedy-Algorithm)

**Comment by import-max** [comment]
- 현재의 문제에서 가장 최선의 방법을 선택하는 알고리즘으로, 동적 프로그래밍이 너무 많은 일을 하기 때문에 이를 보완하기 위해 사용되는 개념이다. 한 가지 해결방법을 정해두고 다음 단계에서도 같은 방식으로 해결한다. 그래서 그 해결방법이 항상 적용될 수 있는지에 대한 정당성을 확인해야 한다.
- 장점 : 빠르다. 단점 : 항상 최적값을 주지는 않는다.

**Comment by miinkang** [comment]
- 현재 단계에서 최선의 방법을 선택해 최종적인 해답에 도달하는 방법
- 최종 해답에 도달했다고해서 그것이 최적의 방법이라는 보장은 없다.
- 이 알고리즘을 적용하기 위해 다음 조건을 성립해야 함
    - 앞의 선택이 이후의 선택에 영향을 주지 않는다.
    - 문제에 대한 최종 해결 방법은 부분 문제에 대한 최적 문제 해결 방법으로 구성된다.
