### ISSUE TITLE
파이썬에서 GIL이 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#37]

**Comment by jarammm** [comment]
- Global Interpreter Lock 의 약자
- 파이썬 인터프리터가 **한 쓰레드**만 **하나의 바이트코드**만 실행할 수 있게 하는 것
- 하나의 쓰레드에게 모든 자원의 점유를 허락 → 자원 점유 못한 쓰레드는 실행 불가
- GIL 로 인해 다른 언어와 같이 멀티쓰레딩 프로그래밍이 제한됨. 하지만 싱글 스레드의 성능은 낮지 않음
- multi thread를 사용하는 코드라도 한 thread만 python code를 실행 할 수 있도록 하는 것이다. (그래서 단일 thread 프로그램을 실행할 때는 GIL의 영향을 모르겠지만 multi thread code에서는 성능 병목 현상이 발생할 수 있다. 그리고 느리다!)

**Comment by kimyuuuuuu** [comment]
- **멀티쓰레딩**을 할 때, 공유 자원에 대해 여러 쓰레드가 동시에 접근한다면 **갱신된 내용이 유실**되는 등의 문제가 발생할 수 있다. 이를 막기 위해 파이썬은 **GIL (Global Interpreter Lock) 을 통해 python interpreter 에 한 쓰레드만 접근**하여 모든 자원을 사용할 수 있게 한다.
- 정확히는 멀티 쓰레드가 bytecode(=instruction) 한 라인씩을 들고 있기 때문에, **한 쓰레드의 bytecode 한 줄에 대해서만 GIL 은 허용**한다.

- GIL은 Python 코드(bytecode)를 실행할 때에 **여러 thread를 사용할 경우, 단 하나의 thread만이 Python object에 접근할 수 있도록 제한**하는 mutex 이다. 그리고 이 lock이 필요한 이유는 CPython이 메모리를 관리하는 방법이 thread-safe하지 않기 때문이다.

- 멀티쓰레드?
    - 파이썬은 인터프리터 언어로서 기본적으로 싱글 쓰레드에서 순차적으로 동작한다. 따라서 **병렬처리를 하기 위해서는 별도의 모듈**을 사용하여 구현해야 한다.

**Comment by import-max** [comment]
1. 
- Global Interpreter Lock 의 줄임말이다.
- 멀티 쓰레딩을 할 때 여러 쓰레드가 동시 접근하면 내용이 유실될 수 있기 때문에 한 쓰레드만 접근할 수 있도록 함. 인터프리터가 한 쓰레드의 하나의 바이트코드에만 실행시킬 수 있도록 하는 lock 기능.

**Comment by miinkang** [comment]
- Global Interpreter Lock
- 파이썬의 인터프리터가 한 스레드만 하나의 바이트코드를 실행시킬 수 있도록 해주는 Lock
- 한 바이트코드를 실행하는 스레드 이외의 스레드에 lock을 건다.
- gil때문에 멀티스레드가 병렬적으로 일하지 않는다.
