### ISSUE TITLE
파이썬의 튜플과 리스트의 차이점은 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#38]

**Comment by jarammm** [comment]
- 리스트는 인덱싱을 통해 각 원소값을 바꿀 수 있으나 튜플은 변경이 불가합니다.
- 리스트는 대괄호 기호를 사용하고, 튜플은 소괄호 기호를 사용합니다.
- 튜플 이터레이션이 더 빠름(지현님)

**Comment by kimyuuuuuu** [comment]
- 리스트
    - mutable(변경 가능) → 선언 후에도 값에 대한 변경, 삭제가 가능
    - 느림
    - 하나의 튜플/리스트에 다른 타입의 값을 함께 저장할 수 있다
    - 대괄호 `[ ]`
    - 리스트 + 리스트 형식으로 요소를 추가할 수 있음
- 튜플
    - immutable(변경 불가능) → 선언 후에 값을 변경하거나 삭제하는 것이 불가능
    - 소괄호 `( )`
    - 메소드가 없음
    - 다른 타입의 데이터를 담을 수 있다.
    - 튜플 + 튜플 형식으로 요소를 추가할 수는 있으며, 삭제도 indexing을 통해서 삭제하고자 하는 요소의 index를 선택하지 않으면 가능하다.

**Comment by import-max** [comment]
- 튜플은 내용을 수정할 수 없지만 리스트는 수정이 가능하다.
- 튜플은 리스트보다 빠르고, 리스트는 [ ] 의 기호를 사용한다. 튜플은 ( ) 의 기호를 사용한다.
- list는 객체를 복사할 때 서로 identity가 다른 객체로 복사가 돼서 새로운 객체가 생긴다.
- tuple은 서로 identity가 같은 객체로 복사된다. 즉, list처럼 새로운 메모리에 값을 할당하는 것이 아니라, 복사된 변수가 원본과 같은 객체를 가리키고 있다.

**Comment by miinkang** [comment]
- 튜플은 변경이 불가능하다.
    - 변경과 관련된 내장함수를 사용할 수 없다.
    - 용량이 적어 접근이 빠르며 효율적
- 여러 값에 대해 비교가 가능하다.
