### ISSUE TITLE
고유값(eigen value)와 고유벡터(eigen vector)이 무엇이고 왜 중요한지 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#39]

**Comment by kimyuuuuuu** [comment]
- 고유벡터
    - 정방 행렬 A를 선형 변환으로 봤을 때, 선형 변환 A에 의한 변환 결과가 자기 자신의 상수 배가 되는 0이 아닌 벡터
- 고유값
    - 고유벡터의 상수배 값
    
- 정방 행렬 A에 대해서 A**v** = λ**v** 를 만족하는 0이 아닌 열벡터 **v**를 고유 벡터, 상수 λ를 고유값이라고 합니다.

- 고유값, 고유벡터는 **정방 행렬**에 대해서만 정의된다.

- 고유값과 고유벡터를 통해 $A$를 고유값과 고유벡터들로 분해하는 **고유값 분해(eigen decomposition)**, 정방행렬 뿐만 아닌 $m \times n$행렬도 분해할 수 있는 **특이값 분해(SVD)**, 데이터들을 차원 축소시킬 때 가장 원래 의미를 잘 보존시키는 **주성분 분석(PCA)** 등에 활용할 수 있으므로 중요하다.

**Comment by import-max** [comment]
- 벡터 중 선형 변환했음에도 불구하고 원래 벡터와 평행한 경우가 있는데, 이러한 벡터를 고유 벡터, 상수 lambda를 고유값이라 한다.
- 두 값을 통해 특이값 분해나 PCA 등의 작업에 활용할 수 있다.

**Comment by miinkang** [comment]
- 어떤 벡터가 정방행렬에 의해 선형 변환될 때, 원래 벡터와 평행한 경우
- 그 어떤 벡터를 고유 벡터, 고유 벡터에 곱해진 람다를 고유값이라고 함
- 중요한 이유
    
    첫번째, 행렬의 제곱을 빠른 속도로 가능하게 하여 시간복잡도를 줄입니다.(고유값 분해의 활용)
    
    두번째, 이미지 압축, 평점을 통해서 유저 찾기(특이값 분해의 활용)
    
    세번째, 데이터 차원 축소 시 원래 의미릴 가장 잘 보존하게 해준다.(PCA의 활용)
