### ISSUE TITLE
"likelihood"와 "probability"의 차이는 무엇일까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#4]
[1회차] 2022년 8월 23일 화요일

**Comment by miinkang** [comment]
Likelihood 는 가능도, probability는 확률입니다. 
확률은 논리가 바탕이 됩니다. 동전을 던졌을 때 앞이 나올 확률은 직관적으로 50%의 확률이라고 알 수 있습니다. 반면 가능도는 실재가 바탕이 되어야합니다. 충분한 시행을 통해 얻은 데이터를 갖고 앞으로 일어날 가능성을 추론하는 것입니다. 
연속사건의 특정 사건이 일어날 확률은 구할 수 없기 때문에 PDF(확률밀도함수)를 이용해서 구할 수 있습니다. 연속사건의 특정 사건에 대한 가능성을 비교할 때 가능도를 사용합니다.

**Comment by jarammm** [comment]
가능도(likelyhood)와 확률(probability)이다.

확률은 데이터를 직접 보지 않아도 이미 알고 있는 모수를 통해 판단 가능한 논리적 가능성의 정도를 말한다.

반면 가능도는 논리를 따지기 보다는 직접 데이터를 봄으로써, 어떤 데이터값이 가장 많이 등장했는지, 즉 경험적으로 어떤 데이터값이 나올 가능성이 높은지 판단하는 것입니다. 즉, 확률이 아니라 가능성의 정도이므로 세밀한 수치로 받아들이기 보단 작고 큼으로 판단하는 것이 좋습니다. 또한 확률 밀도 함수에서는 확률변수를 변수로 보기 때문에 총합이 1이지만, 가능도 함수에서는 모수를 변수로 보기 때문에 총합이 1이 되지 않을수도 있습니다.

**Comment by kimyuuuuuu** [comment]
Likelehood(가능도) : 고정된 관측값에서 어떠한 확류분포에서 어느정도 확률로 나타나는지
Probablity (확률) : 고정된 확률분포에서 어떠한 관측값이 나오느냐에 대한 예측.

**Comment by import-max** [comment]
- likelihood과 probability는 분모가 다르다. probability는 말 그대로 전체 확률 분포 중 특정한 것이 관측될 확률을 이야기하는 것이기 때문에 항상 모든 확률의 합은 1이 된다.
- 반면, likihood는 어떠한 이벤트가 발생한 후의 결과를 기반으로 가능한 경우의 수를 확률로 도출한다. 간단히 말하면 확률의 확률이라고 볼 수 있다. 주어진 관측값에서 이것이 해당 확률분포에서 나왔을 확률을 이야기한다.

**Comment by jarammm** [comment]
질문) pdf가 무엇의 약자인가요?

**Comment by jarammm** [comment]
(아까 하진 못했지만..생각해보면 좋을 것 같아요ㅎㅎ) 추가질문 : 가능도함수는 어떤 상황에서 왜 사용할까요?
