### ISSUE TITLE
ROC 커브에 대해 설명해주실 수 있으신가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#40]

**Comment by jarammm** [comment]
- ROC 커브는 **이진분류 모델의 성능**을 나타내는 지표
- y축이 민감도로 TPR(실제 양성 중 양성 판정 받은 비율), x축이 FPR(음성 중 양성으로 잘못 판정 받은 비율)
- **민감도(Sensitivity, True positive rate(TPR), Recall)**는 실제 스팸메일에 대해서 스팸이라고 판정한 비율이 되고, **특이도(Specificity, True Negative rate(TNR))**는 실제 정상메일에 대해서 정상이라고 판정한 비율이 된다.
- **민감도와 특이도가 모두 높으면 좋겠지만, 어느 정도 trade off 가 있다.** 민감도가 높으면 특이도가 낮아지고, 민감도가 낮으면 특이도가 높아진다. 예를 들어, 모두 스팸이라고 예측하면 민감도가 1이 되고 특이도는 0이 된다. 모두 정상메일이라고 예측하면 민감도는 0이 되고 특이도는 1이 된다. (1-특이도) 의 값은 거짓 긍정 비율(False Positive Rate, fpr) 이고 ROC curve 는 거짓 긍정 값에 따른 참 긍정 비율(True Positive Rate, tpr) 이라고 볼 수 있다.
- **정확도는 비슷하지만 서로 다른 예측확률을 가진다면 모델 성능 비교를 어떻게 하지?** 이것이 ROC curve 를 그리는 이유가 된다. ROC curve 를 그려서 plot의 하단인 면적을 구하고 이 면적의 크기를 비교한다. 이 면적이 **AUC (Area under the ROC curve)**가 된다.
- **False positive rate(FPR)** = 1-specificity(특이도)

**Comment by kimyuuuuuu** [comment]
- ROC 커브는 **이진분류 모델의 성능**을 나타내는 지표이다.
- 모델이 참이라고 예측하는 경우는 **FPR** (False Positive Rate, 실제 값이 거짓일 때) 과 **TPR** (True Positive Rate, 실제 값이 참일 때) 두 경우로 나뉜다.
- FPR 과 TPR 을 그래프에서 x 축, y 축으로 동시에 표현한 ROC 커브를 통해 모델이 얼마나 옳은 값을 잘 예측하는지 알 수 있게 된다.
- ROC 커브가 좌상단과 가까운 경우 좋은 모델이라고 판단할 수 있다. 모델이 FPR 은 낮게, TPR 은 높게 예측하기 때문이다.

**Comment by import-max** [comment]
- Receiver Operating Characteristic 의 약자로 민감도와 1-특이도로 그려지는 커브 곡선이다. 이진분류 모델의 성능을 나타내는 데에 많이 사용한다.
- 흔히 알고 있는 confusion matrix 에서의 TP 비율을 민감도, TN 비율을 특이도 라고 한다. FP는 T로 예측했지만 틀리게 예측한 것이다.
- roc curve는 True라고 판단한 것 중 실제로 True 인 것의 경우를 곡선으로 그린 것이다.
