### ISSUE TITLE
신뢰 구간의 정의는 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#41]

**Comment by import-max** [comment]
- 어떤 구간을 추정할 때, 모집단의 모수가 위치해 있을 것으로 추정되는 신뢰할 수 있는 구간이다. 쉽게 말하면, 어느 범위 안에 있는지를 보여주는 것이고 이를 통해 모수의 신뢰성을 가늠할 수 있다.

**Comment by jarammm** [comment]
- 정규분포에서 평균값을 중심으로 2 * 표준편차의 범위는 약 95%의 면적을 차지 → “내가 지금 추출한 표본 평균은 모평균으로부터 2 * 표준 오차 (SEM) 범위 안에 95% 확률로 들어온다.”
- 표본 평균의 표준 편차는 “표준 오차(Standard Error of Mean, SEM)”

$$
⁍
$$

- 표본 추출은 무수하게 많은 조합으로 추출할 수 있으므로, 100번 정도 반복 샘플링을 해 보았을 때 95번 가량은 2 * 표준 오차안에 모평균이 들어있다는 뜻이라고 생각할 수도 있다.
- 신뢰 수준이 95%이고 표본 오차가 ±3%(즉, 2 x SEM = 3%)인 여론 조사에서 A 후보와 B 후보에 대한 지지율 조사를 했다고 해보자. 이 때, 100명의 사람에게 질문한 결과 A 후보와 B 후보에 대한 지지율이 각각 40%, 36%가 나왔다고 하자. 여기서 우리에게 주어진 정보인 신뢰 수준 95%, 표본오차 ±3%에 따르면 A 후보 지지율의 모비율은 37-43% 사이에 존재할 확률이 95%이고, B 후보 모비율은 33-39% 사이에 존재할 확률이 95%일 것이다. 여기서 A 후보와 B 후보에 대한 두 구간 37-43%와 33-39%이 A 후보와 B 후보에 대한 95% 신뢰 구간이다. 여기까지 잘 이해했다면 B 후보의 모비율이 더 높을 가능성도 존재한다는 것도 알 수 있다. 왜냐면 A 후보의 지지율에 대한 모비율이 37%, B 후보에 대한 지지율이 39%일 수도 있기 때문이다.

**Comment by miinkang** [comment]
- 모수(모집단의 데이터)가 실제로 포함될 것으로 예측되는 범위
    - 샘플링된 데이터를 기반으로 모수의 범위를 추정하기 위해 사용
- 샘플링된 표본이 모집단을 얼마나 잘 대표하는지 측정하는 방법

**Comment by kimyuuuuuu** [comment]
- 구간 추정에서 모수가 a에서 b 사이에 있을 것으로 추정(신뢰구간)하고 그 확률을 구한다.
- 신뢰구간은 모집단의 모수가 위치에 있을 것으로 신뢰할 수 있는 구간이다.
- 모수가 어느 범위 안에 있는지를 확률적으로 보여주는 방법,
- 모수의 신뢰성을 가늠하기 위해 구한다.
