### ISSUE TITLE
Data Normalization은 무엇이고 왜 필요한가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#42]

**Comment by jarammm** [comment]
> 데이터 정규화
> 
- 데이터가 가진 feature의 스케일(범위)이 심하게 차이가 나는 경우 → 모든 데이터 포인트가 동일한 정도의 스케일(중요도)로 반영되도록, 비교 가능하도록 해주는 게 정규화(Normalization)의 목표

### **1. Min-Max Normalization (최소-최대 정규화)**

- minmaxscaler
- 최소-최대 정규화는 데이터를 정규화하는 가장 일반적인 방법이다. 모든 feature에 대해 각각의 최소값 0, 최대값 1로, 그리고 다른 값들은 0과 1 사이의 값으로 변환하는 거다.
- 이상치(outlier)에 너무 많은 영향을 받는다는 단점 존재

### **2. Z-Score Normalization (Z-점수 정규화)**

- standardscaler
- Z-점수 정규화는 이상치(outlier) 문제를 피하는 데이터 정규화 전략이다.
- X라는 값을 Z-점수로 바꿔줌 (사실 고등학교 수학 시간에 정규분포, 표준점수 등의 개념으로 다루는 내용이다.)

### **3. 정리**

- 정규화를 놓치면 특정 feature가 다른 feature들을 완전히 지배할 수 있고, 그럼 거의 모든 정보를 버리는 꼴이니까 정규화가 필요하다.
- 최소 최대 정규화: 모든 feature들의 스케일이 동일하지만, 이상치(outlier)를 잘 처리하지 못한다.
- Z-점수 정규화 : 이상치(outlier)를 잘 처리하지만, 정확히 동일한 척도로 정규화 된 데이터를 생성하지는 않는다.
- 이상치에 강력한 스케일러로는 robustscaler가 있다고 함

**Comment by import-max** [comment]
- 데이터의 feature들의 분포를 조절하여 scaling을 통해 균일하게 만드는 것이다. 한 가지 데이터가 아니라 다양한 데이터를 사용했을 때 feature간 scale 차이가 많이 난다면, 큰 범위를 가지는 feature가 작은 범위의 feature보다 더 강하게 모델에 반영될 수 있기 때문에 꼭 필요한 작업이다.
- 이러한 불균형을 막기 위하여 동일한 정도로 데이터가 반영될 수 있도록 정규화 작업이 필요하며 이를 통해 얻는 장점은 아래와 같다.
    - 학습 속도 개선
    - 적은 노이즈, 오버피팅 억제
    - 데이터의 bias 줄어듦으로써 좋은 성능의 결과
- Batch Normalization, Min-Max Normalization 등이 있다.
    - batch normalization : 적용하려는 레이어의 통계량, 분포 정규화
    - min-max normalization : 모든 값들을 0-1 사이에 두어 scaling 진행. outlier 처리가 어렵다는 단점 존재.

**Comment by miinkang** [comment]
- 데이터의 feature 스케일을 동일한 정도로 조정하는 것
    - 보통 0~1 사이의 값으로 바꾼다.
- 필요한 이유
    - 데이터가 편향되지 않으므로 성능을 개선할 수 있다.
    - 노이즈가 작아 오버피팅을 억제한다.
    - 학습속도가 개선된다.

**Comment by kimyuuuuuu** [comment]
- Data Normalization = 데이터 정규화
- 특성(feature)들의 분포를 조절하여 균일하게 만드는 방법.
- 데이터 feature 간 scale 차이가 심하게 날때, 큰 범위를 가지는 feature가 더 강하게 모델에 반영될 수 있기 때문에 정규화를 해준다.
- 데이터 정규화 실행시 학습속도 개선, 노이즈가 작아져 오버피팅 억제, 데이터를 덜 치우치게 만드는 기능을 할 수 있다.
