### ISSUE TITLE
L1, L2 정규화에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#43]

**Comment by jarammm** [comment]
- 우선, 1차적으로 과적합을 막기 위해 사용됨
- L1 norm : 맨해튼 거리 / L2 norm : 유클리디안 거리
- 신공신경망 설계 시, 충분히 Sparse할 수 있게끔 구축해야합니다. 때문에 특정 Weight가 과도하게 커지지 않게끔 락(Lock)을 걸어주는 역활을 L1, L2 Regularization이 해줍니다.

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/70b0d751-d1ac-4242-862a-3a3cc3d046bd/Untitled.png)

- L1 정규화 : 기존 Loss에 절댓값만큼의 어떤 족쇄(패널티)를 달아줌으로써 Cost가 더 커지게 만든 셈인데, 모델 Weight의 과도한 변화를 막는다는 느낌에 걸맞습니다. 저기서 람다가 작아질수록, 약한 정규화가 적용됩니다. 불필요한 Feature에 대응하는 Weight를 정확히 0으로 만들어버려, Feature selection의 효과를 냅니다. 마지막으로 L1 Regularization을 사용하는 선형 회귀 모델을 Lasso model이라고도 합니다.
- L2 정규화 : 불필요한 Feature(이상치)에 대응하는 Weight를 0에 가깝게 만들 뿐, 0으로 만들지는 않습니다. 이런 특성 때문에, L1 Reg반해 L2 Reg은 선형 모델의 일반화 능력을 항상 개선시키는 것으로 알려져 있습니다. 마지막으로 L2 Reg을 사용하는 선형 회귀 모델을 Ridge model이라고 합니다.

**Comment by kimyuuuuuu** [comment]
- 정규화(일반화)의 목적 : 모델이 학습 데이터에 오버피팅 되지 않고 처음 보는 테스트 데이터에도 좋은 성능을 내도록 만드는 것
- 모델의 학습은 loss 함수를 최소화하는 방향으로 진행.
- L1 정규화 (라쏘 회귀)
    - 특정 피쳐의 값이 매우 낮은 경우 0에 수렴되는 트깆ㅇ이 있다.

- L2 정규화 (릿지 회귀)
    - 특정 웨이트의 값이 매우 낮아도 0에 수렴되지는 않고 가까워지는 특징이 있다. → 선형 모델에 일반화 효과.
