### ISSUE TITLE
큐와 원형 큐

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#44]

**Comment by miinkang** [comment]
- 큐
    - first in first out
    - 출구와 입구가 따로 존재
    - 들어온 순서를 보장해야하는 경우 사용
        - e.g. 연산처리 작업대기, 프린터 인쇄, 프로세스
- 원형 큐
    - Pop으로 첫번쨰 원소를 제거했는데 Rear가 N-1을 가리키고 있어 새로운 원소를 추가할 수 없는 선형 큐의 단점을 해결하기 위해 사용함
    - 처음에는 front, rear가 같은 메모리를 가리키고, 데이터 입력 전에 rear는 메모리가 꽉찼는지 검사한다. (rear + 1==front 인지 검사) 데이터 입력 후 rear += 1
    - 데이터 반환시에는 front가 메모리가 비었는지 검사한다. (front == rear) 데이터 반환후 front += 1

**Comment by import-max** [comment]
### queue

- queue 란 FIFO 구조의 자료형으로, 먼저 입력된 데이터가 먼저 반환되는 형태이다.
- 보통 연산처리 작업대기, 프린트 작업, 프로세스 관리, bfs 알고리즘 등에 사용된다.

### circular queue

- queue와 같이 FIFO 구조의 자료형으로, 원소를 다 채웠을 때 다른 원소를 추가할 공간이 없는 경우가 있다. 이러한 경우를 해결하기 위해 고안된 방법이다.
- 데이터 입력 전에는 메모리가 꽉찼는지, 반환 전에는 메모리가 비었는지 검사한다. 만약 꽉차거나 비어있는 경우가 아니라면 해당 데이터를 입력/반환 후 다음 데이터로 이동한다. 만약 꽉차있거나 비어있다면 오류가 발생할 수 있다. (큐 사이즈 확장 or 반환할 원소 없음) → 꽉차있다면 linked queue 라는걸 활용할 수 있다.

**Comment by jarammm** [comment]
- **FIFO (First In First Out)**
- CPU 연산처리 작업대기, 프린터 인쇄, 프로세스 관리 등 들어온 순서를 보장해야하는 경우 사용된다.
- BFS 알고리즘에 사용
- 가장 앞에 있는 원소를 **Front**, 그리고 가장 뒤에 있는 원소를 **Rear**라고 합니다.
- 큐에는 기본적으로 두 가지의 연산이 있습니다. 바로 enqueue와 dequeue입니다.
- 큐의 단점 : 큐에 빈 메모리가 남아 있어도, 꽉 차있는것으로 판단할 수도 있음
- 원형 큐
    - 큐의 단점을 개선한 구조로, 큐를 원형으로 생각해야되기 때문에 모듈러 연산(나머지 연산)을 해야합니다.
    - 큐의 시작점은 어느 점이라도 되니 front와 rear의 초기값을 지정
    - 크기가 N 인 queue 에서 모든 원소를 다 채우면 rear 는 N-1 을 가리킨다. 이 때, pop 으로 제일 처음 원소를 제거하면 queue 에 남은 공간 1개가 생긴다. 하지만 rear 는 마지막을 가리키고 있기 때문에 더이상 원소를 추가할 수 없다. 이 문제를 해결하기 위해 원형 형태의 `circular queue` 를 사용한다. queue 와 같이 FIFO 구조의 자료형이다.
    - 동작 방식은 다음과 같다.
        - 처음에는 front 와 rear 가 같은 메모리를 가리킨다.
        - 데이터를 입력하기 위해 rear 는 메모리가 꽉찼는지 검사한다. 꽉찬 경우는 rear 다음 번의 메모리가 front 를 가리키는 경우 (rear + 1 == front) 인데, 꽉차지 않았다면 데이터를 입력하고 rear 는 다음 메모리로 이동한다.
        - 데이터를 반환하기 위해 front 는 메모리가 비었는지 검사한다. 빈 경우에는 현재 front 위치와 rear 위치가 같은 경우 (rear == front) 인데, 비지 않았다면 데이터를 반환하고 front 는 다음 메모리로 이동한다.

**Comment by kimyuuuuuu** [comment]
- 큐는 FIFO (First In First Out) 구조의 자료형. 먼저 들어간 데이터가 먼저 나온다.
- 큐의 경우 pop으로 맨 처음 원소를 제거하더라도 rear가 마지막을 가르키고 있어 더이상의 데이터 추가가 이루어 질 수 없다.
- 원형 큐는 원형이기 때문에 계속 데이터를 추가할 수 있다.
