### ISSUE TITLE
어떨 때 모수적 방법론을 쓸 수 있고, 어떨 때 비모수적 방법론을 쓸 수 있나요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#45]

**Comment by kimyuuuuuu** [comment]
- 통계적 추론 : 표본의 통계량(평균, 표준편차 등)을 통해 모집단의 모수(모평균, 모표준편차 등)를 추정하는 방법
- 모수적 방법 : 모집단이 어떤 분포를 따른다는 가정 하에 통계적 추론을 하는 방법
- 비모수적 방법 : 모집단의 분포를 가정하지 않음.
- 표본의 수가 30개 이상일 때 중심극한 정리에 의해 정규분포를 따르므로 **모수적 방법론**을 사용한다.
- 표본의 수가 30개 미만이거나 정규성 검정에서 정규 분포를 따르지 않는다고 증명되는 경우 **비모수적 방법론**을 사용한다.

**Comment by import-max** [comment]
* 모수적 방법론은 모집단이 어떤 분포를 따른다는 가정 하에 통계적 추론을 하는 방법론인데, 표본의 수가 30개 이상일 때 중심극한 정리에 의해 정규분포를 따른다. 일반적으로 정규성 검정을 따르면 모수적 방법론을, 따르지 않으면서 표본의 수가 30개 미만이라면 비모수적 방법론을 따른다.

**Comment by miinkang** [comment]
- 모집단 : 알고 싶은 궁극적인 집단
- 모집단 전체를 조사하는 것은 불가능하기 때문에 적절한 표본집단을 지정한다.
- 모수 : 모집단의 모평균, 모표준편차, 모분산 등
- 모수적 방법론
    - 비교하고자 하는 두 집단이 모두 정규분포를 띤다면, 그 두 집단은 평균을 비교함으로써 차이를 밝힐 수 있다. 이런 정규성을 갖는다는 모수적 특성을 이용하는 통계적 방법
    - 표본의 수가 30개 이상이거나, 10 ≤ n ≤ 30 이면서 정규성 검정에서 정규분포로 간주되는 연속형 자료일 때 사용 가능
- 비모수적 방법론
    - 정규성 검정에서 정규분포를 따르지 않는다고 증명되거나, 군 당 10명 미만의 소규모실험에서는 정규분포임을 가정할 수 없어 모수적 방법론을 사용할 수 없다.
    - 모수적 방법론을 사용할 수 없을 때는 자료 크기 순으로 배열해 순위를 매긴 다음 순위의 합을 통해 차이를 비교하는 순위합검정을 적용할 수 있다. 이런 방법은 모수의 특성을 이용하지 않아 비모수적 방법론이라고 한다.
    - 단점
        - 검정력이 다소 떨어지며, 크기의 차이를 보여주지 못한다.
    - 장점
        - 표본수가 작거나, 숫자로 되어있는 모든 경우에 비모수적 방법론을 적용할 수 있다.

**Comment by miinkang** [comment]
[질문] 정규성 검정에 대해 설명해주세요.

**Comment by jarammm** [comment]
- 모수적 방법론 : **모집단이 어떤 분포를 따른다는 가정** 하에 통계적 추론을 하는 방법을 모수적 방법이라 하는데, 표본의 수가 30개 이상으로 중심극한 정리에 의해 **정규분포**를 따를 때 사용
- 비모수적 방법론 : 표본의 수가 30개 미만이거나 정규성 검정에서 정규 분포를 따르지 않는다고 증명되는 경우, 즉 모수적 방법론을 쓸 수 없는 상황일 때 사용
