### ISSUE TITLE
머신러닝(machine)적 접근방법과 통계(statistics)적 접근방법의 둘간에 차이에 대한 견해가 있나요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#46]

**Comment by kimyuuuuuu** [comment]
- 머신러닝적 접근방법
    - 모델의 **예측 성공률**을 높이는게 목적이다.
    - 따라서 모델의 신뢰도나 정교한 가정보다는 다양한 피쳐를 사용하여 (오버피팅을 감안하더라도) 높은 예측률을 달성하고자 한다.
- 통계적 접근방법
    - 분포와 가정을 통해 **신뢰 가능하고 정교한** 모델(실패 확률을 줄이는)을 만드는게 목적이다.
    - 단순성을 추구하며, 신뢰도가 중요해진다

**Comment by import-max** [comment]
- 두 방법의 목적이 다른데, 머신러닝적 접근방법은 모델의 성능과 관련이 있다. 즉, 모델의 정확도를 높이는 것이 목적이기 때문에 모델의 신뢰도보다는 높은 예측률을 달성하는 것이 목적이다.
- 통계적 접근방법의 목적은 신뢰 가능하고 정교한 모델을 만드는 것이기 때문에 최대한 단순한 모델을 많이 사용하려고 한다.
- 머신러닝은 과거의 정보에서 미래를 예측하는 것이고, 통계적 접근방법은 소수의 데이터로 다수를 예측하는 것을 목적으로 한다.

**Comment by miinkang** [comment]
- 머신러닝적 접근방법
    - 예측에 집중
    - 모델의 측정을 예측의 퍼포먼스로 한다.
    - 모델의 복잡성보다는 overfitting을 고려한다.
- 통계적 접근방법
    - 모형의 단순성을 추구하며, 인자의 해석가능성에 강조한다.
- 넷플릭스로 예를 들자면,
    - 추천 시스템은 사용자가 믿을만한 영화를 추천하는지로 예측의 퍼포먼스를 평가할 수 있다.
    - 전통적 통계적 접근방법을 사용한다면, 왜 사용자가 해당 영화를 선택하는지를 이해할 수 있는 모형을 만들 것이다. 이 점으로 머신러닝적 접근방법을 본다면, 해석가능성이 부족하다고 설명할 수 있다.

**Comment by jarammm** [comment]
|   | 머신러닝 | 통계 |
|--|--|--|
| 목적 | 모델의 **예측 성공률**을 높이기 | 분포와 가정을 통해 **신뢰 가능하고 정교한** 모델 만들기 |
| 방법 | 다양한 피쳐를 사용하여 (오버피팅을 감안하더라도) 높은 예측률을 달성하고자 함 | 모형을 해석하기 쉽게 단순화 추구하고, 어떤 피쳐가 어떤 원인을 주는지 알 수 있도록 함 |
