### ISSUE TITLE
객체 인터닝(object interning)이란?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#48]

**Comment by kimyuuuuuu** [comment]
- 인터닝 : 이미 생성된 객체(object)를 재사용(reuse)하는 것
- 파이썬에서는 모든 것이 객체이므로 변수들은 값을 바로 가지지 않고 값을 가진 주소를 참조하게 된다.
- 보통 Immutable 객체에 대해 Interning을 사용한다. 파이썬은 기본적으로 몇가지 제한된 경우에 대해 디폴트로 Interning을 사용하고 있으며, 또한 개발자가 필요한 경우 함수를 써서 Interning을 지정할 수도 있다.

- 파이썬의 기본적 사용
    - 문자열: 20자 미만의 공백을 포함하지 않는 문자열
    - 정수: -5부터 256사이의 정수

**Comment by import-max** [comment]
* object에 주소값을 주고 그 주소를 재활용하여 참조하여 사용하는 것이다. 기본적으로 파이썬에서는 -5~256, [a-Az-Z0-9_] 에 대해 고정된 주소를 할당하여 interning 을 하고 있다.

**Comment by jarammm** [comment]
- Interning이란 이미 생성된 객체(object)를 재사용(reuse)하는 것을 말하고, 대개 Immutable 객체에 대해 사용
- 파이썬은 기본적으로 몇가지 제한된 경우에 대해 디폴트로 Interning을 사용하고 있으며, 또한 개발자가 필요한 경우 함수를 써서 Interning을 지정할 수도 있음
- 아주 많이 사용되는 Immutable 객체의 경우 Interning을 사용하게 되면 메모리를 줄일 수 있는 효과 있음
- default interning
    - 문자열: 20자 미만의 공백을 포함하지 않는 문자열
    - 정수: -5 부터 256 사이의 정수
- from sys import intern : 파이썬의 intern() 함수는 문자열을 Interning하는 함수. 자주 사용되는 문자열을 intern() 함수를 사용하여 Intern 컬렉션에 저장해 놓고 사용 가능
