### ISSUE TITLE
 메모리 관리 전략에는 무엇이 있는지 간략히 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#52]

**Comment by kimyuuuuuu** [comment]
- 스왑
    - 프로세스가 실행되기 위해서는 메모리에 올라가야한다. 실행되어야 하는 여러 프로세스 중
        - swap-out : **기존에 메모리에 올라간 프로세스를 보조 기억장치 (HDD, SSD) 로 보내는 것**
        - swap-in : **보조 기억장치에 있던 프로세스를 메모리에 올리는 것**
    - 일반적으로 **중기 스케줄러에 의해 swap out 시킬 프로세스를 선정하며, 우선순위에 따라 어떤 프로세스를 swap in/out 할지 결정한다.** 우선순위가 낮은 프로세스를 swap out 시키고, 높은 프로세스를 메모리에 올려놓는 방식이다
    - 어떤 프로세스를 swap-out 시킬지에 대한 대표적인 방법으로는 **round-robin**이 있다.
    
- 압축
    - 메모리에 프로세스들을 올리다보면 빈 공간(free) 이 생긴다. 이 공간을 fragmentation(단편화) 이라고 한다
    - 현재 메모리에서 프로세스와 단편화를 파악하고 **프로세스가 연속적으로 메모리 주소에 할당되게 단편화를 없애는 방법**을 압축이라 한다.
    - 프로세스가 사용하는 공간들을 한쪽으로 몰아 자유공간을 확보하는 방법
    - 압축은 효율적이지 못하기 때문에 좋은 메모리 관리 방법이 아니다.
    
- 페이징
    - 메모리에 연속적으로 프로세스를 할당하지 않고, ****메모리를 페이지라는 단위로 **물리적**으로 나눠서 페이지에 프로세스를 올리는 방법이다.
    - 프로세스가 페이지 크기보다 크다면 여러 페이지를 사용한다.
    - 페이지 크기보다 작은 프로세스가 할당되면 내부적으로 공간이 남는 **내부 단편화**가 발생할 수 있다.
    
- 세그멘테이션
    - 세그멘테이션은 **논리적** 단위로 메모리를 나눈다.
    - 이를 위해 세그멘테이션 테이블을 사용하고, 테이블에는 시작주소인 base 와 최대 크기인 limit 가 포함되어 있다.
    - 세그멘테이션은 세그멘트 간에 할당되지 않은 공간이 남는 **외부 단편화**가 발생할 수 있다.

**Comment by miinkang** [comment]
- 제한된 메모리를 효율적으로 사용하기 위한 관리 전략이 필요함
- 스와핑 (Swapping)
    - 메모리와 HDD, SSD 등의 보조 기억장치간에 프로세스를 이동시키는 것
    - 메모리 → 보조 : swap-out
    - 보조 → 메모리 : swap - in

    
- 압축
    - 빈 공간이 생길 경우를 단편화라고 함
    - 단편화를 없애는 방법으로 프로세스가 할당되도록 하는 방법
    - 효율적이지 않기에 좋은 방법은 아님
    
 
    
- 페이징
    - 연속적으로 할당하지 않고, 페이지 단위로 나누어 프로세스를 올리는 방법
    - 단점 : 내부 단편화가 발생할 수 있음
- 세그멘테이션
    - 논리적 단위로 메모리를 나누며 세그멘테이션 테이블을 사용함
    - 단점 : 외부 단편화가 발생할 수 있음

**Comment by jarammm** [comment]
- 연속 메모리 할당
    - 프로세스를 메모리에 연속적으로 할당하여 빈틈이 없게 함
    - 다만 할당과 제거를 반복하다보면 중간중간 빈 메모리 공간(scattered holes)이 생겨나 외부 단편화 발생할 수 있음
- 페이징
    - 메모리 공간이 연속적으로 할당되어야 한다는 제약을 없앤 전략으로, 논리 메모리와 물리 메모리를 각각 다르게 관리
    - 논리 메모리는 고정크기의 페이지로, 물리 메모리는 고정크기의 프레임 블록으로 관리(페이지? 프레임블록?)
    - MMU(Memory Management Unit)의 재배치 레지스터 방식으로 CPU가 마치 프로세스가 연속된 메모리에 할당된 양 인식하도록함(재배치 레지스터 방식?)
- 세그멘테이션
    - 페이징 기법과 반대로, 논리 메모리와 물리 메모리를 같은 크기의 블록이 아닌, 서로 다른 크기의 논리적 단위인 세그먼트로 분할
- 세그멘테이션 & 페이징 혼용
    - 페이징과 세그멘테이션을 혼용해 서로 발생가능한 단편화를 줄여줌

**Comment by import-max** [comment]
### Swap

- 프로그래밍 환경에서 CPU 할당 시간이 끝난 프로세스의 메모리를 보조 기억장치(e.g. 하드디스크)로 내보내고 다른 프로세스에 메모리를 할당하여 교체할 수 있다. 이러한 기법을 스와핑이라 한다.
- 기존에 메모리에 올라간 프로세스를 보조 기억장치로 보내는 것을 swap-out, 보조 기억장치에 있던 프로세스를 메모리에 올리는 것을 swap-in이라고 한다.

### Compression

- 외부 단편화로 발생한 메모리 파편들을 해결하기 위한 방법
- 프로세스가 연속적으로 메모리 주소에 할당되도록 하여 단편화를 하는 것을 압축이라고 한다. 중간에 삭제하는 과정도 필요하다.

### Paging

- 메모리에 연속적으로 프로세스를 할당하는 것이 아니라, 페이지라는 단위를 활용하여 물리적으로 메모리를 나눠서 할당하는 것. 만약 페이지가 프로세스보다 크다면 내부 단편화 문제가 발생할 수 있다.

### Segmentation

- 메모리를 논리적 단위인 segmentation을 활용하여 분할하고 프로세스를 할당하는 것. 시작 물리주소인 base와 최대 크기인 limit로 구성되어 있다. 외부 단편화 문제가 발생할 수 있다.
