### ISSUE TITLE
인터프리터 언어란 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#53]

**Comment by import-max** [comment]
- 인터프리터는 원시코드 명령어를 한 줄씩 읽어 실행하는 프로그램을 의미한다. 고로, 인터프리터 언어는 소스코드를 바로 실행하는 언어로, 실행 전에 기계 레벨의 코드를 만드는 컴파일 언어와 다른 언어이다.
- 스크립트 언어라고도 하며 동일한 의미이다.

**Comment by jarammm** [comment]
**정의**
- 인터프리터(interpreter)란 소스 코드를 처음부터 한 라인씩 차례대로 해석하며 실행하는 프로그램이다.
- 코드가 완전히 작성되지 않아도 작성된 부분까지만을 테스트할 수 있습니다. 또한, 대화형 기능을 통해 사용자가 곧바로 코드를 수정할 수 있습니다.

**장점**
- 코드가 완전히 작성되지 않아도 작성된 부분까지만을 테스트할 수 있다.
- 프로그램 수정이 간단하다(한 줄 한줄 실행하며 수정 가능) → 컴파일러는 소스 코드를 번역해서 실행 파일을 만들기 때문에 프로그램에 수정 사항이 발생하면 소스 코드를 다시 컴파일해야 한다.
- 공동 작업과 유지 보수가 아주 쉽고 편해서 생산성이 높고 실사용률도 높다.
- 읽고 쓰기 쉽다.

**단점**
- 실행 시마다 소스 코드를 한 줄씩 기계어로 번역하는 방식이기 때문에 실행 속도는 컴파일 언어보다 느리다.

**Comment by miinkang** [comment]
****인터프리터 언어****
- Interpreter (해석기) : 소스코드를 바로 실행하는 컴퓨터 프로그램 또는 환령 
- 소스코드를 한 줄 씩 읽어들이면서 실행한다.
- Python, JavaScript, R 등 script언어
- 장점 
    - 소스코드를 기계어로 변환하지 않아 빌드 시간이 없다.
    - OS이식성이 좋다.
    - 디버깅이 쉽다.
- 단점
    - runtime에서는 한 줄씩 실시간으로 읽기 때문에 컴파일 언어에 비해 속도가 느리다.

****컴파일 언어 (compile language)****
- 소스코드를 목적코드로 옮긴다. 
- 소스파일 → 실행파일 (로 생성한다.)
- 컴파일(소스코드→목적코드, 기계어 번역) 과정과 실행 과정이 나눠져 있음 
- C, C++, Go 등
- 장점
    - 컴파일을 한번하면 실행파일을 생성해 실행 시 실행 속도가 빠르다.
- 단점 
    - 컴파일이 오래 걸릴 수 있다. 
    - OS이식성이 낮아 OS마다 적절한 컴파일러로 컴파일해야한다.
