### ISSUE TITLE
검정력(statistical power)은 무엇일까요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#54]

**Comment by kimyuuuuuu** [comment]
- 검정력은 대립가설 H1이 참인 경우 귀무가설 H0을 기각(대립가설 H1을 채택)할 확률이다. = 효과가 있는 경우 검정 해내는 힘을 뜻한다.
    - 대립가설 : 우리가 증명 또는 입증하고자 하는 가설, 효과와 차이가 있는 가설.
    - 귀무가설 : 우리가 증명하고자하는 가설의 반대되는 가설, 효과와 차이가 없는 가설.

**Comment by import-max** [comment]
검정력은 대립가설이 참인 경우 , 이를 사실로 결정하고 대립가설을 채택할 확률을 의미한다. 만약 검정력이 90%라고 하면, 대립가설이 사실임에도 불구하고 귀무가설을 채택할 확률은 10%이다.

**Comment by jarammm** [comment]
- **대립가설이 참일 때 귀무가설을 기각할 확률, 즉 대립가설을 채택할 확률**. 다시 말해 **내 연구가설이 맞을 때 연구가설을 맞다고 예측할 확률.**
- 따라서 검정력은 크면 클수록 좋다.
- 표본의 크기가 크면 클수록 모집단을 잘 표현할 수 있기 때문에 검정력 또한 커진다.

**Comment by miinkang** [comment]
- 대립가설이 참일 때 귀무가설을 기각하고 대립가설을 채택할 확률
- 검정력이 클수록 내 연구가설이 맞다고 예측할 확률이 큰 것

참고) 귀무가설 : 현재의 상태, 대립가설 : 현재의 상태에 반하여 주장하려는 상태 

- 제 2종 오류(β)가 거짓인 경우(1-β)
    - 제 2종 오류 : 귀무가설이 거짓인데 귀무가설을 채택한 경우
    - 제 1종 오류 : 귀무가설이 참인데 귀무가설을 기각한 경우
