### ISSUE TITLE
Test 세트가 오염되었다는 말의 뜻은?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#55]

**Comment by kimyuuuuuu** [comment]
- 트레이닝 세트로 잘 훈련된 모델에 새로운 데이터셋이 들어와도 잘 작동하는지를 확인해야하는데, 이 확인작업을 위해 집어넣는것이 테스트세트이다.
- train data가 test data와 흡사하거나 포함된 경우 테스트 세트가 오염되었다고 한다.
- 테스트 세트가 완전히 새로운 데이터 셋이 아니라면 튜닝된 모델의 설정은 일반화 성능을 왜곡시킬 것이다.

**Comment by import-max** [comment]
test 세트의 특성은 학습데이터와 다르면서 한 번도 학습된 적이 없는 데이터여야 한다. 하지만 너무 학습 데이터와 비슷하거나 학습된 이력이 있다고 하면 객관적인 데이터로 사용될 수 없다. 이러한 경우를 test 세트가 오염되었다고 한다.

**Comment by jarammm** [comment]
- test세트에 이미 모델이 학습한 train데이터 일부가 잘못 포함되었다는 의미이다. 그렇게 되면 테스트의 의미가 없어진다. 정확한 예측 성능을 확인할 수 없기 때문이다.
- test세트로는 모델이 한 번도 본 적 없는 데이터를 통해 예측을 함으로써 일반화 성능을 측정하는 것이므로, 모델이 학습한 적 있는 데이터가 test세트에 포함되었을 때 test세트가 오염되었다고 한다.

**Comment by miinkang** [comment]
- 모델은 test세트를 전혀 모르는 상태에서 test를 해야 모델의 범용 성능을 확인할 수 있다.
- 모델이 test세트에 대한 정보를 얻어 모델의 일반화 성능이 왜곡되는 경우를 test세트가 오염되었다고 한다.
