### ISSUE TITLE
찾은 해가 Global Minimum인지 아닌지 알 수 있는 방법은?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#56]

**Comment by import-max** [comment]
만약, local minima인 경우라면 convexity 를 만족하지 않는다. 모든 방향에서 아래로 볼록한 형태 (convex) 인 local minima를 발견한다면, 그 지점이 바로 global minima일 가능성이 높다.

**Comment by kimyuuuuuu** [comment]
- 딥러닝에서 다루는 문제가 convexity를 만족하지 않아서 global minima에 도달하는 것을 보장하지 않고, 알수도 없다. 하지만 local minima를 찾는다면, 그 지점이 곧 global minima일 가능성이 높다.

**Comment by miinkang** [comment]
- 알 수 없다.
- 딥러닝 문제는 non-convex할 가능성이 높음
- Local minima는 위로 볼록한 지점이 하나도 없는 경우이기 때문에 매우 낮은 에러를 갖고 global minimum과 비슷한 수준의 에러이다.
- 따라서 찾은 해가 global minimum인지 확신할 수 없어도 딥러닝의 성능에는 문제가 없다고 볼 수 있다.
