### ISSUE TITLE
다른 좋은 머신 러닝 대비, 오래된 기법인 나이브 베이즈(naive bayes)의 장점을 옹호해보세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#57]

**Comment by kimyuuuuuu** [comment]
- 나이브 베이즈
    - 데이터가 각 클래스에 속할 특징 확률을 계산하는 조건부 확률 기반의 분류 방법이다.
    - 
- 데이터에서 변수들에 대한 **조건부 독립을 가정**하는 알고리즘으로 클래스에 대한 사전 정보와 데이터로부터 추출된 정보를 결합하고, **베이즈 정리(Bayes Theorem)**를 이용하여 어떤 데이터가 특정 클래스에 속하는지 분류하는 알고리즘이다.
- 나이브 베이즈의 장점은 다음과 같다.
    - 단순하고 빠르며 매우 효과적이다
    - 잡음과 누락 데이터를 잘 처리해서 노이즈와 결측 데이터가 있어도 잘 수행한다
    - 훈련에 대한 상대적으로 적은 예제가 필요하지만 매우 많은 예제도 잘 수행한다
    - 예측에 대한 추정된 확률을 얻기 쉽다
    
- **나이브 베이즈의 단점**
    - 모든 특징이 동등하게 중요하고, 독립이라는 가정이 잘못된 경우가 자주 있다. (ex: 텍스트의 단어들, 일기예보를 할 때 습도와 같은 중요한 특징을 다른 특징과 동등하다 판단)
    - 수치 특징이 많은 데이터셋에는 이상적이지 않다.
    - 추정된 확률이 예측된 클래스보다 덜 신뢰할만하다.

**Comment by jarammm** [comment]
- 나이브 베이즈 정리란?
    - 모든 특징이 동등하게 중요하고 독립이라는 가정(나이브한 가정)하에 작동되는 알고리즘
    - 표본 정보와 사전 정보를 함께 사용해 모수 추정, 조건부확률을 이용해 정보 갱신
    - A라는 새 정보가 주어질 때 P(B)로부터 P(B|A)를 계산하는 방법을 제공한다.
    - 분류예측에 많이 쓰임. 스팸 메일 필터, 텍스트 분류, 감정 분석, 추천 시스템 등 광범위하게 쓰임.
- 나이브 베이즈 장점?
    - 간단하고 빠르며 효율적임
    - 노이즈 데이터, 아웃라이어를 잘 처리한다
    - 훈련 시 데이터 크기와 무관하게 잘 동작한다.
    - 예측을 위한 추정 확률을 쉽게 얻을 수 있다.
- 나이브 베이즈 단점?
    - 모든 특징이 동등하게 중요하고 독립이라는 가정(나이브한 가정)하에 작동되는 알고리즘인데 실제로는 그 가정이 성립하지 않는 경우가 많다
    - 수치 피쳐가 많은 데이터셋의 경우 성능이 좋지 않다
    - 추정 확률이 예측 클래스보다 신뢰도가 덜하다

**Comment by miinkang** [comment]
- 나이브 베이즈(Naive Bayes Classification)
    - 사용 : 스팸 메일 필터, 텍스트 분류, 감정분석, 추천 시스템 등 광범위한 활용 범위 
    - 지도학습의 일종(feature, label이 필요함)
    - 모든 feature는 서로 독립적이어야한다는 가정이 필요함 ( = naive)
     : 독립 사건이면 두 사건의 확률은 확률의 곱으로 표현되어 수식이 간단해진다.
    - 입력 feature가 클래스 전체의 확률 분포 대비 특정 클래스에 속할 확률을 베이즈 정리를 기반으로 계산한다.
- 머신러닝과 나이브 베이즈의 차이점
    - 머신러닝은 feature에 가중치를 부여해 학습한다.
    - 나이브 베이즈는 모든 feature가 동등한 값을 갖는다.
- 나이브 베이즈의 장점
    - 간단하고 빠른 계산이 가능해 효율적인
    - 데이터의 크기에 상관없이 잘 동작한다.
- 나이브 베이즈의 단점
    - 모든 데이터의 feature가 독립적인 사건이라는 가정이 잘못된 경우가 있다.

**Comment by import-max** [comment]
- 나이브 베이즈 기법은 분류를 위해 베이즈 이론을 사용하는 기법으로, 데이터의 특징이 상호 독립적이라는 가정 하에 데이터가 각 클래스에 속할 확률을 계산하는 분류 방법이다.
- 장점
    - 모든 속성을 동등하고 ‘독립적’이라고 가정하기 때문에 단순하고 연산이 빠르다.
    - 데이터 크기에 관련 없이 학습이 잘 된다.
    - 노이즈나 누락된 데이터를 잘 처리한다.
