### ISSUE TITLE
Weight Initialization 방법에 대해 말해주세요. 그리고 무엇을 많이 사용하나요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#58]

**Comment by kimyuuuuuu** [comment]
- weight initialization은 가중치 초기화이다.
- 딥러닝에서 가중치를 잘 초기화하는 것은 기울기 소실이나 local minima 등의 문제를 야기할 수 있기 때문에 중요하다.

- 초기화 방법
    - **LeCun Initialization**
        - 들어오는 노드 수에 대해 정규 분포와 균등 분포를 따르는 방법이 있다
    - **Xavier Initialization**
        - LeCun 방법과 비슷하지만 들어오는 노드 수와 나가는 노드 수에 의존하고, 적절한 상수값도 발견하여 사용한 방법
    - **He Initialization**
        - `ReLU`와 함께 많이 사용되는 방법으로, LeCun 방법과 같지만 상수를 다르게 하였다. 들어오는 노드만 고려

**Comment by jarammm** [comment]
- std = 0.01
    - 신경망에 아주 작은 데이터(매우 작은 값을 가지는 데이터 x의 분포가 큼)가 흐름 → 역전파 때 가중치의 기울기 역시 작아진단 의미
    - 기울기 소실 문제는 발생하지 않는다
    - 다만 활성화의 값들이 가운데로 치우치게 된다. 이는 표현력 관점에서 성능이 안좋다는 의미이다. 이렇게 된다면 뉴런을 여러 개 둔 의미가 사라진다는 것이다.
    - 각 층의 활성화값이 적당히 골고루 분포되어야 효율적인 신경망 값이 이뤄지기 때문에 **치우친 데이터가 흐르면 기울기 소실이나 표현력 제한 문제에 빠져 원활한 학습을 기대하기가 어렵다.**
- Xavier
    - 일반적인 딥러닝 프레임워크들이 표준적으로 이용중으로, 앞 계층의 노드가 n개, 다음 계층 노드가 m 개라면 표준편차가 $\sqrt{\frac{2}{n+m}}$인 분포를 사용한다.
    - 시그모이드 함수의 표현력도 제한받지 않고 대체로 학습이 효율적으로 이뤄진다.
    - 층이 깊어질수록 형태가 다수 일그러지는데 시그모이드 함수 대신 tanh(hyperbolic tangent)함수를 이용해 형태의 개선 가능
    - 하지만 층이 깊어지면서 활성화값들의 치우침이 조금씩 커지고, 학습할 때 기울기 소실 문제도 일으킴
    - **활성화 함수로 sigmoid, tanh 사용 → Xavier초깃값**
    - +) tanh 함수도 시그모이드와 같이 S자 곡선 함수이다. 다만 시그모이드 함수가 (0, 0.5)에서 대칭인 반면 tanh 함수는 원점에서 대칭이다. 활성화 함수로는 원점 대칭인 tanh 함수가 보다 바람직하다 알려졌다.
- He
    - ReLU 사용 시에는 이에 특화된 초깃값 사용이 권장된다. 그것이 바로 He 초깃값이다.
    - He 초깃값은 앞 계층의 노드가 n개일 때, 표준편차가 $\sqrt \frac{2}{n}$인 정규분포를 사용한다. Xavier초깃값보다 조금 커진 것이다. ReLU는 음의 영역이 모두 0이라서, 보다 넓게 분포시키기 위해 보다 큰 계수가 필요하다고 직관적으로 해석할 수 있다.
    - 층이 깊어져도 분포가 균일하게 유지, 역전파 때도 적절한 값이 나올 것으로 기대
    - 활성화 함수로 ReLU 사용 → He 초깃값
    - 활성화 함수로 ReLU를 사용할 때 Xavier초깃값을 사용해도 학습이 잘 이루어지나, **He초깃값이 더 빨리 학습이 이뤄진다.**

**Comment by import-max** [comment]
1. Weight Initialization 방법에 대해 말해주세요. 그리고 무엇을 많이 사용하나요?
- `Lecun Initialization`
    - input 노드 수에 대해 정규분포와 균등분포를 따른다.
        - 정규분포
            
            $W \sim N(0,Var(W)), \quad Var(W) = \sqrt {\frac{1}{n_{in}}}$
            
        - 균등분포
            
            $W \sim U(-\sqrt {\frac{1}{n_{in}}},+\sqrt {\frac{1}{n_{in}}})$
            
- `Xavier Initialization`
    - input 노드 수와 output 노드 수에 의존하고, 적절한 상수값도 발견하여 사용한다.
        - 정규분포
            
            $W \sim N(0,Var(W)), \quad Var(W) = \sqrt {\frac{2}{n_{in}+n_{out}}}$
            
        - 균등분포
            
            $W \sim U(-\sqrt {\frac{6}{n_{in}+n_{out}}},+\sqrt {\frac{6}{n_{in}+n_{out}}})$
            

- `He Initialization`
    - `ReLU` 와 함께 많이 사용되는 방법으로, `Lecun Initialization` 방법과 같지만 상수를 다르게 함. input 노드만 고려함.
        - 정규분포
            
            $W \sim N(0,Var(W)), \quad Var(W) = \sqrt {\frac{2}{n_{in}}}$
            
        - 균등분포
            
            $W \sim U(-\sqrt {\frac{6}{n_{in}}},+\sqrt {\frac{6}{n_{in}}})$
