### ISSUE TITLE
차원의 저주에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#6]
2회차 - 2022년 8월 26일 금요일

**Comment by kimyuuuuuu** [comment]
- 차원의 저주란?
    - 차원의 저주란 수학적 공간의 차원(변수의 갯수)가 늘어나면서 문제 계산법이 지수적으로 늘어나는 상황.
    - 차원이 높아질수록 데이터 사이의 거리가 멀어지고, 빈공간이 증가하는 공간의 성김현상을 보이게 된다.
    - Feature가 많아질수록, 동일한 데이터를 설명하는 빈공간이 증가한다.
    
    ⇒ 차원의 저주로 인해, 모델링 과정에서 저장공간과 처리시간이 불필요하게 증가하여 성능이 저하된다. 
    

- 차원의 저주를 피하는 방법.
    - 차원을 낮추고자 한다. (고차원 → 저차원)
    - PCA
        - 주성분 분석.
        - 원데이터의 분포를 최대한 보존하면서 고차원 공간의 데이터들을 저차원 공간으로 변환.
        - 기존의 변수를 조합하여 서로 연관성이 없는 새로운 변수(=주성분) 생성
        
    - LDA
        - 선형판별분석. 지도학습의 분류에서 사용된다.

**Comment by miinkang** [comment]
- 데이터를 학습한다는 것은 데이터가 갖고 있는 특징을 학습하는 것입니다. n개의 특징 변수(feature)는 n차원 특징 공간을 갖습니다. 차원의 저주란 차원이 증가하면서 학습 데이터의 수가 차원 수보다 적어져 성능이 저하되는 현상을 말합니다. 차원이 크면 데이터가 차지하는 공간이 작하지고 데이터 간의 거리가 멀어집니다. 빈 공간이 많아지기 때문에 모델의 성능이 저하됩니다. 

- 차원의 저주를 해결하기 위해서 학습 데이터의 수를 증가시키는 방법이 있지만 이는 한계가 있기 때문에 차원을 축소하거나 feature selection 혹은 feature extraction을 사용합니다.

**Comment by import-max** [comment]
데이터의 차원이 증가할수록 공간의 크기가 기하급수적으로 증가하여, 데이터 간 거리가 기하급수적으로 멀어지는 현상을 이야기한다. 
PCA, LDA, LLE, MDS 등의 차원 축소 알고리즘으로 차원 문제를 어느정도 해결할 수 있다.
