### ISSUE TITLE
위상 정렬(Topological Sort)이란 무엇인가요?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#61]

**Comment by kimyuuuuuu** [comment]
- 위상 정렬은 순서가 정해져 있는 작업을 차례로 수행해야 할때 그 순서를 결정해 주기 위한 알고리즘.
- **방향 그래프**의 모든 노드를 선행 순서를 지키며 정점을 순서대로 나열하는 것

- 위상정렬은 DAG에만 적용이 가능하다. DAG는 사이클이 발생하지 않는 방향 그래프이다. 
즉, 사이클이 발생하는 경우 위상정렬을 수행할 수 없다.

- 위상 정렬 알고리즘
    - 진입차수가 0인 노드를 큐에 넣는다.
    - 큐가 빌 때가지 다음을 반복한다.큐에서 요소를 꺼내 해당 노드에서 출발하는 간선을 그래프에서 제거한다. 새롭게 진입차수가 0이 된 노드를 큐에 넣는다.

- https://m.blog.naver.com/ndb796/221236874984

**Comment by import-max** [comment]
- 위상정렬이란 방향 그래프의 모든 노드를 선행 순서를 지키며 순서대로 정점을 나열하는 것이다.
- 쉽게 말하면, 어떤 일을 하는 순서를 찾는 알고리즘이다.

**Comment by import-max** [comment]
위상정렬이란 방향 그래프의 모든 노드를 선행 순서를 지키며 순서대로 정점을 나열하는 것이다.
쉽게 말하면, 어떤 일을 하는 순서를 찾는 알고리즘이다.

**Comment by import-max** [comment]
- 위상정렬이란 방향 그래프의 모든 노드를 선행 순서를 지키며 순서대로 정점을 나열하는 것이다.
- 쉽게 말하면, 어떤 일을 하는 순서를 찾는 알고리즘이다.
