### ISSUE TITLE
평균(mean)과 중앙값(median)중에 어떤 케이스에서 뭐를 써야할까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#62]

**Comment by jarammm** [comment]
- 평균
    - 데이터의 평균적인 수치를 확인할 때 사용
    - 아웃라이어에 민감하므로 데이터의 분포가 균일하거나, 아웃라이어가 크지 않을 때 사용할 수 있음
- 중앙값
    - 가장 가운데에 위치한 수치로, 아웃라이어가 있어도 평균만큼 민감하지 않음
    - 강건한(robust)한 대푯값이라 함

**Comment by kimyuuuuuu** [comment]
- `평균(mean)`: 모든 관측값의 합을 자료의 개수로 나눈 것
- `중앙값(median)`: 전체 관측값을 크기 순서로 배열했을 때 가운데 위치하는 값

- 평균 근처에 표본이 몰려 있는 상황에서 대표값으로 유용하지만 극단적인 값에 영향
- 중앙값은 관측값들의 변화에 민감하지 않고 특히 아주 큰 관측값이나 아주 작은 관측값(즉, outlier)에 영향을 받지 않는다. 중앙값이 유용한 경우는 표본의 편차, 혹은 왜곡이 심하게 나타나는 경우이다.

**Comment by import-max** [comment]
- `평균`이란 모든 관측값의 합을 자료의 개수로 나눈 것이고, `중앙값`이란 전체 관측값을 크기대로 배열했을 때 가운데 위치하는 값이다.
- 평균은 전체 관측값이 골고루 반영되지만 극단적인 값에 영향을 많이 받는다. 표본이 몰린 상황에서 대표값으로 유용하다.
- 중앙값은 가운데 위치하는 값 이외의 크기는 중요하지 않고, 극단적인 값에 영향을 받지 않는다. 표본의 편차가 큰 경우에 중앙값이 유용하다.
