### ISSUE TITLE
 스케줄러가 무엇이고, 단기/중기/장기로 나누는 기준에 대해 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#63]

**Comment by kimyuuuuuu** [comment]
- 시스템 내의 여러 프로세스 중에, 자원을 할당하는 프로세스를 스케줄러라고 한다.
- 스케줄러의 목적 : 시스템 성능 향상.
    - 응답시간: 작업 요청으로부터 응답을 받을 때까지의 시간
    - 작업 처리량: 단위 시간 동안 완료된 작업의 수
    - 자원 활용도 : 주어진 시간동안 자원이 활용된 시간
- 발생 빈도와 할당 자원에 따라 장기/중기/단기 스케줄러
    - 장기 스케줄러
        - Job Scheduling(Job → created)
        - 시스템 내에 프로세스 수를 조절
        - CPU든 I/O든 모두 써서 효율성을 높이기 위해서 I/O bounded와 compute-bounded 프로세스들을 잘 섞어서 선택해야 한다.
    - 중기 스케줄러
        - 메모리 할당을 결정하는 Memory Allocation(suspended ready → ready)
    - 단기 스케줄러
        - 프로세서를 할당 받을 프로세스를 결정하는 Process Scheduling(ready → running)

**Comment by jarammm** [comment]
- OS에서 자원을 할당하는 것이 스케줄러의 일
- 스케줄러는 발생하는 빈도와 할당하는 자원에 따라 **장기/중기/단기 스케줄러**로 나뉨
    - 장기스케줄러
        - 시스템에 제출할 작업을 결정하는 잡스케줄링에 사용
        - 시스템 내에 프로세스 수를 조절
    - 중기스케줄러
        - 메모리 할당
    - 단기스케줄러
        - 프로세서를 할당 받을 프로세스를 결정함 → 가장 빈번하게 발생하므로 매우 빨라야 함

**Comment by import-max** [comment]
- 시공간적 자원을 할당할 프로세스를 선택하는 역할을 하는 것이 스케줄러이다. 시스템 성능 향상이 목표이기 때문에, 목적에 따라 다양한 성능 지표를 고려한다.
- `단기 스케줄러`는 프로세서를 할당 받을 프로세스를 결정하는 process scheduling에서 사용하며, 사용 빈도가 높으므로 속도가 빨라야 한다.
- `중기 스케줄러`는 메모리 할당을 결정하는 memory allocation 에서 사용한다.
- `장기 스케줄러`는 시스템 내의 프로세스 수를 조절하며, 모두 사용하여 효율성을 높이는 것이 중요하다. 시스템에 제출할 작업을 결정하는 job scheduling 에서 사용한다.
