### ISSUE TITLE
스팸 필터에 Logistic Regression을 많이 사용하는 이유는 무엇일까요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#64]

**Comment by jarammm** [comment]
- linear regression(선형 회귀)에 sigmoid함수(=logistic function)를 적용한 것이 logistic regression(로지스틱 회귀)
- 스팸 필터는 스팸이다, 아니다의 이진 분류이므로 선형 회귀로 문제 풀이 시, 1에 가까운 값은 1로 분류하고, 0에 가까운 값은 0으로 분류하게 됨 → 선형 회귀식을 보면 데이터 값에 매우 민감하여 결과값이 0과 1사이로만 맵핑되기가 어려움 → 이에 시그모이드 함수, 즉 로지스틱 함수를 적용해 모든 결과값을 0과 1사이로 맵핑시키면서도 각 값들이 스무스하게 분포하도록 유도, 데이터에 강건한 모델링 가능케 함

**Comment by kimyuuuuuu** [comment]
- 스팸 필터
    - 메일이 스팸 메일인지 아닌지에 대한 확률을 계산하여, 메일을 **분류(Classification)**하는 문제
- 로지스틱 회귀
    - 회귀를 바탕으로 데이터가 어떤 범주에 속할 확률을 0과 1 사이의 값으로 예측하고 그 확률에 따라 가능성이 더 높은 범주에 속하는 것으로 분류(Classification)해주는 지도 학습 알고리즘
    - **입력값이 아무리 크거나 작아도 0에서 1 사이의 값으로 맵핑**시킨다는 점에서 분류문제에 적합

**Comment by import-max** [comment]
- Logistic Regression 은 지도 학습을 활용한 분류 알고리즘으로, 분류하는 task에서는 로지스틱 회귀가 많이 사용된다.
- 시그모이드 함수(sigmoid)를 통해 선형 함수를 0과 1 사이의 함수로 바꾸며, 항상 0-1 사이의 값을 반환한다.
- 선형회귀 함수는 입력값에 따라 0과 1사이의 범위를 벗어나기도 하기 때문에 분류 문제에 적합하지 않다.
