### ISSUE TITLE
PCA는 차원 축소 기법이면서, 데이터 압축 기법이기도 하고, 노이즈 제거기법이기도 합니다. 왜 그런지 설명해주실 수 있나요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#65]

**Comment by jarammm** [comment]
1. pca는 고차원의 데이터를 더 낮은 차원의 데이터로 변환시키는 기법입니다.
2. 차원을 축소하는 과정에서 덜 중요한 피쳐들은 빠지는데 이것이 데이터 압축과 같습니다
3. 또한 전체 데이터셋을 잘 설명하는 데이터만 남기는 과정과도 상통하기에 노이즈 제거기법이 되기도 합니다.

**Comment by import-max** [comment]
* 공분산 행렬 기반으로 분산의 크기가 가장 큰 것부터 벡터를 추출하는데, 이 벡터가 가장 데이터를 잘 설명하기 때문에 차원축소 기법임과 동시에 노이즈 제거 및 데이터 압축기법이다.

**Comment by kimyuuuuuu** [comment]
- PCA(Principle Component Analysis)는 입력 데이터의 공분산 행렬을 기반으로 고유벡터를 생성하고 이렇게 구한 고유 벡터에 입력 데이터를 선형 변환하여 차원을 축소하는 방법

- PCA는 고유값이 가장 큰, 즉 데이터의 분산이 가장 큰 순으로 주성분 벡터를 추출하는데, 가장 나중에 뽑힌 벡터보다 가장 먼저 뽑힌 벡터가 데이터를 더 잘 설명할 수 있기 때문에 노이즈 제거 기법
