### ISSUE TITLE
파이썬에서 난수를 생성하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#66]

**Comment by import-max** [comment]
- `random()` 모듈을 사용하여 생성이 가능하다. 보통 `randint()`, `randrange()`, `random()` 등을 보통 많이 사용한다.

**Comment by jarammm** [comment]
- random(), randint(최소, 최대), uniform(최소, 최대), randrange(시작, 끝, 간격), shuffle(컬렉션), choice(컬렉션), choices(컬렉션), sample(컬렉션, 샘플 수)
