### ISSUE TITLE
b+ tree

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#67]

**Comment by kimyuuuuuu** [comment]
- 이진트리란 자식노드가 최대 두 개인 노드들로 구성된 트리
- 이진 트리(Binary Tree)를 확장해 모든 리프 노드들이 **같은 높이**를 갖도록 하는 트리이다. 정렬된 순서를 보장.
- 노드 내에 **여러 개의 key**가 있을 수 있으며, 최대 key의 개수에 따라 N개면 N차 B-트리라고 부른다. 
- 루트노드에서 시작하여 **하향식으로 검색**

- B-트리 vs B+ 트리
    - B+ 트리는 B-트리와 비슷하지만 **리프노드가 연결리스트**의 형태를 띄어 **선형 검색이 가능한** 트리이다.

**Comment by import-max** [comment]
- Tree 자료구조 중 하나로, 인덱스를 통해 데이터를 표현하는 동적 자료구조이다.
- 모든 key, data가 리프노드에 모여있으며 이 리프노트는 연결리스트의 형태를 가지고 있다.

**Comment by jarammm** [comment]
- B트리는 이진트리에서 발전되어 **모든 리프노드들이 같은 레벨을 가질 수 있도록** 자동으로 벨런스를 맞추는 트리입니다. 또한 정렬된 순서를 보장하고, 멀티레벨 인덱싱을 통한 빠른 검색을 할 수 있기 때문에 DB에서 사용하는 자료구조 중 한 종류라고 합니다.
- 3 way-탐색트리일 때
    - 2 <= 루트 노드의 서브트리 개수 <= m
    - [m/2] <= 루트를 제외한 노드의 서브트리 개수 <= m
    - [m/2] - 1 <= 루트를 제외한 노드의 키 개수 <= m-1
    - 모든 리프노드는 같은 레벨에 존재
- 검색 과정 : 루트노드에서 시작하여 **하향식으로 검색**
- key를 삽입하기 위해서는 **1. 요소 삽입에 적절한 리프 노드를 검색**하고, **2. 필요한 경우 노드를 분할**해야 합니다. 리프노드 검색은 하향식이지만 노드 분할의 과정은 **상향식**으로 이루어진다고 볼 수 있습니다.


참고 : [https://velog.io/@emplam27/자료구조-그림으로-알아보는-B-Tree](https://velog.io/@emplam27/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EC%95%8C%EC%95%84%EB%B3%B4%EB%8A%94-B-Tree)
