### ISSUE TITLE
노트북으로 `www.google.com`에 접속을 했습니다. 요청을 보내고 받기까지의 과정을 자세히 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#69]

**Comment by kimyuuuuuu** [comment]
**1단계**

웹 사이트에 접속하기 위해서는 **노트북의 IP주소, 1-hop 라우터의 IP 주소, DNS 서버 주소**가 필요하다. 이를 알아 내기 위해 DHCP query가 담긴 IP 데이터그램을 1-hop 라우터에게 전송한다. DHCP 서버가 내장된 라우터가 노트북의 IP주소, 자신의 IP주소, DNS 서버의 IP주소를 담은 DHCP ACK를 다시 노트북에게 전송한다.

DNS란 **D**omain **N**ame **S**ystem의 약자로 `www.google.com`과 같은 도메인 주소를 IP 주소로 바꿔주는 시스템을 말한다.

DHCP 서버는 보통은 라우터에 DHCP 서버가 내장되어 있으며 DHCP 서버에 연결된 클라이언트에게 자동적으로 IP주소를 할당한다. 

**2단계**

DNS 서버에 DNS query를 보내기 전에 **1-hop 라우터의 MAC 주소**가 필요하므로 ARP query를 브로드캐스트 방식으로 전송하여 router의 MAC주소를 알아낸다.

ARP는 MAC 주소와 IP 주소를 1:1 매핑하기 위해 사용된다.

**3단계**

`www.google.com`에 요청을 보내기 위해서는 `www.google.com`의 IP주소가 필요하므로, DNS query가 담긴 IP 데이터그램을 DNS 서버에 전송하고 `www.google.com`의 IP 주소를 클라이언트인 노트북에게 전송한다.

**4단계**

TCP 소켓을 생성하고 3-way handshake로 연결을 생성한다. HTTP 요청을 보내고 응답을 받아 브라우저에 렌더링을 하면 Google 웹페이지를 브라우저에서 확인할 수 있다.

**Comment by miinkang** [comment]
1. 사용자가 웹브라우저 검색창에 www.google.com을 입력한다.
2. 웹 브라우저는 캐싱된 DNS기록들을 통해 해당 도메인 주소와 대응하는 IP주소를 확인한다.
3. 웹 브라우저가 HTTP를 사용해서 DNS에 입력된 도메인 주소를 요청한다.
4. DNS가 웹브라우저에게 찾는 사이트의 IP주소를 응답한다. 
5. 웹브라우저가 웹서버에게 IP주소를 이용해서 html문서 요청
6. 웹어플리케이션서버와 데이터베이스에서 우선 웹페이지 작업을 처리한다. 
7. 작업처리 결과를 웹서버로 전송
8. 웹서버는 웹브라우저에게 html문서 결과를 응답 
9. 웹브라우저가 웹페이지 내용물을 출력한다.
