### ISSUE TITLE
Stack 의 자료구조에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#7]
2회차 - 2022년 8월 26일 금요일

**Comment by jarammm** [comment]
1. LIFO(last in first out)인 구조로, heap(FIFO, first in fist out)과 상반되는 자료구조임
2. push하면 원소가 스택의 가장 뒤쪽에 쌓이고, pop하면 가장 최근에 push되었던 원소가 튀어나옴

**Comment by kimyuuuuuu** [comment]
- LIFO ( Last In First Out) 구조의 자료형. 한쪽으로만 데이터를 넣고 뺄 수 있다.
- 뒤로가기, 되돌리기 등에서 사용된다.
- stack에 더 넣을 곳이 없는데 push()를 하게 되면 overflow, 데이터가 없는데 pop()을 하게 되면 underflow

**Comment by miinkang** [comment]
- Last In First Out(후입선출) 데이터 관리 방식을 따르며 한 쪽 끝에서만 자료를 넣거나 뺄 수 있는 데이터를 제한적으로 접근할 수 있는 구조입니다.
- 구조가 단순하며 구현이 쉽고, 데이터를 저장하고 읽는 속도가 빠른 장점이 있습니다. 단 데이터 최대 갯수를 미리 정해야하고, 미리 최대 갯수만큼의 저장 공간을 확보해야하기 때문에 저장 공간의 낭비가 발생할 수 있습니다.  
- 대표적으로 브라우저의 뒤로 가기, 앞으로 가기 기능을 구현할 때 사용됩니다.

**Comment by import-max** [comment]
- `push` 로 넣고 `pop` 으로 뺄 수 있는데, 한 쪽으로만 데이터 입출력이 가능하기 때문에 가장 마지막에 들어간 것이 가장 먼저 나오는 LIFO(Last In First Out) 구조이다. 만약 공간이 더 없을 때 데이터를 `push` 한다면 `overflow`, 데이터가 없을 때 `pop` 한다면 `underflow` 라고 부른다.
- 브라우저의 뒤로가기/ 되돌리기 기능, stack memory 등에 사용되며 DFS 알고리즘 등에 사용된다.
