### ISSUE TITLE
멀티 프로세스 대신 멀티 스레드를 사용하는 이유를 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#70]

**Comment by kimyuuuuuu** [comment]
- **멀티 프로세스** : 하나의 운영체제 안에서 여러 프로세스가 동시에 실행되는 것
- **멀티 스레드** : 하나의 프로세스 안에서 여러 스레드를 사용하여 동시에 처리하는 것

1. **메모리 측면** : 자원을 효율적으로 사용하기 위해
    
    멀티 프로세스의 경우 프로세스를 생성하여 자원을 할당하는 시스템 콜을 할 때마다 오버헤드가 크지만, 멀티 스레드는 메모리 영역을 공유하기 때문에 시스템 자원을 효율적으로 사용할 수 있다.
    
2. **속도 측면** : Context-Switching 비용을 줄이고 응답 속도를 빠르게 하기 위해메모리 영역을 공유하기 때문에 Context-Switching과 스레드 간의 통신 시 Stack 영역만 처리하기에 통신 비용이 적고 응답속도가 빠르다.

**Comment by miinkang** [comment]
프로세스 : 운영체제로부터 자원을 할당받는 작업의 단위

스레드 : 프로세스가 할당받은 자원을 이용하는 실행의 단위

- 멀티 스레드가 더 적은 메모리 공간을 차지함
- 자원 효율성이 증가한다.
- stack영역을 제외한 모든 메모리를 공유하기 때문에 통신 비용, 부담이 줄어든다.
- context switching을 할 때 전환 속도가 프로세스간의 전환 속도보다 빠르다.
- 단점
    - 하나의 스레드 장애로 전체 스레드가 종료될 위험이 있음
