### ISSUE TITLE
아웃라이어의 판단하는 기준은 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#73]

**Comment by jarammm** [comment]
1. IQR(InterQuartile Range, *qaurtile : 사분위수)
    1. 보통 IQR을 기준으로 판단
        1. 데이터를 오름차순으로 정렬하고 25%, 50%, 75%, 100%로 4등분을 했을 때 각 지점을  Q1부터 Q4라고 이름
        2. 그리고 Q1과 Q3 사이의 범위를 IQR(=Q3-Q1)이라고 한다. 이 IQR에 1.5를 곱한 값을 Q3 지점의 값에 더하여 최대값을, Q1 지점의 값에서 빼서 최소값을 계산
        3. 최대값보다 크거나, 최소값보다 작을 때 이상치라고 판단
    2. 데이터 불균형일 때, 데이터가 많은 쪽에 대해 이상치가 존재하는 샘플들을 제거하면 예측 성능이 올라가는 효과를 기대할 수 있음
2. Z-Score
    1. Z-score는 데이터를 표준정규분포로 변환한 후의 개별 값들이다.
    2. 데이터가 평균에서 얼마나 떨어져 있는지를 나타내는 지표로, **임계값**을 설정하여 Z-score이 이 값보다 크다면 이상치로 판단한다.

**Comment by import-max** [comment]
- IQR 기법과 Z-score 방식이 있다.
- IQR 기법은 데이터를 오름차순 정렬해서 25%마다의 간격으로 나눈다. 25%지점과 75% 지점의 차이에 1.5배를 한 뒤, 75% 지점의 값에 더하여 최대값으로 간주하고, 25% 지점의 값에서 빼서 최소값으로 간주한다. 이 최소값과 최대값의 범위 밖의 값들을 아웃라이어라고 한다.
- Z-score는 데이터가 평균에서 얼마나 떨어져 있는지를 나타내는 지표로, 임계값을 설정하여 Z-score이 이 값보다 크다면 이상치로 판단한다.

**Comment by kimyuuuuuu** [comment]
- **이상치(outlier) :** 전체 데이터의 패턴에서 벗어난 이상한 값을 가진 데이터
- 이상치를 판단하는 방법
    - IQR
        - IQR 기법을 사용하기 위해서는 우선 데이터를 오름차순으로 정렬하고 25%, 50%, 75%, 100%로 4등분을 한다. 이 75% 지점과 25% 지점의 값의 차이를 IQR이라고 한다.
        
    - Z-score
        - 관측치가 평균에서 벗어난 표준 편차의 수를 나타낸다.
        - 포인트 그룹의 평균 및 표준 편차와의 관계 측면에서 데이터 포인트를 설명하는 방법이라고 볼 수 있다.
        - 데이터가 평균에서 얼마나 떨어져 있는지를 나타내는 지표로, 임계값을 설정하여 Z-score이 이 값보다 크다면 이상치로 판단
        - Z-score 방식은 데이터가 가우시안 분포를 따른다고 가정하기 때문에 데이터가 가우시안 분포가 아닐 경우 별도의 변환이 필요하다.
