### ISSUE TITLE
lambda 함수란 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#76]

**Comment by jarammm** [comment]
1. 정의 : 람다 표현식은 식 형태로 되어 있다고 해서 람다 표현식(lambda expression)이라 함
2. 함수를 간편하게 작성할 수 있어서 다른 함수의 인수로 넣을 때 주로 사용하며 익명 함수임
3. def 를 사용하여 함수를 만들지 않아도 되니 간편하고, 일회성이라 한 번만 쓰이고, 다음 줄로 넘어가면 힙(heap) 메모리 영역에서 증발하여 메모리 절약

**Comment by miinkang** [comment]
- 익명함수를 지칭하는 용어
- 이름이 없는 한 줄 이하의 작고 제한된 기능의 함수
- 한 번 쓰이고 다음 라인으로 넘어가면 힙 메모리 영역에서 제거된다.
- 파이썬에서는 map, reduce, filter등의 함수에서 주로 쓰인다.

**Comment by import-max** [comment]
- 이름이 없는 익명함수를 람다함수라고 한다. `lambda 인자 : 표현식`의 형식으로 표현할 수 있다.
- 일반 함수를 가볍게 만든 함수이기 때문에, 결과를 return 키워드 없이 자동으로 return한다. 람다함수를 사용하면 코드가 간결하고 메모리가 절약된다.

**Comment by kimyuuuuuu** [comment]
- 익명 함수(이름이 없는 함수)
- `def`키워드를 통해서 함수를 생성하는 리터럴 표기법을 **딱 한 줄의 코드로 표현**할 수 있게 해주며, `lambda 인자 : 표현식`의 형식으로 표현
- 람다함수는 결과 부분을 return 키워드 없이 자동으로 return한다
- 함수에 이름이 없고, 저장된 변수가 없기 때문에 다시 사용하기 위해서는 다시 코드를 적어주거나, 람다함수를 변수에 담아주어야한다.
