### ISSUE TITLE
통계에서 사용되는 bootstrap의 의미는 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#77]

**Comment by import-max** [comment]
* 가설검증을 하거나 평가지표를 계산하기 전에 random sampling을 적용하는 방법이다.  랜덤 샘플링을 통해 학습 데이터를 늘리는 방법이나 여러 모델을 학습시켜 추론 결과의 평균을 사용하는 방법(앙상블)의 의미를 지닌다.

**Comment by kimyuuuuuu** [comment]
- 모수의 분포를 추정하는 파워풀한 방법은 현재 있는 표본에서 추가적으로 표본을 복원 추출하고 각 표본에 대한 통계량을 다시 계산하는 것입니다.
- 가설검증을 하거나 metric을 계산하기 전에 random sampling을 적용하는 방법
- 여러번의 무작위 추출을 통해, 평균의 신뢰구간을 구할 수 있다.

**Comment by jarammm** [comment]
- 표본에 대한 신뢰도를 높이는 목적으로, 추가적으로 표본을 N번 복원추출하는 것을 말하고, 각 랜덤 샘플링 시 데이터는 중복될 수 있다.
- 단일 표본이 모집단을 대표하기는 어려우므로 데이터 증강을 통해 데이터 분포를 보다 고르게 하여 한계를 극복하려는 것이다.
- 부트스트랩된 데이터셋을 통해 새로운 통계량에 대한 표준오차 및 신뢰구간을 구할 수 있다.

**Comment by miinkang** [comment]
- 가설 검증을 하거나 metric을 계산하기 전에 random sampling을 적용하는 방법
- 기존의 표본이 200개라면 200개를 이용해 Random한 데이터셋을 b개 생성해 새로운 통계량을 구한다. → data augmentation의 효과가 있음

사용예시

- estimator의 분산을 직접 구하기 힘들 때 사용한다.
- estimator의 신뢰구간을 직접 구하기 힘들 때 사용한다.
- predictor 성능을 높일 때 사용할 수 있다.
    - b개의 classifier, b개의 prediction이 생성되기 때문에 ensemble 접근이 가능함
