### ISSUE TITLE
Bias는 왜 있는걸까?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#79]

**Comment by import-max** [comment]
- 하나의 뉴런으로 입력된 모든 값을 다 더한 다음에 이 값에 더 해주는 상수인데, 이 값은 하나의 뉴런에서 활성화 함수를 거쳐 최종적으로 출력되는 값을 조절하는 역할을 한다.
- 쉽게 말해 타겟과 예측값이 얼마나 멀리 떨어져 있는가를 의미한다.

**Comment by miinkang** [comment]
편향

- 편향을 더해줌으로써 활성화함수가 위치를 이동할 수 있다.
- 가중치는 비중을 다르게 두는 역할이라면 bias는 어떤 성향을 더해주는 것이라고 할 수 있다.
- 최종 출력값을 조절함

**Comment by jarammm** [comment]
- 편향(bias)은 하나의 뉴런에서 활성화 함수를 거쳐 최종적으로 출력되는 값을 조절하는 역할
- 데이터를 더 잘 나타내기 위해서 필요
(방향성, 형태를 잡아주는 것이 가중치라면, 편향은 보다 정확한 절대적 위치, 값을 찾도록 하는 느낌)

**Comment by kimyuuuuuu** [comment]
편향(bias)는 활성화 함수를 움직임으로써 데이터에 더 잘 맞도록 한다.
모델이 데이터에 잘 fitting하게 하기 위하여 평행 이동하는 역할
