### ISSUE TITLE
__init__ 메서드에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#8]
2회차 - 2022년 8월 26일 금요일

**Comment by kimyuuuuuu** [comment]
- __init__은 파이썬의 약속된 메서드로 초기화 메서드 혹은 생성자이다.
- 클래스의 새 객체/인스턴스가 생성될때 자동으로 호출된다.
- 객체가 갖게될 기본성질을 불러온다.

**Comment by miinkang** [comment]
- 인스턴스(객체)가 생성될 때마다 실행되며 인스턴스를 초기화합니다.
- 클래스 안에서만 사용됩니다.
