### ISSUE TITLE
break, continue and pass 는 어떻게 작동하나요?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#80]

**Comment by kimyuuuuuu** [comment]
1. pass : 실행할 코드가 없는 것으로 다음 행동을 계속해서 진행합니다.
2. continue : 바로 다음 순번의 loop를 수행합니다.
3. break : 반복문을 멈추고 loop 밖으로 나가도록합니다.

**Comment by miinkang** [comment]
break

- for, while문에서 탈출한다.

continue

- 해당 iteration을 건너뛴다.

pass 

- 아무것도 하지 않게 하고 싶을 때 사용한다.
- 함수, 클래스의 구조를 세울 때 사용한다.

**Comment by import-max** [comment]
- `break`는 특정 반복문(for, while) 을 멈추고 루프에서 빠져나가도록 한다. 한 번만 빠져나오게 되기 때문에 이중 반복문이라면 다음엔 반복이 되기 때문에 또 루프에 들어갈 수 있다. 이럴 경우에 (try-catch 를 통해 빠져나올 수 있다.)
- `continue`는 다음 루프를 수행하는 커맨드로, 이번 이터레이션(iteration)을 건너뛰고 다음 이터레이션을 이어나가도록 한다.
- `pass`는 실행할 코드가 없다는 것을 의미한다. 문법적으로 필요할 때 사용한다. 주로 함수나 클래스의 구조부터 세우고 나중에 구현을 하고 싶을 때 사용한다.

**Comment by jarammm** [comment]
- break
    - break는 반복문에서 사용 시, 하나의 반복문을 빠져나가도록 하는 키워드이다.
    - 중첩 반복문 break
        - 자바의 경우 각 loop에 라벨링을 하여 중첩 반복문을 한 번에 빠져나올 수 있지만 파이썬에는 그런 기능이 없다. 대신 try-except문을 통해 에러를 발생시키거나, return 키워드를 사용하여 한번에 빠져나올 수 있다.
- continue
    - 반복문 내에서 continue를 만나면 이후 코드를 실행하지 않고 다음 순번의 loop를 실행한다
- pass
    - 아무것도 실행하지 않을 때 사용하는 키워드
    - 추상 클래스, 추상 메서드, 아무 기능이 없는 함수를 생성 시 에러(`SyntaxError`) 빌생을 미연에 방지하기 위해 사용
