### ISSUE TITLE
pep 8은 무엇인가요?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#82]

**Comment by import-max** [comment]
- python enhance proposal의 약자로, 파이썬 코드 포맷 방법을 지정하는 규칙 집합이다. 코드를 어떻게 구성할 지 알려주는 스타일 가이드로서의 역할을 한다.
- 파이썬 창시자인 귀도 반 로섬이 파이썬의 특성을 고려하여 작성한 것으로, 이를 사용하는 것의 장점은 검색 효율성과 코드의 구조화로 인한 일관성 등이 있다.

**Comment by jarammm** [comment]
- Python Enhance Proposal(파이썬 개선 제안서)
- 8이라는 숫자는 버전이 아니라, 토픽에 따라 인덱싱한 것
- 파이썬 개선 제안서, 파이썬 코드를 어떻게 구상할 지 알려주는 스타일 가이드.
    - 다른 사람과 원활하게 협업하려면 공통된 스타일 공유가 필요
    - 일관성 있는 스타일은 나중에 수정하기도 쉽다
