### ISSUE TITLE
Dynamic Programming에 대해 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#84]

**Comment by import-max** [comment]
- 중복된 하위 문제들의 결과를 저장한 후 원래의 문제와 결과와 합하는 알고리즘이다. 중복된 문제가 없다면 다이나믹 프로그래밍을 적용할 수 없다.
- 크게 상향식 접근법과 하향식 접근법으로 나눌 수 있다.
    - 상향식 접근법 : Tabulation → 작은 문제의 정답을 이용해 큰 문제의 정답을 푸는 방식이다. 데이터를 테이블 평태로 저장한다.
    - 하향식 접근법 : Memoization → 작은 문제의 결과를 얻었는지 확인해가며 문제를 재귀로 풀어가는 방식으로, 분할 정복에서의 재귀 방식과 유사하나 이미 푼 문제인지 검사한다.

**Comment by kimyuuuuuu** [comment]
- **중복된 하위 문제들의 결과를 저장**한 후 원래 문제의 결과와 합하는 알고리즘
- 다이나믹 프로그래밍과 분할 정복 알고리즘의 큰 차이점은 **중복된 문제**의 차이
    - 분할 정복 알고리즘을 사용한 병합 정렬이나 퀵 정렬의 경우 하위 문제들이 중복되지 않는다.
    - 다이나믹 프로그래밍은 중복된 하위 문제들의 결과를 저장함으로써 중복 계산을 피한다

**Comment by jarammm** [comment]
> 재귀에서 발생하는 계산 중복의 문제를 해결한 것이 동적 계획법
> 
- 공통점
    - 실질적 **계산이 순차적으로** 이뤄짐
    - **순환식**의 값을 계산하는 기법들이다.
- 차이점
    - Memozation
        - top-down방식이며, 실제로 필요한 subproblem만을 푼다.
        - 중간 계산 결과를 배열에 캐싱함으로써 중복 계산을 피함
        - DFS 형식
        - 형식적으로는 위에서부터 재귀적으로 **호출**됨
        - 그러나 **계산과정**에서는 초기화되지 않은 수열들을 역행해, 결국은 맨처음 수열부터 순차적으로 구하게 됨
        - 즉, 호출과 실질적 계산의 방향이 정반대
    - Tabulation
        - 위에서부터 호출 하는 **호출 과정 자체가 부재**
        - base case는 초기에, 캐시에 직접 저장
        - 동적 계획법은 bottom-up 방식이며, recursion에 수반되는 overhead가 없다.
- 작은 문제의 답들 사이의 관계
    - Memoization : 재귀호출의 파라미터로 표현
    - Tabulation : 첨자(=인덱스, 위의 예시에서는 `f[i]`의 `i`)로 표현
- Tabulation이 필요한 경우
    - **low level programming** 시 (리눅스 커널, 임베디드 시스템 등) 허용가능한 **stack overhead**의 사이즈가 매우 작아 재귀호출이 불가한 경우 필요
