### ISSUE TITLE
텍스트 더미에서 주제를 추출해야 합니다. 어떤 방식으로 접근해 나가시겠나요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#86]

**Comment by kimyuuuuuu** [comment]
### **잠재 디리클레 할당(Latent Dirichlet Allocation, LDA)**

- 문서의 집합에서 토픽을 찾아내는 프로세스를 뜻하는 **토픽 모델링**의 대표적인 알고리즘
- "문서들은 토픽들의 혼합으로 구성되어져 있으며, 토픽들은 확률 분포에 기반하여 단어들을 생성한다"고 가정하며, 데이터가 주어지면 LDA는 토픽을 문서가 생성되던 과정을 역추적한다.
- 어떤 문서가 들어온다면, LDA는 특정 토픽에 특정 단어가 나타날 확률을 내어 줍니다.
- LDA를 통해 각 문서의 **토픽분포**와 각 **토픽 내의 단어 분포**를 추정할 수 있다.

**Comment by miinkang** [comment]
LDA 잠재 디리클레 할당 

- 텍스트 더미의 분포로부터 토픽을 뽑는다.
- 해당 토픽에 해당하는 단어들을 찾아 해당 텍스트 더미를 어떤 토픽으로 분류할지 예측한다.

딥러닝
- 토픽 모델들이 있음 (E.g. Textrank)

**Comment by jarammm** [comment]
- 비지도 학습
    - 토픽 모델링 : LDA을 통해 주제를 추출할 수 있다.
- 딥러닝
    - 요약문 추출(extractive) 방식
        - 대표 모델 : TextRank, BertSum
        - 비지도 학습 가능
    - 요약문 생성(abstractive) 방식
        - 대표 모델 : BART
        - 비지도 학습 불가능
