### ISSUE TITLE
여러분이 서버를 100대 가지고 있습니다. 이때 인공신경망보다 Random Forest를 써야하는 이유는 뭘까요?

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#87]

**Comment by kimyuuuuuu** [comment]
- 랜덤 포레스트
    - 여러 결정 트리를 **앙상블**하여 하나의 모델로 구성하는 방법이다.
    - 여러개의 decision tree를 형성하고 새로운 데이터 포인트를 각 트리에 동시에 통과시키며, 각 트리가 분류한 결과에서 투표를 실시하여 가장 많이 득표한 결과를 최종 분류 결과
    - 랜덤 포레스트에서는 각 서버를 모델의 특성을 이해하는 단일 결정 트리(의사결정모델) (Decision tree) 로 **병렬**적이게 구성할 수 있다.
        - 의사 결정 모델
            - **분류(classification)** **회귀(regression)** 모두 가능
    
- **인공신경망**은 하나의 서버 자체가 모델의 특성을 모두 이해하는 end-to-end 구조로 **직렬**적이게 구성된다.

⇒ 따라서 서버가 100대 있을 때는, 이를 **병렬적으로 활용**할 수 있는 **랜덤 포레스트**를 사용한다.

**Comment by jarammm** [comment]
- 비지도 학습
    - 토픽 모델링 : LDA을 통해 주제를 추출할 수 있다.
- 딥러닝
    - 요약문 추출(extractive) 방식
        - 대표 모델 : TextRank, BertSum
        - 비지도 학습 가능
    - 요약문 생성(abstractive) 방식
        - 대표 모델 : BART
        - 비지도 학습 불가능

**Comment by jarammm** [comment]
- 인공신경망은 각 레이어가 직렬로 연결되어 있지만, 랜덤 포레스트는 각 트리들이 병렬적으로 수행해 앙상블 하는 알고리즘이다.
- 서버가 여러 개 있을 때 랜덤 포레스트를 사용한다면 각 서버에 하나의 트리 모델을 모델링한 후 각 결과를 앙상블할 수 있다. 따라서 랜덤포레스틀 사용하는 것이 속도면에서 효율적이다.

**Comment by miinkang** [comment]
- random forest는 Tree기반의 앙상블 모델이기 때문에, 문제를 나누어 그 결과를 합친다. 서버가 여러개일 때 사용하기 용이함
- 인공신경망은 하나의 서버가 모델을 이해하고 동작하기 때문에 병렬적으로 활용할 방법이 없지만 Random forest는 100대의  서버를 병렬적으로 활용할 수 있다.
