### ISSUE TITLE
사용자 수준 스레드와 커널 수준 스레드의 차이를 설명해주세요.

### ISSUE THREAD

**Issue by miinkang** [AInsteins/AI-Tech-Interview#88]

**Comment by kimyuuuuuu** [comment]
- **사용자 수준 스레드**
    - **유저 레벨**에서 생성되고 동작하는 스레드이다.
    - 커널이 제공하는 pthread와 같은 **스레드 라이브러리**를 사용하여 스레드를 만들고, 사용자 단에서 스레드를 관리한다는 특징을 가진다.

- **커널 수준 스레드**
    - **커널 레벨**에서 생성되는 스레드로, 커널이 직접 관리한다
    - 하나의 프로세스는 적어도 하나의 커널 스레드를 가지게 되며, 프로그래머 요청에 따라 스레드를 생성하더라도, **스케줄링하는 주체가 커널**이면 커널 레벨(Kernel Level) 스레드라고 한다.

**Comment by jarammm** [comment]
- 커널 레벨 쓰레드와 유저 레벨 쓰레드는 **생성 주체가 누구냐에 따라 구분**된다.
    - 프로그래머 요청에 따라 쓰레드를 생성하고 스케줄링하는 주체가 커널이면 **커널 레벨(Kernel Level) 쓰레드**라고 한다.
    - 커널에 의존적이지 않은 형태로 쓰레드의 기능을 제공하는 라이브러리를 활용할 수 있는데 이러한 방식으로 제공되는 쓰레드가 **유저 레벨(User Level) 쓰레드**이다.

**Comment by miinkang** [comment]
- 스레드 : 프로세스 내 작업 단위
- 커널 수준 스레드
    - 커널 레벨에서 생성되는 스레드
    - 커널이 직접 관리
    - 주기억 장치에 프로세스 여러 개가 적재되기 때문에 CPU할당을 기다리며 동작함
- 사용자 수준 스레드
    - 사용자 단에서 생성, 관리되는 스레드
    - 커널 레벨 밖에 있는 스레드
    - 실제로는 커널 내부에 있지만 커널모드가 아닌 사용자 모드에서 동작함
- 컨텍스트 스위칭이 있고 없고의 차이
    - 커널 수준 스레드는 CPU할당을 기다리기 때문에 컨텍스트 스위칭이 있음
    - 컨텍스트 스위칭 : 인터럽트 발생으로 현재 작업중인 프로세스가 BLOCK되고 다른 프로세스로 변경할 때 CPU내 재배치 레지스터에 다음에 실행할 프로세스 정보들로 교체하고 캐시를 비우는 것
    - 컨텍스트 스위칭은 오버헤드 발생등이 생길 수 있음
