### ISSUE TITLE
다익스트라

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#89]

**Comment by miinkang** [comment]
다익스트라 알고리즘

- 다이나믹 프로그래밍을 이용한 최단 경로 찾기 알고리즘
- 너비우선탐색(BFS)을 기본으로 한다.
- 가중치가 있을 때 최단 경로를 찾기에 BFS, DFS는 어렵기 때문에 생긴 알고리즘
- 음수 가중치가 있으면 사용할 수 없다.
    - 정점을 지날수록 가중치가 증가한다라는 사실을 전제하고 쓰여진 알고리즘
    - 음의 가중치가 있으면 전제가 무너지기 때문에 계산할 수 없음
    - 음의 가중치가 있을 떄 최단 거리를 계산하는 알고리즘 : 벨만-포드 알고리즘
- 우선순위 큐를 사용해서 최단 거리 값을 갱신 횟수를 줄인다.
- 큐에 각 정점까지의 거리 값을 저장해놓고 최단 거리로 이동하면서 거리 값을 갱신한다.

**Comment by jarammm** [comment]
- 자료 구조로는 `graph` 를 사용
- **노드**와 **가중치를 가진 간선** 을 이용하여 실제 거리 표현
- 풀이 과정
    1. 출발 노드와, 도착 노드를 설정알고 있는 모든 거리 값을 (단방향 or 양방향으로) 부여
    2. 출발 노드부터 방문하지 않은 인접 노드를 방문, 거리를 계산한 후, 현재 알고있는 거리보다 짧으면 해당 값으로 갱신한다.
    3. 현재 노드에 인접한 모든 미방문 노드까지의 거리를 계산했다면, 현재 노드는 방문한 것이므로, 미방문 노드 리스트에서 제거한다.
    4. 도착 노드가 미방문 노드 리스트에 없으면 종료한다.
- 다익스트라 알고리즘을 실행 하는 중에는 **방문하지 않은 인접 노드**를 방문하는 부분이 있습니다. 이 부분에서 **우선순위 큐**를 사용 하면, **지금까지 발견된 가장 짧은 거리의 노드에 대해서 먼저 계산**할 수 있으며, **더 긴 거리로 계산 되었을 시 스킵** 또한 가능합니다.
