### ISSUE TITLE
p-value를 모르는 사람에게 설명한다면 어떻게 설명하실 건가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#9]
[3차시] 2022년 8월 30일 화요일

**Comment by jarammm** [comment]
- 유의수준 : **제 1종 오류(귀무가설을 잘못하여 기각하는 것)**를 범할 확률의 최대값을 α라 표기하고 우리는 이 α값을 유의수준(significance level)이라 합니다. 유의수준이 0.05라면 5% 이하 정도의 1종 오류의 발생은 무시해도 괜찮다는 의미가 됩니다.
- p-value(유의확률 = p값 = significance probability) : 귀무가설이 참이라는 전제아래에서, 계산된 검정통계량이 귀무가설을 얼마나 지지하는지 나타내는 확률. 기존의 귀무가설에 대한 유의수준보다 작아야 대립가설이 채택될 가능성이 있음
- p-value가 유의 수준보다 작다면 실험의 오류가 상한선보다 작으므로 귀무가설을 기각하고 대립가설을 채택합니다.
- p-value가 유의 수준보다 작다는 것은 어떤 사건(가설 검증 시의 대립가설)이 우연히 발생할 확률이 유의 수준보다 낮다는 의미입니다. 즉 우연히 일어난 사건일 가능성이 거의 없다고 보는 것, 인과관계가 있다고 추정하는 것, 결과적으로 유의미하다고 해석된다는 의미입니다.

**Comment by import-max** [comment]
1. p-value를 모르는 사람에게 설명한다면 어떻게 설명하실 건가요?
- 어떤 가설을 전제로, 그 가설이 맞다는 가정 하에 내가 현재 구한 통계값이 얼마나 자주 나을 것인가를 의미한다. 처음 세운 가설을 귀무가설이라고 하는데, 귀무가설이 틀렸다는 것을 증명하는 가설을 대립가설이라고 한다. 무죄추정의 원칙처럼 이렇게 귀무가설을 기각하는 과정에서 생길 수 있는 오류가 있다. 만약 가설이 참인데 거짓이라고 한 경우 오류가 발생하는데, 이러한 오류가 발생할 확률을 p-value 라고 한다.
- 이 또한 확률이기 때문에, 예를 들어 p-value가 0.05라면 이는 5%라는 확률이고, 5%의 확률로 해당 오류를 범했다는 뜻이다.

**Comment by kimyuuuuuu** [comment]
### p-value?

- **우리가 얻은 검정 통계량보다 크거나 같은 값을 얻을 수 있을 확률**
- 1종 오류란 **귀무가설이 참인데 기각한 경우**을 말한다. 귀무가설이란 기존의 주장을 말하며, 이와 반대로 새로운 주장을 대립가설
- p-value는 **1종 오류를 범할 확률**
- 귀무가설(null hypothesis, H0)이 맞다는 전제 하에, 통계값(statistics)이 실제로 관측된 값 이상일 확률을 의미

**Comment by miinkang** [comment]
- p-value(유의확률)은 검정 통계량에 관한 확률이며, 통계적 가설 검정에서 사용됩니다. 가설검정은 대상에 대한 가설을 설정하고 검토하는 통계적 추론을 뜻합니다. p-value는 귀무가설이 맞다는 전제 하에 표본에서 실제로 관측된 통계치와 같거나 더 극단적인 통계치가 관측될 확률을 뜻합니다. 
- p-value가 작다면 귀무가설을 기각하고 대립가설을 채택합니다.
