### ISSUE TITLE
힙(이진 힙)

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#90]
- min heap
- max heap

**Comment by miinkang** [comment]
이진 힙

- 힙 : 트리 기반 자료구조, 최상위 노드는 최대값을 가지는 특징이 있음
- 자식노드가 반드시 2개 이하인 트리
- 우선순위 큐를 구현하는데 적합한 자료구조
- 부모노드는 반드시 자식노드보다 큰 값을 갖는다.

**Comment by kimyuuuuuu** [comment]
- 완전 이진 트리를 기본으로 한 자료구조
- A가 B의 부모 노드이면, A의 키값과 B의 키값 사이에는 대소관계가 성립한다.
- heap의 종류에는 최소힙과 최대힙이 있다.
- 이진힙은 키값이 오름차순이거나 내림차순이다. 마지막 왼쪽 결합 노드들으 ㅣ레벨을 제외한 다른 모든 레벨들은 완전 이진 트리를 형성한다.
- $O(\log n)$
