### ISSUE TITLE
파이썬의 객체지향(OOP) 특징은 무엇인가요?

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#91]

**Comment by jarammm** [comment]
- 객체 지향의 특징 : 캡슐화(언더바 2개), 상속, 다형성(ex.오버로딩)
- 객체 : 속성 + 행동
- 객체지향프로그래밍 : 독립된 객체들 간의 상호작용으로 파악하는 프로그래밍 접근법

**Comment by kimyuuuuuu** [comment]
- 객체 지향의 특징인 **캡슐화(encapsulation), 상속(inheritance), 다형성(polymorphism)**을 모두 가지고 있다. 
- **클래스(Class)와 인스턴스(Instance) 객체 생성**
