### ISSUE TITLE
누적 분포 함수와 확률 밀도 함수는 무엇인가요? 수식과 함께 표현해주세요.

### ISSUE THREAD

**Issue by jarammm** [AInsteins/AI-Tech-Interview#92]

**Comment by miinkang** [comment]
누적 분포 함수

- 주어진 확률변수가 특정 값보다 작거나 같을 확률을 나타내는 함수

확률 밀도 함수 

- 연속확률 변수 x 에 대해서 f(x)가 누적 분포 함수일 떄 확률 밀도 함수의 정의
- 연속확률변수 : 확률변수 x가 임의의 실수 집합 B에 포함되는 사건의 확률이 어떤 음이 아닌 함수 f의 적분으로 주어질 때의 x를 연속확률변수라고 함
- 이때 음이 아닌 함수 f를 확률 밀도 함수라고 한다.

둘의 관계

- 미분과 적분의 관계를 갖는다.
- 확률 밀도 함수를 음의 무한대에서 특정값 a까지 적분을 하면 a에 대한 누적 분포 함수를 얻을 수 있다. 반대의 경우도 가능하다.

**Comment by jarammm** [comment]
- 누적 분포 함수 CDF(Cumulative Distribution Function) : 음의 무한대에서 특정 값까지의 분포 확률을 나타냄

$$
⁍
$$

- 확률 밀도 함수 PDF(Probability Density Function) : 특정 구간의 확률을 나타냄
    
    $$
    F(x) = \int^x_{-\infty}{f(x)dx}
    $$
    
- 확률 밀도 함수와 누적 분포 함수는 **미분과 적분의 관계**
    - 확률 밀도 함수 → 음의 무한대에서 특정값 $a$까지 적분을 하면, $a$에 대한 누적 분포 함수
    - 누적 분포 함수 → 미분하면 확률 밀도 함수
