### ISSUE TITLE
캐시의 지역성에 대해 설명해주세요.

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#95]

**Comment by miinkang** [comment]
캐시

- 속도가 빠른 장치와 느린 장치에서 속도 차이에 따른 병목 현상을 줄이기 위한 메모리
- 주기억장치에서 자주 사용하는 프로그램, 데이터를 저장해 속도를 빠르게하는 메모리
- 주기억장치와 CPU사이에 위치
- 주기억장치를 접근하는 횟수가 줄어들어 컴퓨터의 처리속도가 향상된다.

캐시의 지역성

- 지역성 : 데이터 접근이 시간적, 공간적으로 가깝게 일어나는 것
- 캐시가 효율적으로 동작하기 위해서는 캐시의 적중률(요청한 데이터를 캐시 메모리에서 찾을 확률, hit)을 극대화해야 한다.
- 한 순간에 특정 부분을 집중적으로 참조하는 특성, 균등하게 엑세스하지 않음

지역성의 종류

- 시간적 지역성
    - 최근 참조된 주소의 내용은 곧 다음에 다시 참조되는 특성
- 공간적 지역성
    - 실제 프로그램이 참조된 주소와 인접한 주소의 내용이 다시 참조되는 특성
    - 특정 데이터와 가까운 주소가 순서대로 접근되면, 해당 블록을 전부 캐시에 가져온다.
- 순차적 지역성
    - 분기가 발생하지 않는 한 명령어는 메모리에 저장된 순서대로 인출, 실행된다.

**Comment by import-max** [comment]
- **캐시 메모리**는 CPU의 처리 속도와 메모리의 속도 차이로 인한 병목현상을 완화하기 위해 사용하는 고속 버퍼 메모리이다. 이 버퍼링 시간을 줄이기 위해 데이터를 빠르게 액세스하여 속도 차이를 줄일 수 있도록 중간에 캐시 메모리를 두는 것이다.
- 시간적 지역성 : CPU가 한 번 참조한 데이터는 다시 참조할 가능성이 높다.
- 공간적 지역성 : CPU가 참조한 데이터와 인접한 데이터 역시 참조될 가능성이 높다.
- 순차적 지역성 : 분기가 발생하지 않는 한 명령어는 메모리에 저장된 순서대로 인출/실행된다.

지역성은 어디까지나 경향에 대한 것이므로 항상 캐시의 높은 적중률을 보장해 주지는 않는다.

**적중률(Hit rate)**

캐시 메모리가 있는 컴퓨터 시스템은 CPU가 메모리에 접근하기 전 먼저 캐시 메모리에서 원하는 데이터의 존재 여부를 확인한다. 이때 필요한 데이터가 있는 경우를 적중(hit), 없는 경우를 실패(miss)라고 한다.

**요청한 데이터를 캐시 메모리에서 찾을 확률**을 **적중률(hit rate)**이라고 한다.

캐시 메모리의 성능은 적중률에 의해 결정된다.

**Comment by kimyuuuuuu** [comment]
- **캐시 메모리**
    - CPU의 처리 속도와 메모리의 속도 차이로 인한 병목현상을 완화하기 위해 사용하는 고속 버퍼 메모리이다.
    
- `적중률(Hit rate)`을 극대화하기 위해 데이터 `지역성(Locality)의 원리`를 사용
- 데이터의 지역성
    - **시간적 지역성(temporal locality)**: CPU가 한 번 참조한 데이터는 다시 참조할 가능성이 높다.
    - **공간적 지역성(spatial locality)**: CPU가 참조한 데이터와 인접한 데이터 역시 참조될 가능성이 높다.
    - **순차적 지역성(sequential locality)**: 분기가 발생하지 않는 한 명령어는 메모리에 저장된 순서대로 인출/실행된다.
    - 지역성은 어디까지나 경향에 대한 것이므로 항상 캐시의 높은 적중률을 보장해 주지는 않는다.

**Comment by jarammm** [comment]
- **주기억장치에서 자주 사용하는 프로그램과 데이터를 따로 저장해두어 속도를 빠르게 하는 메모리**
    - 따라서 캐시는 주기억장치보다 크기가 작다. 캐시의 크기는 보통 수십 KByte ~ 수백 KByte.
    - `캐시 기억장치`와 `주기억장치` 사이에서 정보를 옮기는 것을 **매핑**이라고 함
- **속도가 빠른 장치와 느린 장치간의 속도 차에 따른 병목현상을 줄이기 위한 범용 메모리**
    - 이를 위해서는 CPU가 어떤 데이터를 원하는지 어느 정도 예측할 수 있어야 한다.
    - 캐시 메모리에 CPU가 이후에 참조할, 필요 있는 정보가 어느 정도 들어있느냐에 따라 캐시의 성능이 좌우되기 때문
- ****캐시(Cache)의 지역성(Locality)****
    - 캐시가 효율적으로 동작하려면, 캐시의 적중율(Hit-rate)를 극대화 시켜야 한다.
    - 캐시에 저장할 데이터가 **지역성(Locality)**을 가져야 한다.
    - 지역성이란, **데이터 접근이 시간적, 혹은 공간적으로 가깝게 일어나는 것**을 의미한다.
    - 지역성의 전제 조건으로 프로그램은 모든 코드나 데이터를 균등하게 Access하지 않는다는 특성을 기본으로 한다.
    - 즉, **지역성(Locality)**이란 기억장치 내의 정보를 균일하게 Access하는 것이 아닌 **어느 한 순간에 특정 부분을 집중적으로 참조하는 특성**이다.
- **지역성(Locality)의 종류**
    - **시간적 지역성**
        - 특정 데이터가 한번 접근되었을 경우, 가까운 미래에 또 한번 데이터에 접근할 가능성이 높은 것
        - 메모리 상의 같은 주소에 여러 차례 읽기 쓰기를 수행할 경우, 상대적으로 작은 크기의 캐시를 사용해도 효율성을 꾀할 수 있다.
    - **공간적 지역성**
        - 특정 데이터와 가까운 주소가 순서대로 접근되었을 경우.
        - CPU 캐시나 디스크 캐시의 경우 한 메모리 주소에 접근할 때 그 주소뿐 아니라 해당 블록을 전부 캐시에 가져오게 된다.
        - 이때 메모리 주소를 오름차순이나 내림차순으로 접근한다면, 캐시에 이미 저장된 같은 블록의 데이터를 접근하게 되므로 캐시의 효율성이 크게 향상된다.
