### ISSUE TITLE
Local Minima 문제에도 불구하고 딥러닝이 잘 되는 이유는?

### ISSUE THREAD

**Issue by kimyuuuuuu** [AInsteins/AI-Tech-Interview#96]

**Comment by miinkang** [comment]
- local minima 문제는 고차원의 데이터를 학습하는 딥러닝에서는 발생하기 어려움
- Weight가 굉장히 많은데 이 많은 weight가 모두 Local minima에 빠지기 어렵기 때문

**Comment by jarammm** [comment]
- 딥러닝은 층을 많이 쌓아 고차원인 경우가 대다수인데, local minima문제는 고차원의 공간일수록 발생 확률이 낮기 때문이다.
    - 고차원일수록 가중치가 많고, 그 많은 가중치가 모두 local minima에 빠져야 가중치 업데이트가 중단된다.
- 차원만큼 많은 좌표 축이 생길텐데 그 많은 모든 축의 방향으로 오목한 형태가 형성된다는 것은 확률적으로 매우 희박하다.

**Comment by import-max** [comment]
- 고차원의 공간에서는 발생하기 힘든, 매우 희귀한 경우이다. 실제 딥러닝 모델에서는 weight가 수도없이 많으며, 그 수많은 weight가 모두 local minima에 빠져야 weight update가 정지되기 때문에 local minima는 큰 문제가 되지 않는다.

**Comment by kimyuuuuuu** [comment]
고차원(High Dimensional)의 공간에서는 발생하기 힘든, 매우 희귀한 경우이기 때문이다.
-> 고차원이라 엄청난 수의 weight가 있는데 이 weight들이 모두 local minima에 빠져야 weight update가 정지 되기 때문에 사실상 큰 문제가 되지 않는다
