### ISSUE TITLE
쿠키(Cookie)와 세션(Session)을 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#97]

**Comment by miinkang** [comment]
- http 프로토콜 환경 : 서버는 클라이언트가 누구인지 매번 확인해야한다.
- 위와 같은 connectionless, stateless 한 특성을 보완하기 위해 쿠키, 세션을 사용함
- 세션은 서버의 자원을 사용하기 때문에 무분별하게 만들다보면 서버의 메모리가 감당할 수 없어질 수가 있고 속도가 느려질 수 있기 때문에 쿠키가 유리한 경우가 있음

쿠키

- 클라이언트 로컬에 저장되는 키와 값이 들어있는 작은 데이터 파일
- 클라이언트의 상태 정보를 로컬에 저장했다가 참조한다.
- 사용자가 따로 요청하지 않아도 브라우저가 request시에 request header를 넣어서 자동으로 서버에 전송한다.
- 사용 예시
    - 로그인시 아이디와 비밀번호 저장
    - 팝업의 오늘 더이상 이 창을 보지 않음
    - 쇼핑몰 장바구니

세션

- 쿠키를 기반하고 있지만, 사용자 정보 파일을 브라우저에 저장하는 쿠키와 달리 세션은 서버 측에서 관리
- 서버에서는 클라이언트를 구분하기 위해 세션 ID를 부여하며 웹 브라우저가 서버에 접속해서 브라우저를 종료할 때까지 인증상태를 유지한다.
- 사용자에 대한 정보를 서버에 두기 때문에 쿠키보다 보안에 좋지만, 사용자가 많아질수록 서버 메모리를 많이 차지하게 된다.
- 세션도 결국 쿠키를 사용한다.

쿠키, 세션 차이점

- 보안 면에서 세션이 더 우수하며, 요청 속도는 쿠키가 세션보다 더 빠르다. 세션은 서버의 처리가 필요하기 때문
- 사용자의 정보가 저장되는 위치가 가장 큰 차이점

**Comment by jarammm** [comment]
1. 쿠키
    1. 클라이언트의 로컬에 저장되는 작은 데이터 파일
    2. 모든 정보들을 서버에 저장하면 한정된 서버 메모리가 이를 감당하기 어렵고 속도도 느려질 수 있어서 쿠키를 사용하는 것
    3. 장점 : (쿠키 유효기간에 따라)브라우저를 닫아도 정보가 사라지지 않는다, 서버 메모리 사용량을 줄일 수 있다
    4. 단점 : 보안이 약하다(따로 쿠키를 삭제하지 않으면 정보가 계속 유효할 수 있음)
2. 세션
    1. 클라이언트가 서버 접속 시 세션 ID를 부여받는데, 서버는 이 ID를 통해 각 클라이언트들을 구별하여 개별 요청을 들어주고 각 세션 ID를 쿠키를 사용해 리퀘스트 헤더에 담아 클라이언트로 전달
    2. 장점 : 보안면에서 쿠키보다 우수하여 보안상 중요한 작업 수행 시 사용
    3. 단점 : 사용자가 많아질수록 서버 메모리 크게 차지함

**Comment by kimyuuuuuu** [comment]
- 쿠키
    - 쿠키는 **클라이언트(브라우저) 로컬에 저장되는 키와 값이 들어있는 작은 데이터 파일**
    - 사용자 인증이 유효한 시간을 명시할 수 있으며, 유효 시간이 정해지면 브라우저가 종료되어도 인증이 유지된다는 특징이 있다.
    - 쿠키는 클라이언트가 서버로 request를 보냈을 때 서버에서 쿠키를 생성해 클라이언트에 응답 시 response header에 쿠키를 넣어 응답합니다. 이 응답에서 클라이언트는 response header의 쿠키를 추출하여 클라이언트에 저장해둡니다. 그리고 이 쿠키값을 클라이언트가 서버에 request 요청을 보낼 때마다 HTTP가 해당 쿠키를 찾아 header에 자동으로 넣어 전송하여 쿠키를 이용해 사용자를 인증하게 됩니다.
- 세션
    - 쿠키를 기반하고 있지만, 사용자 정보 파일을 브라우저에 저장하는 쿠키와 달리 세션은 **서버 측에서 관리**
    - . 서버에서는 클라이언트를 구분하기 위해 세션 ID를 부여하며 웹 브라우저가 서버에 접속해서 브라우저를 종료할 때까지 인증 상태를 유지한다.
    - 클라이언트가 Request를 보내면, 해당 서버의 엔진이 클라이언트에게 유일한 ID를 부여하는 데 이것이 세션 ID다

**Comment by import-max** [comment]
### 쿠키

- 쿠키는 클라이언트 로컬에 저장되는 key, value가 들어있는 데이터 파일이다. 클라이언트의 상태 정보를 로컬에 저장했다가 참조하며 사용자가 따로 요청하지 않아도 브라우저가 요청 시에 Request Header를 넣어서 자동으로 서버에 전송한다.
- 동작 방식
    - 클라이언트가 페이지를 요청 → 서버에서 쿠키 생성 → HTTP 헤더에 쿠키를 포함시켜 응답 → 브라우저가 종료되어도 쿠키 만료 기간이 있다면 클라이언트에서 보관 → 같은 요청을 할 경우 HTTP 헤더에 쿠키를 함께 보냄 → 서버에서 쿠키를 읽어 이전 상태 정보를 변경할 필요가 있을 때 쿠키를 업데이트하여 변경된 쿠키를 HTTP 헤더에 포함시켜 응답

### 세션

- 세션은 쿠키를 기반하고 있지만, 서버 측에서 관리한다. 서버에서는 클라이언트를 구분하기 위해 세션 ID를 부여하며 웹 브라우저가 서버에 접속해서 브라우저를 종료할 때까지 인증 상태를 유지한다.
- 접속 시간에 제한을 둔다. 사용자에 대한 정보를 서버에 두기 때문에 쿠키보다 보안에 좋지만, 사용자가 많아질수록 서버 메모리를 많이 차지하게 된다. 예를 들어 동시접속자 수가 많은 웹 사이트인 경우 서버에 과부하를 주게 되므로 성능 저하의 요인이 된다. 
클라이언트가 Request를 보내면, 해당 서버의 엔진이 클라이언트에게 유일한 ID(세션ID)를 부여한다.
