### ISSUE TITLE
동기와 비동기의 차이를 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#98]

**Comment by miinkang** [comment]
동기

- 요청에 대한 결과를 받은 후에 다음 요청을 진행
- 요청과 결과가 동시에 일어난다는 약속
- 직관적인 구조이나 비효율적

비동기

- 요청 결과에 관계 없이 바로 다음 요청을 수행
- 결과는 콜백 함수를 통해 받음
- 설계가 복잡하나 효율적

**Comment by kimyuuuuuu** [comment]
- **동기**
    - 요청에 대한 결과를 받은 후에야 다음 요청을 진행하는 방식으로 결과를 받을 때까지 대기해야한다. 동기는 직관적인 구조이지만 비효율적이다.
    - **System Call이 끝날때까지 프로그램은 대기해야 하고 System Call이 완료가 되면 그때야 Return 한다.**
- **비동기**
    - 요청 결과에 관계 없이 바로 다음 요청을 수행하고, 결과는 `콜백` 함수를 통해 받는다. 비동기는 설계가 복잡하지만 효율적이다.
    - **System Call이 완료되지 않아도 대기하지 않고 Return 해버린다.**
- 차이점
    - **프로그램이 바로 실행할 수 있는 유무가 다르다.**

**Comment by jarammm** [comment]
1. 동기(synchronous)
    1. 특징
        1. 데이터 요청과 그 응답이 순차적으로 일어나는 것을 말한다
        2. 유저가 서버에 데이터를 요청하면, 그에 대한 응답이 유저에게 리턴될 때까지 유저는 대기 상태로, 다른 활동을 할 수 없다
    2. 장점 : 설계가 매우 간단하고 직관적
    3. 단점 : 응답이 올 때까지 아무것도 못하고 대기해야 한다
    4. 예시 : 단순히 파이썬 코드를 실행시켰을 때 매 줄마다 차례로 실행되는 것
2. 비동기(Asynchronous)
    1. 특징
        1. 동기와 반대로, 요청한 결과를 꼭 기다릴 필요는 없도록 클라이언트-서버 간 데이터 처리가 이뤄진다
        2. 유저가 서버에 데이터 요청 시, 응답을 기다리면서 동시에 다른 요청을 보내도 된다
    2. 장점 : 요청에 따른 응답을 기다리는 동안 다른 작업 수행이 가능
    3. 단점 : 동기 방식보다 설계가 복잡
    4. 예시 : 멀티 스레딩으로 코드 실행하는 것
    5. 멀티스레딩 코드

**비동기식으로 작동하는 자바의 멀티 스레드 코드**

```java
public class Asynchro {
	public static void main(String[] args) {
	
	
		Thread t1 = new Thread(()->{
			method1();
		});
		Thread t2 = new Thread(()->{
			method2();
		});
		Thread t3 = new Thread(()->{
			method3();
		});
		
		
		t1.start();
		t2.start();
		t3.start();
		
	}
	
	public static void method1() {
		System.out.println("method1");
	}
	public static void method2() {
		System.out.println("method2");
	}
	public static void method3() {
		System.out.println("method3");
	}
}
```

**Comment by import-max** [comment]
- 동기는 요청 후 결과를 받아야 다음 단계를 진행하기 때문에 비효율적이지만 직관적이다.
- 비동기는 결과 수신 여부에 관계 없이 다음 단계를 진행하기 때문에 효율적이다. 결과는 `callback` 함수를 통해 받을 수 있다.
