### ISSUE TITLE
Hash table이란?

### ISSUE THREAD

**Issue by import-max** [AInsteins/AI-Tech-Interview#99]

**Comment by kimyuuuuuu** [comment]
- 해시 테이블은 (Key, Value)로 데이터를 저장하는 자료구조 중 하나로 빠르게 데이터를 검색할 수 있는 자료구조
- 빠른 검색속도를 제공하는 이유는 내부적으로 배열(버킷)을 사용하여 데이터를 저장하기 때문
- 각각의 Key값에 해시함수를 적용해 배열의 고유한 index를 생성하고, 이 index를 활용해 값을 저장하거나 검색하게 된다. 여기서 실제 값이 저장되는 장소를 버킷 또는 슬롯
- 해시 함수에서 중요한 것은 고유한 인덱스 값을 설정하는 것이다. 해시 테이블에 사용되는 대표적인 해시 함수로는 아래의 3가지가 있다.
1. Division Method: 나눗셈을 이용하는 방법으로 입력값을 테이블의 크기로 나누어 계산한다.( 주소 = 입력값 % 테이블의 크기) 테이블의 크기를 소수로 정하고 2의 제곱수와 먼 값을 사용해야 효과가 좋다고 알려져 있다.
2. Digit Folding: 각 Key의 문자열을 ASCII 코드로 바꾸고 값을 합한 데이터를 테이블 내의 주소로 사용하는 방법이다.
3. Multiplication Method: 숫자로 된 Key값 K와 0과 1사이의 실수 A, 보통 2의 제곱수인 m을 사용하여 다음과 같은 계산을 해준다. h(k)=(kAmod1) × m
4. Univeral Hashing: 다수의 해시함수를 만들어 집합 H에 넣어두고, 무작위로 해시함수를 선택해 해시값을 만드는 기법이다.
- 해쉬값이 충돌하는 경우
    - 분리 연결법 : 동일한 버킷의 데이터에 대해 자료구조를 활용해 추가 메모리를 사용하여 다음 데이터의 주소를 저장하는 것
    - 개방주소법 : 비어있는 해시 테이블의 공간을 활용하는 방법
- 시간복잡도는 O(1)
- 삽입, 삭제, 탐색에 대해 해시 충돌이 일어나지 않는 경우에 $O(1)$, 충돌이 일어난다면 최악의 경우에 $O(N)$의 시간 복잡도를 가진다

**Comment by miinkang** [comment]
- (key, value)로 데이터를 저장해 빠르게 데이터를 검색할 수 있는 자료구조
- 내부적으로 배열을 사용해 데이터를 저장해 빠른 검색속도가 가능함
- 각 key값에 해시함수를 적용해 배열의 고유한 index를 생성함
- 시간복잡도 : O(1)
- 해시 충돌 해결방법
    - 분리 연결법 (Separate chaining) : 추가 메모리를 사용해 다음 데이터의 주소를 저장, 확장이 필요 없음
    - 개방주소법 (open addressing) : 비어있는 해시 테이블의 공간을 활용하는 방법

**Comment by jarammm** [comment]
- 정의 : 키에 데이터를 저장하는 데이터 구조로, 키를 이용해 데이터를 바로 리턴할 수 있어 속도가 빠르다. 파이썬의 딕셔너리 타입이 그 예시이다.
- 사용방법 : 대개 사전에 필요한 사이즈의 해시 테이블 생성 후 사용
- 용도
    - 검색이 빈번하게 발생할 경우
    - 저장, 삭제, 읽기 등의 수행이 잦을 경우
    - 캐시 구현할 경우(중복 값 확인에 용이)
- 장점 : 데이터 검색 속도가 빠름, 키에 대한 데이터 존재여부 확인이 쉬움
- 단점 : 저장공간이 많이 필요함, 여러 키에 해당하는 주소가 동일하면 충돌 해결을 위한 별도의 자료구조가 필요하게 됨
- 시간 복잡도 : $O(1)$ ~ $O(n)$
- chaining기법 : 시간 복잡도가 $O(n)$일 경우는 모든 시행에서 충돌이 발생(즉 데이터를 저장하려는 주소에 이미 값이 존재할 때)하는 경우이다. 이는 링크드 리스트를 이용한 체이닝 기법으로 해결할 수 있다. 이때 저장하려는 주소에 값이 있다면 해당 주소에 노드를 추가하여 값을 저장하고, 기존의 노드가 추가된 노드를 가리키도록 구현한다.

<aside>
🤗 용어
1. 해시(hash) : 임의 값을 고정 길이로 변환하는 것
2. 해시 테이블(hash table) : 키값의 연산에 의해 직접 점근이 가능한 데이터 구조
3. 해싱 함수(hashing function) : 키에 대한 산술 연산을 이용해 데이터 위치를 찾을 수 있는 함수
4. 해시값(hash value), 해시주소(hash address) : 키를 해싱함수로 연산해서 해시값을 알아내고, 이를 기반으로 해시 테이블에서 해당 키에 대한 데이터 위치를 일관성 있게 찾을 수 있음
5. 슬롯(slot) : 한 개의 데이터를 저장할 수 있는 공간

</aside>

**Comment by import-max** [comment]
- Key-value 로 데이터를 저장하는 자료구조로, 빠른 속도를 자랑한다. 내부적으로 배열을 사용하여 데이터를 저장하고 각 key 값에 해시함수를 적용하여 고유 index를 생성하고 이를 통해 값을 저장하거나 검색할 수 있다.
- 평균 시간복잡도는 $O(1)$ 이지만, 충돌이 일어나는 최악의 경우에는 $O(N)$ 의 시간복잡도를 가진다.
